### ISSUE TITLE
Allow Evade To Apply To Aero Unit Even If Player Overshoots Movement

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#1021]
### Environment
Megamek 0.44.0
Java 8
Windows 8.1

### Description
If the player overshoots the aero's movement capability and gets all the grey hexes and then clicks [Evade] megamek will draw the "Evade" text is grey over the ending hex but, will not apply it to the unit if the player then clicks done.  So, player must press escape and redo the movement so his/her cursor ends on the last hex to then enable evade.  Am just asking if megamek could be a little more forgiving to the player and still apply evade even if they overshoot it.

### Files
![image](https://user-images.githubusercontent.com/16950832/42299764-9cc8e21c-7fd2-11e8-9358-3997a9ffed5f.png)

**Comment by HoneySkull** [comment]
After taking a deep look at the possibility registering an evade step when the move path is into the illegal steps, I found it would be difficult to get right since there is a MP cost to evading along with the way only legal steps get processed by the server.

Maybe a next best solution is to provide a convenient way to unwind to the last legal step by adding a Shift-Backspace or a modifying the ESC key function so that instead of resetting the whole move, it only removes the illegal move steps and if there are no illegal move steps, then removes all?  At least this way it would be convenient to overshoot and then it's just one keystroke to get back to the last legal move.

**Comment by Sleet01** [comment]
> Maybe a next best solution is to provide a convenient way to unwind to the last legal step by adding a Shift-Backspace or a modifying the ESC key function so that instead of resetting the whole move, it only removes the illegal move steps and if there are no illegal move steps, then removes all? At least this way it would be convenient to overshoot and then it's just one keystroke to get back to the last legal move.

I've been wanting this as well, as I've been testing ASF on ground maps a lot and rewinding to the last good step would have saved me a ton of time.
