### ISSUE TITLE
[Feature Request] Unofficial option for removing shield encumbrance rules

### ISSUE THREAD

**Issue by Marshymallow** [MegaMek/megamek#108]
This is probably an issue that only I have, but I'm using Megamek for creating mobile suits from Gundam and as such there are some definite areas where the rules of Battletech don't entirely fit. While I can entirely understand if this is thoroughly unnecessary seeing as it's extremely specific, the rule making it so medium and heavy shields reduce and remove jumpjet capabilities respectively heavily damages what I am intending to do and is hopefully an easy thing to change. If it seems like this is a completely unnecessary addition for this program, I would appreciate if someone could at least point me in the right direction for changing it myself if it isn't core functionality that would take ages to remove properly.

**Comment by arlith** [comment]
We could potentially implement this as an unofficial rule, however I feel like it is very specific to your purposes, and I'm concerned about adding too many optional rules.  If there is a deficiency in the canon rules, and an unofficial option would make it better for a large part of the player base, I would be okay with it, but since it's fairly specific, I would not want to actually add this unofficial option.

If you would like to make the changes yourself, it doesn't look to be too difficult.  At least for large shields, the code looks to be at line 1171 of Mech.java (in `Mech.getJump(2)`).  On that line, there's a `MiscType.S_SHIELD_LARGE` reference, which is defined on MiscType line 445.  There you will see that there are shield subtypes defined.  Basically, you should be able to look in the code for `S_SHIELD_LARGE` and `S_SHIELD_MEDIUM` and it should lead you right to the code you need to modify.  Hope that helps.
