### ISSUE TITLE
Support for demolition charges

### ISSUE THREAD

**Issue by giorgiga** [MegaMek/megamek#1109]
### Environment
Current github master.

### Description
Fix support for demolition charges

MM used to support planting and detonating demolition charges in buildings (rules reference: _Demolition Engineers_, at p 341 of Tactical Operations).

Apparently, this stopped working a while ago.

#### Note:
To replicate this issue, you'll need to have some infantry with the _Demolition Engineers_ specialization.
One such unit is **Commando Battlefield Infiltration Units** (_IS Advanced_).

**Comment by servo01** [comment]
I'm not having an issue with this in my game [0.45]. 

Just ran a scenario where demolition charges worked fine. I did have an issue with units that should be equipped with demolition engineers that do not load with the ability - but I was able to edit the unit in the lobby (under the configure/equipment tab) in order for them to deploy with the ability. 

The targeting and firing process is a little unwieldy, but once I figured it out I was still able to target, set, arm and detonate charges as per the TacOps rules set.

**Comment by HammerGS** [comment]
Which units didn't load with the ability?

**Comment by servo01** [comment]
It seems that stock units load without issue. 

So, apparently it was just one or two of my own custom units that were not loading properly. I should be able to sort that out in MegaMekLab.

**Comment by giorgiga** [comment]
@servo01 I did try with the stock **Commando Battlefield Infiltration Units** unit, but I couldn't find an option to place or detonate charges...

It must be just that I've looked in the wrong place :-) could you describe how to use demo charges?

**Comment by servo01** [comment]
1) Enter the hex where you wish to lay charges. 

2) Do not fire during the fire phase.

3) The infantry unit should rotate in during the physical attack phase. Right click on the hex and target the building for collapse.  

4) After targeting the building the option to Lay Explosives (bottom button below the main display) becomes lit. 

5) Continue to plant charges for the appropriate number of turns. 

6) Repeat the targeting/lay explosives process in order to FINISH planting the charge. 

7) Move the unit out of hex (optional)

8) Right click on the hex, "Touch Off Explosives" should now appear in the drop down. Once selected the detonation will occur automatically during the appropriate phase. 

* You may want to run through the process a few times, as it can be a little unwieldy and a missed phase or turn during a real game can be frustrating.

**Comment by giorgiga** [comment]
Thanks @servo01!

It works as described in current the git master too, so I'll close this ticket.

<img width="741" alt="demo" src="https://user-images.githubusercontent.com/471835/44598511-89678100-a7d3-11e8-8fe4-f85f1806f62e.png">
