### ISSUE TITLE
packaging_local broken due to incorrect pkg information

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#113]
should be ${localdir} not ${pkgdir}

**Comment by Dylan-M** [comment]
Actually, this is incorrect. It should be pkgdir throughout. However, I've ignored this so far because I have plans over the summer vacation time to completely re-work the packaging files **and** create a maven setup for the projects. This way the project can be dual ant and maven. The reasons for this are many, but mostly so that people can build the project either way. Additionally this is laying the ground work to splitting MegaMek into a couple of jars, essentially allowing us to have a MegaMekServer.jar, a MegaMekCommon.jar, and a MegaMekClient.jar. With this separation, other clients could be written much more easily. All of this is just a long term goal however, as it does involve a lot of work.

**Comment by nderwin** [comment]
I'm very interested in the Maven aspect of this and would like to help, as I have it working in the development branch of my fork.  

Something else to consider splitting out would be the Map Editor.

**Comment by Dylan-M** [comment]
A couple people have maven changes in forks, however I plan on doing it quite a bit different from any of the current approaches.

The map editor would be another one that could be good to split out, you're correct in that.

**Comment by nderwin** [comment]
When you get some time to write it up, I'd like to see the plan.
