### ISSUE TITLE
Warship weapon out of ammo 0.45.1

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#1131]
For some reason, battleships in a space game are showing no NAC ammo for their respective weapons, even though they show up properly in their unit screens when selecting them.  Saved game and MUL attached.

Note that the attached Clan Coyote zip file is actually a MUL file; just delete the .zip file extension from the file name.

[autosave.sav.gz](https://github.com/MegaMek/megamek/files/2373233/autosave.sav.gz)
[Clan Coyote Keshik Warship Fleet.mul.zip](https://github.com/MegaMek/megamek/files/2373234/Clan.Coyote.Keshik.Warship.Fleet.mul.zip)
[megameklog.txt](https://github.com/MegaMek/megamek/files/2373301/megameklog.txt)

**Comment by mkerensky** [comment]
You didn't, by chance, save the MUL in a previous version and load it in 0.45.1, did you?  There are some invalid slots in your log file and I can't actually load your MUL in the latest development version, also due to equipment slot mismatch. I can read the text, and when I added a couple of the ships (Cameron 2688 and Texas 2618) as new units their ammo matched up fine.

**Comment by BLR-IIC** [comment]
I generated that MUL using the force generator for 0.45.1.

**Comment by mkerensky** [comment]
I got the savegame to load in my copy of 0.45.1 - that has your empty ammo bins in it 

I loaded the MUL - it gives me a standard Texas 2618. I don't have your copy of the Ancestral Home custom.
I created a new fleet with the force generator - Coyote front line - and started a game with those.  
In both cases, the ammo bins match up

0.45.1 adds MML support for Warships - did you build and/or verify the Ancestral Home with it? If not, try that. The fields in the BLK changed so that older, hand-built customs don't work quite right. I had 6 or 7 of my own that had to be rebuilt. 
Can you try a few more games and see if you have this same problem again?

**Comment by BLR-IIC** [comment]
I loaded the MUL again and also added my custom _Ancestral Home_ ship and now all the naval ACs have ammo.  I really have no idea why it's different now.  

FWIW I did build the _Ancestral Home_ using MML 0.45.1 as I've been bug hunting the advanced aerospace construction rules too :)

**Comment by jayof9s** [comment]
I was just about to report a similar issue and I think I've narrowed down what caused it: In the lobby, if I configure the warship at all (commander for sure but I suspect anything) somehow all the ammo disappears.

**Comment by chrisbfisher** [comment]
This is still an issue in .46 . I can't load a warship that actually has ammo. No AC ammo. No missiles. The only things that load are standard BT weapons. What gives?
