### ISSUE TITLE
ASFs combined with isometric view causes CPU usage to jump a lot

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#114]
I noticed that in one of my games, my CPU usage was abnormally high for megamek (about 13%) even though it was my turn and the bot had finished making all of its moves.

I tried loading the save game again (without replacing the bots) and the CPU usage remained high. After fiddling with some settings, i found that turning off isometric view caused the CPU usage to drop to 0%. Turning on isometric view caused CPU usage to increase to 13% again. This only seems to happen if there are ASFs in the game.

For some reason having isometric view with ASFs seem to be causing huge CPU usage spikes even if the program is idle and there are no bots present...

![megamek2](https://cloud.githubusercontent.com/assets/1191378/14161620/f7aafa80-f730-11e5-8821-8ee92e4c4fb6.jpg)

[#battletech.zip](https://github.com/MegaMek/megamek/files/196785/battletech.zip)

**Comment by pheonixstorm** [comment]
What is the cpu usage if a ground unit is the one selected?

**Comment by Question2** [comment]
Yes. The issue occurs when an ASF is present in the game, regardless of whether it is selected or not. 

E.G. You start a game with only mechs, there is no CPU usage problem with isometric.

You start a game that includes at least 1 ASF, there is a huge CPU usage spike when isometric is turned on.

**Comment by vizax** [comment]
I tested this with a bot and myself.

In iso view, loaded with 1v1 meks, then added a RAT of an ASF on my side. What I noticed, after an initial CPU spike, was that when the board has the ASF in view, my CPU spiked (~15-20%). However, if the ASF was not in view on the board, everything was normal (~2-5%).

Also, after a while I kept the ASF in view at all times and eventually my CPU usage went back to normal (after, say ~10 minutes)

I used my resource monitor, and over the 10-15 minute game I averaged out to ~11% CPU, with spikes (of various length) 20-25%.

**Comment by Akjosch** [comment]
If I had to wager a guess, I'd say it's likely that *something* in the Aero display code causes a lot of "dirty regions", which Swing's RepaintManager tries to "fix". Often. Possibly thousands of times per second.

**Comment by arlith** [comment]
The same/similar issue was reported a while back on SF: https://sourceforge.net/p/megamek/bugs/4363/

**Comment by arlith** [comment]
Some of the changes in 909c2295 may have an effect on this.  What I found was that the `FlyOverSprite` was incredibly inefficient.  First of all, it was recomputing the whole flightpath polygon everytime `FlyOverSprite.getBounds` was called, which happens everytime the sprite was drawn.  This caused the whole flypath to be retraced in order to recompute the polygon.  In addition, for each `Coord`s in the flight path, it was necessary to retrieve the previous Coords.  Well, this was done by starting from the beginning of the flight path and iterating until the previous step was reached.... So,  the code was really inefficient *and* it was being called everytime the sprites had to be drawn.

However, what still isn't clear to me is why this would be called if the board isn't being scrolled.  As @Akjosch alluded to, `BoardView1.paintComponents` should only be called if something is signifying that a dirty area needs to be repainted.

I'm guessing that the changes in 909c2295 have probably fixed this, but I want to see if I can figure out what was causing the dirty regions.
