### ISSUE TITLE
DFA victim takes no fall damage if pushed off building onto lower building. 

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#1141]
In this case, pushed off one building onto a shorter one. 

![image](https://user-images.githubusercontent.com/19868605/45582660-c29a8a80-b881-11e8-9023-ea0c9d53cc28.png)

![image](https://user-images.githubusercontent.com/19868605/45582663-ce864c80-b881-11e8-9263-1a4f490a7ae6.png)

[DFAfallFail.sav.gz](https://github.com/MegaMek/megamek/files/2385378/DFAfallFail.sav.gz)

**Comment by VampireSeraphin** [comment]
Suggestion: Check and see if falling and displacement is making correct checks for all terrain types; landing in water, swamp, impassable terrain, etc... when affected by charge, dfa, push, or other forms of involuntary movement.

**Comment by SBBurzmali** [comment]
This bug seems to still be open, the issue is that MegaMek is calculating the height of the fall from the ground floor of the source hex to the ground floor of the destination hex plus the height of the building in the destination hex. Since the height of the building in the source hex isn't considered, the mech is never considered to have fallen.
