### ISSUE TITLE
Force Generator switching from Mechs to Protomechs for Clans that deploy them.

### ISSUE THREAD

**Issue by xStormforgex** [MegaMek/megamek#1149]
Force Generator switching from Mechs to Protomechs for Smoke Jaguars only.

### Environment
MM 0.45.1

### Description
Exact settings to reproduce only Protomechs.

Year: 3059 or 3060
Faction: Smoke Jaguar (Blood Spirit Now too)
Unit Type: Mech
Rating: Any, but Front Line or Keshik (If Blood Spirit then Front Line causes this)
Other: Not touched, left blank
Subfaction: General
Formation: Binary or Trinary (Star for Blood Spirit)
Target Weight: Any
Experience: Any
Support Forces: Unselected

Recheck settings before hitting Generate as changing Formation type will reset Rating back to Front Line. Keep hitting Generate until Protomechs start appearing. It will not switch back to Mechs, Protomechs ONLY after it switches. Testing for the Protomech issue, this seems to be a problem only with the Smoke Jaguars. Protomechs do not appear when generating Mech forces for any other Clan. Unit type still says Mech unless I switch to another Faction, then it changes itself to Protomech on Faction change. Seems something is causing it to switch to Protomechs at some point while hitting Generate for the Smoke Jaguars.

**Comment by xStormforgex** [comment]
In testing the above I set all of the Clans to Second Line or equivalent. 

Testing for another possible bug, I found that Clan Blood Spirit has this same problem when they are set to Front Line. So it appears this is not limited to just Smoke Jaguars, but changes on the unit Rating selected and may be different for each Clan.

**Comment by neoancient** [comment]
Most Clan factions that use protomechs substitute them for mechs in their normal force organization. There is a rule for these Clans that creates a chance for that substitution. I couldn't see a reason why it would continue to substitute after the first time, but I did add a check that causes it to skip the potential substitution for the root eschelon, since presumably if you wanted a protomech trinary or binary you would have made that explicit. So as of the next release it will still include protomechs binaries and trinaries at times when generating a cluster, and for certain Clans there is a chance that a mech binary or trinary will include a protomech star.
