### ISSUE TITLE
[0.45.0 : Bug] Game Non-Responsive

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#1172]
### Environment
MM 0.45.0

### Description
Game non-responsive after clicking done. No error in log. Save game attached. Just move or not move the unit and hit 'Done'.

### Files
[GameNon-Responsive.sav.gz](https://github.com/MegaMek/megamek/files/2463903/GameNon-Responsive.sav.gz)

**Comment by neoancient** [comment]
After finishing the movement for the selected unit the server moves the game to the next initiative turn, which belongs to a platoon that is already marked as done. My guess is that it was previously unloaded from a transport. With individual initiative there are no other options for that turn. Only the server changes turns, and since the client has no options for moving it just gives up and does nothing. What should be happening here is that when the server advances the turn it checks to make sure there is a valid unit for that turn, and if not keeps skipping turns until it finds one with a unit that hasn't acted.
