### ISSUE TITLE
Ghost Targets Not Working

### ISSUE THREAD

**Issue by VictorMorson** [MegaMek/megamek#125]
Ghost Targets are not currently functioning at all with ECM.  This has worked in previous versions but seems to have stopped in the last few builds.

1) Equip an ECM System and put two units on the board
2) In the movement phase, go to Systems->All Equipment and turn the ECM to Ghost Targets Mode
3) Repeat for the second unit 
4) Hit done until Ghost Targets are active (and roll a success)
5) In the firing phase, attempt to fire at each other.
6) Note no matter the maximum bonus set, no bonus is given against incoming weapons fire.

[GhostFailure3.sav.gz](https://github.com/MegaMek/megamek/files/201530/GhostFailure3.sav.gz)
[GhostTargetFailure2.sav.gz](https://github.com/MegaMek/megamek/files/201531/GhostTargetFailure2.sav.gz)
[GhostTargetsNotActive.sav.gz](https://github.com/MegaMek/megamek/files/201532/GhostTargetsNotActive.sav.gz)

**Comment by VictorMorson** [comment]
Note:  I just tested it with two clients/two different teams (not represented in the original save files):
[GhostFailure.sav.gz](https://github.com/MegaMek/megamek/files/201540/GhostFailure.sav.gz)

**Comment by arlith** [comment]
Nothing has changed with the Ghost targets code in over a year.  There is an opposed roll that happens with Ghost targets, and the attackers "ghost target override" roll is never reported, so as a user you can't really know.  The implementation of the ghost targets rules are kind of poor, but these rules were basically all rewritten in errata (to be far less ridiculous than the original TO rules for ghost targets).  Basically, I don't really want to fix any issues for the current implementation because it will get replaced when the new errata is implemented.

**Comment by arlith** [comment]
I didn't address this as clearly as I had wanted to: stepping through the code it seems like things are functioning as they had been, however there are some rounds where a targets ghost target roll succeeds, but not penalty is added because the attackers override roll is high enough.  So, just because you see a report that the ghost targets roll succeeded, it doesn't mean you will necessarily get a to-hit adjustment.

**Comment by Question2** [comment]
What is the current implementation of ghost targets then? Is it the original version in tac ops?

**Comment by pheonixstorm** [comment]
yes, the new rewritten rules have not been added yet and the devs don't see it as a high priority atm.

**Comment by Question2** [comment]
I just did some testing and it appears ghost targets dont work according to the original version.

Eagle EGL-R6 Mk IIa IIC (#battletech) needs a 2 for Ghost Targets, rolls a 8: ghost targets active.

So with a 6 MOS, the attacker needs to roll piloting + 6 or get at least a +1 hit modifier. The attacker had piloting 8 so it was impossible for him to pass the override roll.

The attacker had to roll an 8 or higher to hit (3 gunnery + 4 long range + 1 attack against nose) but was still rolling 8s and landing attacks.

[#battletech.zip](https://github.com/MegaMek/megamek/files/264645/battletech.zip)
