### ISSUE TITLE
Partial Wing won't work on Ultralight Battlemech

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megamek#1356]
### Environment
Ver 0.45.4
Windows 7

### Description

As title says. I have made an Ultralight Battlemech with 15 tonnage, and add a Partial Wing on it. Its Jump MP is 3 on MegaMekLab and preview of MegaMek, but when I add it on the roaster at MegaMek it says it only has Jump MP 2.

I have checked the atmosphere but it is standard, and the other Battlemech with Partial Wing works properly. I think that only Ultralight Battlemech - 10 and 15t - are have the problem

[There is an another issue on MegaMekLab that related with the problem.](https://github.com/MegaMek/megameklab/issues/300)

### Files
[Test Mek 01.zip](https://github.com/MegaMek/megamek/files/3237262/Test.Mek.01.zip)

**Comment by neoancient** [comment]
I suspect it checks for weight class light rather than <= light. It should be an easy fix. It's easy to forget about ultralight mechs.

**Comment by neoancient** [comment]
The method that computes the bonus has two branches: one for when the 'Mech is assigned to a game and when when there isn't. The one with no game gave a +2 to light and medium and +1 to everything else, which is why MML shows it as a +1. The one with a game object also checks atmospheric conditions and was giving the higher bonus to LM and the lower one to HA, leaving out ultralights completely, which is why MM wasn't giving any bonus at all once it's added to the game.

**Comment by binaryspica** [comment]
Ah. I suspect like that but it actually does.... Thanks.
