### ISSUE TITLE
Jumping into Water and Falling deals incorrect damage

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#138]
Link to Errata Post
http://bg.battletech.com/forums/index.php?topic=52128.0

Tested this in 41.16 by jumping a Spider into Level 4 water I failed the pilot check and only suffered one damage.

_TW pg 57.
If a unit below the water’s surface falls, it suffers normal falling damage divided by 2 (see Falling, p. 68). A unit above the water’s surface suffers normal falling damage divided by 2 for hitting the water’s surface and normal falling damage divided by 2 for the fall from the water’s surface to
the bottom of the water hex. Normal damage for hitting the water’s surface equals tonnage/10 (round up) x (# of levels fallen + 1)/2. Normal damage for hitting the bottom of the water hex equals tonnage/10 (round up) x (depth of water hex + 1)/2. Damage is resolved separately.__

[Jumping.sav.gz](https://github.com/MegaMek/megamek/files/211910/Jumping.sav.gz)

**Comment by arlith** [comment]
This issue is actually different.  I can recall fixing falling so that it matches this errata, however it would only matter for an accidental fall from above, where the unit is displaced off of a cliff, falling some number of elevations, and then hitting the ground.

In your example, there's a PSR for entering a water hex.  In this case, the falls is from the surface of the water to the bottom, which isn't covered by the errata.  There is a bug however in that the damage is incorrect.

**Comment by arlith** [comment]
The problem ultimately lies in `Server.processMovement`.  At the end of processing the `MovePath`, there's a series of checks for PSRs for various things.  One of them is jumping into water.  However, these PSRs are done *after* the `Entity` state has been updated for the movement (namely, setting elevation).  The problem in this case is that the `Entity`'s elevation is set to the depth of the hex, whereas `Server.doEntityFall` expects the `Entity` elevation to reflect the value prior to to the fall (in this case, 0).  Because the elevation is already set, it causes issues with the fall height calculations.  The fix to this is to cache the elevation then set it to 0, and if the PSR passes set it back to the cached value (if it fails, `Server.doEntityFall` sets the elevation).

I've done this, but then I found an issue with the pilot damage PSR calculation, where it was using the wrong fall elevation.  Once I fix that, I'll get this committed.

**Comment by arlith** [comment]
The problem with the PSR came from this line:

```java
roll.addModifier(fallHeight - newElevation - 1, "height of fall");
```

However, the elevation is already factored into the fallHeight, this this value was off.  I removed the subtraction by newElevation.
