### ISSUE TITLE
Feature:  Hi-Res Backgrounds

### ISSUE THREAD

**Issue by VictorMorson** [MegaMek/megamek#144]
I am opening this issue on the suggestion of the [thread](http://megamek.info/forums/index.php?topic=2350.15).

Currently it requires a considerable amount of editing of the tileset file to use a high-resolution image for the map board, and having the ability to set a map-wide background would massively improve the process (along with an invisible tile set).

I can provide any info needed here or a sample map of the current method if needed, just let me know.

**Comment by Akjosch** [comment]
Sample map would be nice (you can attach it here, I think). The idea would be to recreate your visuals as accurately as possible without it being too complicated to use.

**Comment by VictorMorson** [comment]
[Example Map.zip](https://github.com/MegaMek/megamek/files/217578/Example.Map.zip)

Sure thing - file attached.  I should note the file is actually a RAR renamed as .ZIP since it was refusing to upload as a RAR; if I should re-upload it let me know.

**Comment by Akjosch** [comment]
4800x2922 px. I'm astonished MegaMek doesn't crash and burn anywhere. :)

**Comment by VictorMorson** [comment]
I was surprised it worked so well myself!  Every now and then you get an issue where it slowly caches the file in (and the background turns to the background image) but flipping iso on/off fixes it immediately.  Other than that, it never gives us any trouble.

If this gets put in it will be amazingly helpful, editing the tileset is the hardest part of the job!

**Comment by arlith** [comment]
I'm having some issues extracting your archive.  Seems like most of the files work, but I get an error on the full-sized background JPG (which is one of the more important files, heh).  Could you try resubmitting it as a zip?

**Comment by VictorMorson** [comment]
Hey I just saw this comment, will do.
[Example Map-t2.zip](https://github.com/MegaMek/megamek/files/248332/Example.Map-t2.zip)

This feature is easily my most anticipated in a long time, for sure.  The maps have been a big hit with the group.

**Comment by arlith** [comment]
I've started working on this, and I've got an initial implementation.  It's in the branch issue#144.Hi-Res.Backgrounds.  Right now, boards now have a new keyword `background`, which allows you to specify an image stored in `data/images/board_backgrounds`.  If a board specifies a background, and the hex uses the `transparent` theme, then instead of rendering the normal base, super, and ortho images, an image is pulled from the background and rendered instead.

Here's an example:
![screenshot-5](https://cloud.githubusercontent.com/assets/13815237/15801759/a930b7ca-2a64-11e6-9194-987e5d6e4df8.png)

Right now, there are still some rendering bugs to work out, but it's coming along.

@VictorMorson, can I add your map and image to the repository and distribute them with MM?  I'd like to have some examples in the releases so people can see how this works.

**Comment by SJuliez** [comment]
A full map background image (instead of tileset) will probably feature its own woods and buildings and therefore its own shadows for these. For the elevations however Id expect them to be not very visible,at least not as visible as the BT elevations usually should be. Maybe the elevation shadows should be allowed by showing the shadows in general in drawHex() but hiding the woods&building shadows in an if {} at line 1537. They can be turned off in the client settings anyway.

**Comment by arlith** [comment]
That's a reasonable idea.  One of the bugs right now is that it looks like it's drawing the whole square hex image, instead of just the "hex" part, which I think is why the hex borders aren't showing up (getting overwritten by adjacent "squares").  That should make things stand out a bit more.

**Comment by SirMegaV** [comment]
Will it be easier when transperant theme are used, MM just ignore all the base images but maintain all other images?

**Comment by arlith** [comment]
Yes, I think so.  Originally, I had thought that the supers/orthos might interfere with the board BG.  Really, it kind of depends on how the BG imgae is designed: you could design it with features to make the supers not necessary (aka, hexes intended to be woods, are clearly wooded in the board BG).  However, I think this ends up being too restrictive.

Initially, I was somewhat concerned that the supers/orthos would look out of place with the board BG, but after testing it, I don't think that's the case.  Actually, I think it ends up looking pretty good.  Here are some examples:

![screenshot-8](https://cloud.githubusercontent.com/assets/13815237/15805597/2f4d1fd4-2af5-11e6-9cd6-d9ea77d92ec5.png)

![screenshot-9](https://cloud.githubusercontent.com/assets/13815237/15805603/4ac8d104-2af5-11e6-8823-914156ec490d.png)

I've also fixed the two issues I mentioned before.  The only issue that remains is there are some compounding rounding errors with scaling.  At the base scale, things look good, but as I zoom out, I can see some jaggedness in the board background image.  Pretty sure this is due to integer rounding/truncating somewhere.

**Comment by arlith** [comment]
Here's an example of what I wanted to try to avoid by not drawing supers/orthos:

![screenshot-10](https://cloud.githubusercontent.com/assets/13815237/15805643/34678526-2af6-11e6-96fe-cd55f7b06582.png)

What you should see here is that there are buildings in the background image, with MM  buildings superimposed over them.  Probably, this is an issue we should just ignore and leave up to the creator of the board bg image.

**Comment by arlith** [comment]
I've merged this in, so it should be in the next dev release so people can test it out. 

To get it to work, here's what I did.  Take the Carver V - Airraid.board from the previously attached zip file and add the following line to it:

`background "CarverVAirstrip.jpg"`

Then, extract the CarverVAirstrip.jpg to `data/images/board_backgrounds` (you will have to create the directory).

Then, start a new game with that board, and once the game has begun click on View>Change Tileset Theme and select the `transparent` theme.  Themes can also be set individually for hexes via the board editor.

**Comment by arlith** [comment]
I think that this ticket is probably fulfilled, but I'm going to wait until I get some feedback before closing it.

**Comment by arlith** [comment]
At the very least, this feature doesn't appear to have anything to crash and burn when not using it.  I've also contacted VictorMorson and gotten his permission to use his map, so I've added that.  With that, I'm going to close this ticket.
