### ISSUE TITLE
Infantry unimpacted by fire in buildings if above HL1

### ISSUE THREAD

**Issue by VictorMorson** [MegaMek/megamek#145]
[MrFahrenheit.sav.gz](https://github.com/MegaMek/megamek/files/217743/MrFahrenheit.sav.gz)

Requested test/bug:  Infantry are not impacted by fire if above the bottom floor level of a building
-
Step to repro:
1) Pick a unit with flamers and a foot/jump platoon
2) Pick a map such as Suburbs with multi-level buildings
3) Place the infantry on FL2+ of a building
4) Use the flamers to light the building on fire.
5) Note the infantry are not impacted until the building burns down.

Note:  This may be an extension of the general issues with infantry not taking proper damage inside of buildings, currently bugged on the other tracker; I am unsure.

**Comment by arlith** [comment]
`Server.checkForFlamingDamage` is what determines if a unit should be affected by flaming damage.  It had just checked to see if the elevation was `<= 1` to determine if it was in the fire.  I added an additional check to see if the elevation is `<= BLDG_ELEV`, since in that case elevation represents the units standing on a floor of the building.
