### ISSUE TITLE
Request: Additional option to increase Autocannon damage

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/megamek#1483]
Environment
Combined version 0.46.0
Windows 10
Java version 1.8.0_211

Description
Please can you add a Megamek option to adjust Inner Sphere autocannon to the following damage values:
AC 2: 5 damage
Light AC 2: 5 damage
LB 2-X AC: 5 damage
AC 5: 8 damage
Light AC 5: 8 damage
LB 5-X AC: 8 damage
AC 10: 12 damage
LB 10-X AC: 12 damage

**Comment by binaryspica** [comment]
What's the idea on the percentage of increased value?

**Comment by Gribbly1** [comment]
The aim is to bring the damage per tonne more broadly in line with weapons of similar range, erring on the generous side
![medium](https://user-images.githubusercontent.com/55139229/64661018-d6e47980-d43a-11e9-9418-c67040bc3956.PNG)
![long](https://user-images.githubusercontent.com/55139229/64661021-da780080-d43a-11e9-9698-98a835ff588c.PNG)

.
The AC 2 would be more comparable with the ER large laser and ER PPC, but still well short of the gauss rifle and LRM's. AC 5's and 10's would compare more favourably with the PPC and large laser.

**Comment by binaryspica** [comment]
I am not the part of the project team but the math would be a reason to request that. If it seems good and reasonable enough for them, then maybe they consider that. 

Although LB 10-X is useful already, but increase its cluster pellets seems worthwhile.

Besides, I did math for damage per ton and heat/weight too, but don't you also need to reduce the ammo weight less than 1.0 to AC2s? If you have multiple same guns, its ammo efficiency is better than simple 1.0 ton per a gun.

For example, I think the game lasts no more than 10 turns so when I check the weight of the ammo I consider its ton(and critical, for an ammo rack is 1 ton and requires one critical) as 10/(numbers of shots in a ton). Then, An AC10(10 shots) will results 1, means you need 1 ton of ammo per an AC10. Meanwhile, AC5(20 shots) will results 0.5, means I just consider +0.5 ton for its total weight. It is not helpful if you just want only one AC5(because only machine gun ammos are able to take half ton on mechs, as we know already), but it would help if you want that many of. Else you may try Ultra variant as well.

CASE/CASEII can be ignored, for you end up with attach either of them if you want to add an explosive slot(unless your era is unaware of these designs).

And, how you think about AC2s and AC5s' longer range? Although they are ridiculously weak, but they do aims farther so at least some degree of premium is required. How do you consider this? Just compare them with energy/missiles as you said is an option, though.

**Comment by Gribbly1** [comment]
I also tried basing it on ten shots per weapon, although 0.2t of ammo per AC 2 didn't seem conservative enough. One tonne per weapon is a 'worst case'. Changing the minimum ammo per weapon to 0.5t is also reasonable and doesn't make a lot of difference for these weapons.

If you take a look at the last column there is a comparison based on an even weight of range and damage.

**Comment by neoancient** [comment]
We do not have the developer resources to take on implementation and maintenance of custom weapon modification requests. This has always been the nature of autocannons, and part of the character of the BT universe is that equipment of varying degrees of technical sophistication exist side-by-side.

**Comment by Gribbly1** [comment]
I understand dev resources are a factor. Thanks for taking a look at this.

I noticed that there are some custom options to improve autocannons, including the base damage, so there is already recognition there is an issue. 
The character of technology in the BT universe has little to do with weapon stats in the game, which often seem largely arbitrary.

**Comment by NickAragua** [comment]
The dev resources (and desire) are definitely the limiting factor. However, it's an open-source project and anyone can contribute code, so if someone were to submit a pull request implementing these changes, we would take a look at it.

**Comment by Gribbly1** [comment]
I've never done any coding, but I might try editing the source code for personal use. Do I need a Git client for that?

**Comment by NickAragua** [comment]
You'll need one to pull down the source code, yes, along with a java development environment or compiler. There are instructions on the wiki here how to build the project.

**Comment by binaryspica** [comment]
By the way, is it possible that it is not approved because it may cause the maintenance problem even if we make some unofficial stuffs? It seems that the wontfix label means it.
