### ISSUE TITLE
git repo history all out of synch with forks

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#15]
At first I thought it was just my fork but after investigating it seems to be affecting every fork. If I compare MM master to another fork I get the following

MegaMek:master and Akjosch:master are entirely different commit histories.

**Comment by arlith** [comment]
We had an issue where many of the old commits that were made in SVN for SF had invalid email addresses when they got imported into git.  This meant that the contributors and commit history in GitHub wasn't parsing correctly.  We had to rewrite the history in order to get GitHub to recognize the authors for these commits.  Because the history was rewritten, the SHA-1 hashes for those commits changed, which will cause your fork to think that it has diverged.  You can use rebase to fix this, or you can re-clone the repository (at least, that's what I did, I'm not sure how that works with forks).

**Comment by pheonixstorm** [comment]
Thanks arlith.

**Comment by pheonixstorm** [comment]
As an afterthought, if you think this might happen again adding a fix to the wiki might be in order. Since I don't have any recent changes (and re-cloning has removed me from the fork list) I have to redo the fork. Not an issue, but may become one for the other older forks especially if this ticket get buried or closed.

**Comment by arlith** [comment]
It shouldn't happen again.  We've fixed the emails, and rewriting history is not a good idea (for these reasons).

**Comment by Akjosch** [comment]
Yeah, took me a better part of the day to `git rebase` my more important repos. Mostly due to conflicts in docs/history.txt, strangely enough. Please, *please* don't do it again.

**Comment by beerockxs** [comment]
It won't happen again, it was a one time thing to credit all the old commits to the correct github user accounts.

Am 22. Februar 2016 15:28:48 MEZ, schrieb Akjosch <notifications@github.com>:
>Yeah, took me a better part of the day to `git rebase` my more
>important repos. Mostly due to conflicts in docs/history.txt, strangely
>enough. Please, *please* don't do it again.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/MegaMek/megamek/issues/15#issuecomment-187203535

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
