### ISSUE TITLE
MGs, Flamers firing at LOS Range

### ISSUE THREAD

**Issue by ObviousTech** [MegaMek/megamek#152]
MGs and Flamers do not meet the minimum required range for direct-fire ballistic or direct-fire energy weapons, so they should not be able to fire at LOS range (TacOps p85).

MGs and Flamers are not flagged as DIRECT_FIRE, so they can fire at LOS Range in MegaMek (but shouldn't be able to according to TacOps LOS Range rules).

**Comment by arlith** [comment]
Looks like Flamers and MGs don't have F_DIRECT fire because of TW pg 113:

>**DE/DB: Direct-Fire Energy or Ballistic Weapon.** These
weapon types (except flamers and machine guns) can
use a targeting computer when making attacks (see
Targeting Computer, p. 143).

Looks like the flag was left out to make it so flamers and MGs don't work with TCs.  I'll have to figure out the best way to handle this.

I feel like it's best to give them the flags and then update the code for targeting computers.

**Comment by arlith** [comment]
I decided against adding the F_DIRECT_FIRE flag to these weapons.  I felt it was too ingrained in the code that F_DIRECT_FIRE implied that a weapon could use targeting computers; there were just too many places in the code that I didn't want to change.

So, I added some explicit checks in `Compute.getRangeMods` that looks for any `MGWeapon`, or anything with the `F_AMS` flag, or anything with the `F_FLAMER` flag.

**Comment by mkerensky** [comment]
When this was addressed, I think some BA-specific weapon types may have been missed. In 0.41.24, I'm getting shot by the bot with a Longinus (Magnetic) (WOB) squad at ranges far beyond what should be possible. 
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/527940/autosave.sav.gz)
Try using the attached save as 337th.  The offending battle armor squad is near hex 2437, and logs from some prior turns will show it firing both installed MGs across the map.
