### ISSUE TITLE
Mowang Courier has wrong size cargo bay

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/megamek#1537]
While talking about small craft the Mowang Courier is listed in MegaMek as having a 26.5 ton cargo bay.  3057r however records it as a 5 ton bay.  

Is this an error or is there an explanation.  

![SmallCraft](https://user-images.githubusercontent.com/20606833/68427551-57dc9a80-0178-11ea-903d-ba9e829a0845.jpg)

See https://bg.battletech.com/forums/index.php?topic=67463.msg1560612#new for discussion

**Comment by HammerGS** [comment]
The simple answer is that it very underweight when built.
![image](https://user-images.githubusercontent.com/13752452/68429617-aa638a00-016b-11ea-81fb-ca4f087e5e94.png)

So rather than waste 20.5 tons we tossed that into Cargo space. We find their are lots of small craft, support vee's, and other no combat units with errors when we run them through MegaMekLab their are errors of some type.  I suspect this is a result of them being built by hand or excel spreadsheet.
