### ISSUE TITLE
When resetting out of a save game, you lose map size options.

### ISSUE THREAD

**Issue by VictorMorson** [MegaMek/megamek#157]
When you use the /reset command to leave a loaded saved game, the map selection screen will lose several options including the ability to pick maps of different sizes, until the game is reset entirely.

Steps to repro:
1) Create a save game.
2) Restart Megamek and load the save game.
3) Once in the match, type /reset
4) Attempt pick a different map
5) Notice a lack of size selections

**Comment by arlith** [comment]
When I try to reproduce I can see that the list of available map sizes isn't populated correctly, but that's the only issue I notice.  It seemed like you had other problems in mind, is that true, or is it just the list of available map sizes?

**Comment by VictorMorson** [comment]
It is in fact the list of maps sizes; it's mostly a problem when you are playing custom maps, since there's no way to choose any map that isn't the default size; you have to reload the game to fire up, say, a 32x32 map.

**Comment by arlith** [comment]
The issue here is that the `Client` never gets updated with the list of available maps.  `Client` stores these in the `availableSizes` set while other map settings are stored in `Client.mapSettings`.  The only time the server was updating the available sizes was when the client connects or a saved game is loaded (that is, `Server.sendCurrentInfo` is called).  It was not getting called with the /reset command.

However, `Server.prepareForPhase` sends map settings to the client when preparing for the lounge phase.  When it sends the map settings, it should also update the board sizes, so I added code there to also send the available map sizes, which in turn fixes the problem.
