### ISSUE TITLE
'Mech can grapple another 'mech 2 levels higher on a elevator hex 0.47.2

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#1570]
On one of the coliseum maps, I saw I was able to grapple with a 'mech in an adjacent hex in front of mine even though it was on top of a level 2 elevator.  My 'mech was on level 0.

**Comment by neoancient** [comment]
I tried this by moving a unit onto a level 2 elevator while it was raised, and couldn't make any physical attacks. When the elevator came back down I verified that I could make physical attacks, then when it went back up with the target already on it I couldn't make any attacks.

[elevator_test.sav.gz](https://github.com/MegaMek/megamek/files/4060653/elevator_test.sav.gz)
Player name is "test"

Closing due to no problem found.
