### ISSUE TITLE
Mechs switching hot-loading LRMs on/off during battle

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#160]
During battle you can go into your mech's systems tab, select your LRM ammo and in the "mode box" I guess you could call it, you can switch your ammo to hot-load on/off like with vehicles.

**Comment by BLOODWOLF333** [comment]
Tested and this is present in the MM release with 0.3.27.  Really doesn't bother me though I like the bug but, I know TacOps says different.

**Comment by BLOODWOLF333** [comment]
![ingame](https://cloud.githubusercontent.com/assets/16950832/15002891/c847e528-116b-11e6-8310-15bdb924061b.png)

[HL.sav.gz](https://github.com/MegaMek/megamek/files/248039/HL.sav.gz)

Player name: BLOODWOLF

**Comment by arlith** [comment]
The "Hot Loading" mode is added in the weapon files.  Turns out it's not even removed if the hot loading option isn't on.  I added the ability to remove specific modes, and the mode is now removed for 'mechs during the exchange phase (which is a phase that happens just after the lounge, before a game begins).

I also noticed that if a vehicle hot loads ammo, the mode isn't properly set, so the "empty" mode is selected.  To remove hotloading, the user has to select hotloading, then select the normal mode.  I fixed this by ensuring the "HotLoad" mode is selected when ammo is hotloaded in the lounge.
