### ISSUE TITLE
Foot platoons can move infinite hexes while in woods per turn

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#175]
As long as my foot platoon stays in woods hexes I can move him as many hexes as possible in one turn.

![ingame](https://cloud.githubusercontent.com/assets/16950832/14945685/cf7ac1da-0fdb-11e6-8014-90223d05259c.png)

[FootPlatoonBug.sav.gz](https://github.com/MegaMek/megamek/files/244494/FootPlatoonBug.sav.gz)

**Comment by pheonixstorm** [comment]
Using the latest MM release??

**Comment by BLOODWOLF333** [comment]
Yes this is the 0.3.27 package.

**Comment by scJazz2** [comment]
From convo on MC Forums...
Units ignore the movement penalty from trees if there is pavement as the base layer, the infantry has to be some weird interaction with that. Infantry platoons can also always move at least one hex.

So, I think, what is happening here, is that the foot infantry have an MP of 1, but they get the bonus MP needed to enter a woods hex. But since woods hexes on pavement only cost the underlying amount, in this case, 1, the infantry only ever expends their bonus MP to enter the wooded hexes, causing the cost of entering a woods hex to be effectively 'free' but also never expending their walk MP. Since you have not expended your walk MP, MM thinks you should still be able to move.

**Comment by BLOODWOLF333** [comment]
Player name: Madras as seen in the screenshot.

**Comment by pheonixstorm** [comment]
Should have a fix for this in my next PR. Maybe this weekend.

**Comment by pheonixstorm** [comment]
@arlith 
Still digging around on this one. It seems to have been around for awhile though. I went as far back as 0.35.34 and it was present. I'm shocked this hasn't been reported sooner.

**Comment by pheonixstorm** [comment]
This is being a real bugger to fix properly. Just adding not this or that terrain does nothing but adding not this and not this fixes the issue but makes movement from clear terrain to wooded road or pavement cost 2 mp rather than 1. Will continue to bash my head against it until something breaks.

**Comment by pheonixstorm** [comment]
Fixed.

**Comment by BLOODWOLF333** [comment]
Way to go Phoenix \m/.

**Comment by arlith** [comment]
Are you going to make a PR?

**Comment by pheonixstorm** [comment]
Yes, I had three other bugs to fix before posting.

**Comment by arlith** [comment]
Fixed with PR #183.

**Comment by VampireSeraphin** [comment]
This issue recurred for me today on Jakes-Wide Blue River1, a 35x35 map.

[InfiniteInfantry2.sav.gz](https://github.com/MegaMek/megamek/files/590102/InfiniteInfantry2.sav.gz)
[InfiniteInfantryWalk.sav.gz](https://github.com/MegaMek/megamek/files/590101/InfiniteInfantryWalk.sav.gz)

This maps is using a tile type "Woods:0" that may be illegal & contributing to this bug.

**Comment by BLOODWOLF333** [comment]
This map I realize is invalid to begin with. Pavement and woods are both base terrain and illegal to have two base terrain types in the same hex.
