### ISSUE TITLE
Real Blind Drop: unit customization messages reveal how many units a player has

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#176]
Currently, when you customize a Unit in the Lobby a msg is generated and shown to both players that a Customization has occurred. It also shows the Unit Number.

This means in a DB game you can get a good (perfect) count of the number of units in the other players force.

Please, either remove that string entirely in DB games or change it to "Player N has configured a unit"

**Comment by arlith** [comment]
This should be for real blind drop, not for DB.  There are arguments both way (aka, you may want to know what your opponent is deploying, to "keep him honest", vs not wanting to have any information revealed at all).  This is handled via the blind drop and real blind drop options, not the double blind option.

**Comment by arlith** [comment]
To be clear, this is related to the `"Unit <Unit> <Player> has been customized."` messages that the server sends in the lobby when a player customizes on of their units.  We have two options that should affect this: Blind Drop and Real Blind Drop.  Blind Drop is designed to provide lax obfuscation: unit details are obfuscated, but BV and # of units isn't.  Real Blind Drop attempts to obfuscate all information.

Previously, the customization message for Blind Drop and Real Blind drop was of the form: `"Unit <UUID> <Entity_ID> (<Player>) has been customized"`.  This could easily reveal how many units a player has, so isn't appropriate for Real Blind Drop.  I changed it so that if Real Blind Drop is on, the message is now just: `"A Unit (<Player>) has been customized."`.
