### ISSUE TITLE
PSR for jumping into ultra heavy woods

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#179]
Currently you can jump into ultra heavy woods and incur no PSR as with heavy woods.
![ingame1](https://cloud.githubusercontent.com/assets/16950832/15061289/262c3002-12f9-11e6-84be-a2cd9d9d3dbf.png)

[UHW.sav.gz](https://github.com/MegaMek/megamek/files/251402/UHW.sav.gz)

Player name: BLOODWOLF

**Comment by arlith** [comment]
I would guess that the reason this wasn't added in the past was because 'mechs cannot enter ultra heavy woods.  The only reason you can enter those hexes in your example is because they are on pavement, so it's presumed you're moving through the pavement.  The unofficial rule will require the PSR for heavy woods in this case, so I did add ultra heavy woods to the PSR, however making that role will probably be very rare.  Because of the rarity, I didn't update the option name/tooltip (otherwise, I imagine seeing ultra woods may confuse some people).
