### ISSUE TITLE
41.17 : Friendly ECM field dissapears after switching another friendly unit to ECCM mode

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#182]
After switching one of the vultures to ECCM mode, the next turn, most of the ECM field from the other vulture dissapeared. See attached screenshot and save.

[#battletech.zip](https://github.com/MegaMek/megamek/files/254900/battletech.zip)

**Comment by pheonixstorm** [comment]
It would help if the screen shot was in your post rather than zipped up. Does the ECM still do its job at all? A graphics bug isn't as big a deal as an actual ecm that no longer functions under a teams eccm.

**Comment by arlith** [comment]
When was this saved game originally created?  I see that your logfile mentions MHQ 0.3.27, which should be MM 41.17, but when I load the saved game, it looks like the hash code for the Coords isn't serialized in the saved game so is set to 0 for all Coords.  This causes issues, and the only saw I could see this happening is if the saved game was created with a version prior to the Coords.hashcode change (MM 41.15).  I could try loading the saved game with 41.15 to see if I can reproduce the issue, but I'm hesitant to do that without further information.

**Comment by Question2** [comment]
Yea it was 41.17, I just loaded MM stand alone and was able to replicate it just fine.

[megameklog.txt](https://github.com/MegaMek/megamek/files/284134/megameklog.txt)

[#battletech.sav.gz](https://github.com/MegaMek/megamek/files/284175/battletech.sav.gz)

![megamek](https://cloud.githubusercontent.com/assets/1191378/15573724/375d095c-238c-11e6-8138-1632663d6d11.jpg)

**Comment by arlith** [comment]
It's not that the issue cannot be replicated; the problem is that the saved game itself has problems in it, and I can't tell what the source of the problem is.  We use hashed datastructures to store/retrieve coords.  All versions past 41.15 have a state variable in `Coords` that store the hashcode for each `Coords` instantiation.  All of the `Coords` in your saved game haven't stored a hashcode, so every `Coords` has the same hashcode, which will break a ton of things.  Ultimately, that's the issue here.

**Comment by pheonixstorm** [comment]
Do a clean install of MM and see if you can still replicate. It could be as simple as a corrupt file in your HQ install.

**Comment by Question2** [comment]
Hmm, in that case, when you replicate the ECCM glitch and save the game, does your save game have the issue with Coords thing as well?

Quick save game that I just did with 2 Ravens.

[#battletech.sav.gz](https://github.com/MegaMek/megamek/files/285059/battletech.sav.gz)

**Comment by Question2** [comment]
This is on a fresh install of 41.17.

[#battletech.sav.gz](https://github.com/MegaMek/megamek/files/285106/battletech.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/285107/megameklog.txt)

**Comment by Akjosch** [comment]
For the last save:

1. I added a converter to `loadGame()` so that coordinates get created via the constructor, not the `sun.misc.Unsafe` way XStream typically uses
2. I loaded the game and saved it right aways.
3. The hashes got generated (as expected) *and* saved.

Comparison to the original first occurence of  `<coords>`:

            <coords>
              <x>0</x>
              <y>0</y>
            </coords>

vs. what was saved with MegaMek:

            <coords>
              <x>0</x>
              <y>0</y>
              <hash>895840469</hash>
            </coords>

The latter format is *also* what an unpatched version of MegaMek 0.41.17 generates. I just checked it by creating a new game (from a scenario to save time) and saving it right away.

I'll add the converter patch to MegaMek to help people who try to load older saves with newer games (though that was never supported for MegaMek ...), but I can't see how it would even be possible to generate those two saves from a regular 0.41.17.

**Comment by Question2** [comment]
Weird, because https://github.com/MegaMek/megamek/issues/182#issuecomment-221964106 was done with a fresh install of 41.17...

**Comment by Akjosch** [comment]
Strange. Anyway, try doing that in the next daily build from http://mm.akjosch.de/ - see if ECM fields works for you then.

**Comment by arlith** [comment]
I'm going to look into this bug, but my hunch is that the `Coords` issue is tangential to the ECM issue.  I'm fairly confident the `Coords` issue is related to saving/loading games; if it wasn't there would be also, far more noticeable, issues (for instance, the right-click context menu "Select" and "View" options won't work, which is what I immediately noticed).

**Comment by arlith** [comment]
Alright, what happens here is that, `ECMInfo` makes some assumptions, and hence can really only track allied ECM vs enemy ECCM or allied ECCM vs enemy ECM, but not both.  The code in `BoardView1` was basically trying to use one `ECMInfo` to track both allied ECM and ECCM, and what ended up happening is that they would cancel each other out.  Of course, this was only for the code displaying the effects of ECM; code for applying the effects of ECM/ECCM occurs in a slightly different place (and is unit tested).

**Comment by Question2** [comment]
@Akjosch just in case i tried testing with the megamek version at the link you gave me. Heres a savegame using 41.19-git 

[megameklog.txt](https://github.com/MegaMek/megamek/files/294086/megameklog.txt)
 : 
[a.sav.gz](https://github.com/MegaMek/megamek/files/294085/a.sav.gz)
