### ISSUE TITLE
RFE: Ability to manually set maximum number of deployment hexes from team home edge

### ISSUE THREAD

**Issue by sldfgunslinger2766** [MegaMek/megamek#1852]
Please consider adding an enhancement to Board.java that will allow for the designation of the depth of a teams deployment zone from their home edge. The current edge based deployments are hard coded at 3 hexes and a large amount of the Tracks published by Catalyst have deployment zones that exceed 3 hexes. Include a 'Deployment Zone Depth' integer field in the Player Set Up\Change Start tabs pop up menu. 

https://github.com/MegaMek/megamek/blob/a392955443c0ba48a0b2e8349eae569ffa472789/megamek/src/megamek/common/Board.java#L715 (edited) 
megamek/src/megamek/common/Board.java:715

Thank you!

**Comment by SimonLandmine** [comment]
I was going to request an option for "half-map" (if N/S/E/W deployment) or "quarter-map" (if NW/NE/SW/SE deployment), but this RFE would be more flexible.
I would suggest that deployment depths be assignable per player (in the same manner as deployment direction currently is), so that some players could be deep-deployed while others are edge-deployed, depending on the scenario.

**Comment by sldfgunslinger2766** [comment]
Bump.

**Comment by SimonLandmine** [comment]
Would probably be worth having the value default to 3, so that if it's not specifically set, it remains at the standard value. Would also make sense for deployment depth value to be set per player, rather than for entire game.

**Comment by sldfgunslinger2766** [comment]
> Would probably be worth having the value default to 3, so that if it's not specifically set, it remains at the standard value. Would also make sense for deployment depth value to be set per player, rather than for entire game.

Agreed. Upon reflection, that would prevent any compatibility issues with StratCon/AtB...
