### ISSUE TITLE
47.5 Map Editor - UI Improvement - suggest 'grey out' Exits value when checkbox unchecked.

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#1857]
v0.47.5

With the new UI, the 'Exits' value is permanently shown in the value box with the up/down buttons, even when the 'Exits' checkbox isn't active. This might be confusing to users. Is there a way to set the text colour in that box to a shade of grey when the 'Exits' checkbox is unchecked, and to prevent the value being changed?

**Comment by SJuliez** [comment]
When Exits is unchecked and you click the up/down or enter a value, Exits is checked automatically. It's been a while since I programmed this but I think I tested both and considered this superior because clicking that checkbox to get exits to work always felt a nuisance. Or my mouse aim is just bad. I could grey out the text a little to make it more obvious. On the other hand, I've been using the Map Editor myself quite a bit, for testing and rendering maps to print and never had any problems with it. Sometimes a map ends up having something like pavement:1:34 but that usually doesnt hurt...

**Comment by SimonLandmine** [comment]
Having the 'Exits' checkbox auto-check when the value is changed (by scrollbox or direct input is certainly a good thing, no complaint about that.
My concern was more that it might confuse new users when the 'Exits' value is clearly displayed when they've not set any exits.
(The checkbox+picker combo makes it more obvious, for me, what direction the exits are in when placing roads, bridges, and buildings - especially as bridges don't display on the preview hex. I find the scrollbox is the better interface when selecting fluff by scrolling through it, though.)
