### ISSUE TITLE
AMS mounted on ASFs do not fire on the ground map

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#189]
ASFs mounted on ASFs never fire to intercept incoming missiles, even on the ground map. See the attached save.

[#battletech.zip](https://github.com/MegaMek/megamek/files/264058/battletech.zip)

**Comment by HammerGS** [comment]
Confirm this isn't working at all. Nothing in the logs.

Smaller Save on Ground Map attached.
[ASF.sav.gz](https://github.com/MegaMek/megamek/files/382346/ASF.sav.gz)

For reference AMS rules are on TW pg 129-130.

**Comment by arlith** [comment]
Looks like the AMS was actually firing, generating heat and consuming ammo, but not actually doing anything.  I also noticed that the report was odd: the hit/miss status of the roll wasn't being reported.

What was happening was that `WeaponHandler.calcHits` was being called, which triggers the AMS computation, but then for airborne units, it would remove the reports added from that, and do something else.  I adjusted `MissileWeaponHandler.handle` so that it only calls calcHits for non-airborne units.  Then, it properly reports the hit status, and also runs the AMS computation.  Now, it will also reduce the AV of the missile hit, according to TW pg 130.
