### ISSUE TITLE
Unit prone in basement not buried during building collapse

### ISSUE THREAD

**Issue by ZraveX** [MegaMek/megamek#195]
I had this issue come up during a match, and was able to reproduce it a few times against bots. I was able to determine that the problem is not in the building collapse step, but rather in the basement collapse event. I tested it 7 times, and the unit was buried properly when the basement was double or if the building had more than 1 level. However, 4 times when there was a single basement on a 1 level building, the unit did not actually fall in the basement during basement collapse. Version info on last picture.

![1](https://cloud.githubusercontent.com/assets/19374990/15275273/0157c090-1a95-11e6-8756-8d2c52ffe962.png)
![2](https://cloud.githubusercontent.com/assets/19374990/15275279/0e0e46c4-1a95-11e6-9d74-a4d9555714e7.png)

As you can see at this point there is already a problem, the WHM-6D prone in the building does not have the -1 indicator on the upper left of the hex indicating it is below the surface. Every time that indicator was present, the unit was buried properly during collapse.

![3](https://cloud.githubusercontent.com/assets/19374990/15275280/0f7809fa-1a95-11e6-844e-73affe39b792.png)
![4](https://cloud.githubusercontent.com/assets/19374990/15275281/10b7e16e-1a95-11e6-86dd-6e69ec8f721a.png)

And here is the unit surviving the collapse.

**Comment by HammerGS** [comment]
We really are going to need a save game and the log to recreate this.

**Comment by barukkhazad** [comment]
Hello... I attached three files. The 1.sav.gz savegame shows the unit immediately after it triggered the basement collapse. The 2.sav.gz shows the movement phase report (the 70 ton unit took the expected 14 damage from falling over and from falling down 1 elevation but the unit remained at elevation 0). In th example we just started walking meks into the buildings until it happened. The MegaMek version is 0.41.16-MW20160229-b867f65 0.

[2.sav.gz](https://github.com/MegaMek/megamek/files/265144/2.sav.gz)
[1.sav.gz](https://github.com/MegaMek/megamek/files/265145/1.sav.gz)
[game_2016-05-15_13-35-55.txt](https://github.com/MegaMek/megamek/files/265152/game_2016-05-15_13-35-55.txt)

**Comment by BLOODWOLF333** [comment]
TW p179 " A collapsed basement will not automatically collapse the building hex but the building hex will take damage equal to the tonnage of the falling units divided by 10 (round fractions up) double the damage for a two-level basement—"

TW p176 "Basements and Collapse: When a building hex collapses, the rules assume that the resulting rubble will fill in any basement the building might have had. A building with a basement becomes a rubble hex equal to the level of the terrain underneath the building, not a sublevel rubble hex. If the collapse occurs as a unit moves into the building hex at Level 0 for the first time in the scenario, the controlling player need not make a basement roll (see Basements, p. 179). If a unit occupies a basement when a building hex collapses, that unit is destroyed. "

**Comment by arlith** [comment]
Ok, the source of this problem is commit 8fb90433f.  This was to fix a bug tracked on SF: https://sourceforge.net/p/megamek/bugs/4128/.  I vaguely recall making this commit, and I'm pretty sure I made it based on a hunch that I didn't fully test.  I can somewhat confirm this by going back and loading those saved games; there's no situation in those saved games that would be affected by this change.

Essentially the problem is with this line in `Server.doEntityFall`:

```java
        if ((entity.relHeight() >= buildingElev)
            && (buildingElev >= 0)) {
            // fallHeight should already reflect this
            newElevation = buildingElev;
            checkCollapse = true;
        }
```

The purpose of this code is to determine if the entity is falling from within the building or from above it.  The issue is that relative height is the Entity's elevation + height, basically representing where the "head" of the unit is.  In this instance, what we care about is where the "feet" of the unit is, which is just `getElevation`.  In the example here, since the building is elevation 1, and the 'mechs relative height is 2, it's assuming the 'mech is falling on top of the building and so uses a fall elevation of 1, which then subtracts the basement depth from yielding a new elevation of 0 (instead of -1).

I've reverted the change in 8fb90433f, and tested that it fixes the problem.
