### ISSUE TITLE
RFE: Princess option - "Advance to contact"

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#1950]
The "Destination Edge" addition is excellent for getting Princess to move across a battlefield, in simulation of a 'breakthrough' or 'convoy' mission (for Princess - a 'defence' or 'ambush' scenario for the player). However, I've noticed that, with "Destination Edge" set, Princess will depart the board (at least in 0.46.1) if the units make to the destination edge (potentially if outnumbered). Units with this setting will effectively 'flee' towards their destination, unless Crippled, in which case they will fall back to the "Retreat Edge".

However, if you want Princess to simulate an "advance to contact" setting in a Double Blind scenario, where Princess' units don't start with LOS to the player's units, then this isn't entirely ideal, and you will occasionally need to do something to get Princess' attention.

My suggestion - add an "Advance to contact" option checkbox to the Princess bot configuration window.

Suggested implementation - When checked, this option would set a flag on a Princess instance. While the flag is set, units will advance at Run (or Walk? but not Sprint - they need to be ready to react on contact) speed away from their starting edge* (or towards a destination edge?), until encountering forces from another Team, at which point the Flag will be cleared, and the standard assigned Princess behaviour for that bot will resume.

* Note - this could encounter an issue with CENTER start, but it might just result in units scattering entertainingly. That would probably require testing, but that could still be a viable outcome.

**EDIT** Currently, if "Destination Edge" is checked, but "Auto Flee Edge" is unchecked, Princess' behaviour is even odder - her units mill about at their destination edge, as if unsure what to do now they've got there, and unwilling to move away from it.

**Comment by SimonLandmine** [comment]
An additional thought about this proposal - it would probably work better as a 'fallback option', so that if enemy are encountered, and then are no longer visible, Princess would then revert to this advancing behaviour.

**Comment by HammerGS** [comment]
Related to https://github.com/MegaMek/megamek/issues/203

**Comment by SimonLandmine** [comment]
Related, but would be an alternative - 'Single Blind' would give Princess 'god's eye view', while 'Advance to Contact' maintains the possibility of flanking, which Single Blind would negate.
'Advance to Contact' simply means that Princess does something if there's no enemy in sight.

**Comment by Thom293** [comment]
I did not know Simon had already done this.  He had already thought of half of this so my "Search Edge" idea below is redundant.  But I will add this addition restated to a "No Persistent Memory Necessary" option for Princess to react to sensor pings.  Its a suggestion for princess to be able to react to sensor pings or having no targets even if she doesnt have a memory.

Idea below:

Simple AI Search/Double Blind behavior

I only know a tiny bit of 1987 Basic Code completely limited to the probably improper use of IF, THEN, and GOTO.  So that is how I will write this.

Requirements:
Make sensor pings persistant for 3 turns.  Perhpas shorter on small maps and longer on very big maps.
Set some reasonable (opposite?  furthest?  Custom?) map edge for a new "Search Edge" parameter at game start.

Move phase:

If no destination edge
If no retreat edge
If no strategic target
If no defensive Target
If no visible enemy


Then search for Sensor Pings.
If sensor ping, approach Ping.

If no Ping, then:

If entity has X move points, then:  (might want a qualifier here for the "no ping" case - you dont want assaults wandering around randomly so target it at higher move point units?  - but could remove this too).

If no sensor ping, move to Search Edge.

repeat.

I think This would remove her need for a memory.

Eventually, on an especially huge map or if someone is intentionally trying to hide from her, she might end up wandering around at the search edge if she didnt find someone before then, but that would be an extremely rare case I think?  Could probably come up with a way to trick her into doing something else once she reaches the search edge without a memory too).

**Comment by SimonLandmine** [comment]
In the suggested context, 'Search Edge' could be the same as 'away from starting position' logic used for 'Advance to Contact'.

An alternative, and possibly simpler option would be not use the 'ping persistence'. Instead, add some code to Princess so that the AI reacts to sensor pings, with behaviour possibly determined by the AI configuration - braver units (or scouts?) advance towards a ping for more information, more cowardly units stay away from them. This could be a halfway house, and the code for Princess responses to pings would still be useful for the 'persistent ping' suggestion. However, that does seem to be a considerable addition to the basic 'Advance to Contact' code suggestion.

**Comment by SimonLandmine** [comment]
As @Thom293 has mentioned in the Discord, there is apparently code for this functionality already in the program, but commented out (or turned off in some other way). This might potentially make it a low-hanging fruit, if that code could be completed.

**Comment by Thom293** [comment]
I'm not at home right now but from memory it's coded as one of her move options in one file (along with retreat, flee to cardinal edge, etc) and appears "usable" but in another file (Perhaps one of the Path Rankers?) it's grayed out as never used.

**Comment by repligator** [comment]
Completed, closing.
