### ISSUE TITLE
Vibrabomb Minefield deals damage with the wrong timing.

### ISSUE THREAD

**Issue by Logajam** [MegaMek/megamek#1978]
### Environment
Testing on MM46.1

### Description
Place a mech in a hex with a Vibrabomb, or use Thunder Vibrabombs to deploy a minefield in the mechs hex.  Set the vibrabomb to have a detection threshold of 20, so it will activate.

Move the mech out of the vibrabomb minefield.  The mech will take damage.

This is incorrect.

There are several places in tactical operations where it is stated that a unit leaving a hex that is mined does not set off the mines.  For example on pg 373

In addition the example for Vibrabomb mine usage on pg 209 says that the check to see if the vibramine activates happens when a mech enters a hex.

Since in my example above the mech that is activating the mines is the one that just entered another hex entirely, it can not be in the hex it just left to be hit by the mines.

**Comment by HammerGS** [comment]
I can confirm a recent rules team ruling that mines only detonate when a unit enters the hex.

**Comment by NickAragua** [comment]
The thing about vibrabombs is that the mech detonating them doesn't have to step on the hex containing the vibrabombs. If a mech is heavier than the vibrobomb setting by at least 10 tons, it will set them off from 1 hex away per 10 tons over. So, a 50-ton mech stepping out of a 40-ton-rated vibrabomb hex *should* detonate the vibrabombs.

That being said, the unit shouldn't be taking damage in this scenario, so that's what the fix will be.
