### ISSUE TITLE
Advanced Search returning incorrectly filtered results.

### ISSUE THREAD

**Issue by Logajam** [MegaMek/megamek#2078]
### Environment
MM 47.7

### Description
Do an Advanced search for units with 4 Large lasers.
Filter to Aerospace fighters.
Several returns have only 3 Large lasers.
Hellcat HCT-213
Ironsides IRN-SD2
Etc.

Fraid I'm sending you on a wild goose chase, Have no clue whats happening.

**Comment by arlith** [comment]
The problem here is that ASF have weapon groups for capital fighters.  These weapon groups get added into the equipment list, so that they can be selected as weapons to fire.  However, `MechSummary.setEquipment` doesn't know about weapon groups so those get treated as regular equipment.  For instance, the Hellcat has two Large Laser weapon groups added, as well as two medium laser weapon groups.  These get counted as pieces of equipment when they shouldn't.
