### ISSUE TITLE
41.17 : Incorrect color when reversing a mech

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#208]
For some reason the color changes when backing up. By default, backing up always use the yellow color (normally used for running), but when using maneveuring ace to sidestep, the color seems to change to blue.

I'm not sure if backing up should use the yellow color either since its still at walking speed, which should be blue...either way, the color change due to maneveuring ace probably shouldnt be happening.

![megamek](https://cloud.githubusercontent.com/assets/1191378/15393092/b5e2aae4-1e0e-11e6-8559-55db62aa0ece.jpg)
[#battletech.zip](https://github.com/MegaMek/megamek/files/272510/battletech.zip)

**Comment by arlith** [comment]
The problem here are the lateral shifts.  The code to apply the "MoveBackColor" (which is an advanced option; you can change it if you'd prefer a difference color) was only checking for the `BACKWARDS` MoveStepType.  It also need to check for `LATERAL_LEFT_BACKWARDS' and `LATERAL_RIGHT_BACKWARDS`.  I added these to the check.
