### ISSUE TITLE
VTOLs incorrectly able to lateral shift / sideslip   (rules issue)

### ISSUE THREAD

**Issue by ZraveX** [MegaMek/megamek#210]
In Megamek (version 0.41.16-MW20160229-b867f65) VTOLs are permitted to sideslip during cruising speed movement, but any sideslips introduced are still accepted even if later in the movement you use flanking MP. No PSR is required.

![sideslip](https://cloud.githubusercontent.com/assets/19374990/15405836/b0e97af0-1dd1-11e6-998e-f553edcec297.png)

Relevant rules:

Total Warfare describes the lateral shift maneuver on page 50. The paragraph heading states "LATERAL SHIFT (FOUR-LEGGED ’MECHS ONLY)".

A Time of War has the pilot skill Maneuvering Ace, which states:

"Bipedal ’Mech units and VTOL units at Cruising
speed whose pilots possess this ability can perform the lateral
shift maneuver normally available only to four-legged ’Mechs
(see p. 50, TW)"

This confirms that Lateral Shift is available only to four-legged 'Mechs, but that the maneuvering ace skill allows VTOLs to perform it. However, even then they are limited to cruising speed. VTOLs currently have a better version of this ability without needing this pilot skill.

In Tactical Operations, page 25, an advanced maneuver is introduced, called Sideslip, allowed for both VTOLs and Hover Vehicles. However, it works differently from implemented in Megamek. Relevant text: "any time a vehicle makes a sideslip, the controlling player must make a Driving Skill Roll with a –1 modifier. If the roll fails, the vehicle slips too far, moving an extra hex in the direction of the sideslip."

The only mention of this maneuver in Strategic Operations is in the design quirks section, where some VTOLs are specifically forbidden from attempting the sideslip described in Tactical Operations.

This is all I've been able to find.

**Comment by BLOODWOLF333** [comment]
This does apply in 0.41.17 as well
![ingame](https://cloud.githubusercontent.com/assets/16950832/15415824/21e8c83a-1e0b-11e6-915a-b5831d95d6ac.png)

[#210.sav.gz](https://github.com/MegaMek/megamek/files/273800/210.sav.gz)
Player name: BLOODWOLF

**Comment by arlith** [comment]
There's a `MovePath.canShift` method that determines whether a unit should be able to lateral shift.  This looked like it was intended to be correct, however, there were some misplaced parens so instead of being `(maneuveringAce && (BipedMech || (VTOL && notFlanking))` it was `(maneuveringAce && BipedMech) || (VTOL && notFlanking)`.  I adjusted the parens to be correct.

Additionally, while a `MovePath` wouldn't add a shift after flanking was reached, a `MovePath` that contained a shift prior to flanking was still considered legal (which doesn't follow the rules).  I added a check to mark illegal any paths that go into flanking movement and contain shifts.
