### ISSUE TITLE
Smoke missile smoke dissipates one turn earlier than it should

### ISSUE THREAD

**Issue by Cryosleeper** [MegaMek/megamek#2102]
According to https://bg.battletech.com/forums/index.php?topic=69608.0 a smoke missile cloud shot on Turn 1 should clear on Turn 4. But as of 0.46.1 it goes away on Turn 3.

From what I see in the code, it's because the smoke duration counter is initially set to 3 in a fire phase, but then affected by the end phase of the same turn. Therefore, changing it to 4 should help.

**Comment by gsparks3** [comment]
Can confirm that this bug is still present as of 0.49.8. 

The message for weapon-delivered smoke dissipating due to the timer expiring also indicates that the smoke "drifts to hex [xxxx] and dissipates to light smoke" in the round report, when in fact it does not drift at all, and dissipates entirely rather than becoming light smoke.

Also, if the "TacOps Starting Fires" game option is not active, weapon-delivered smoke _never_ dissipates.
