### ISSUE TITLE
41.17 : Saving and reloading in the "designate artillery targets" phase at the start of the game breaks the save

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#211]
In the designate artillery targets phase at the start of the game, i saved, closed MM, and reloaded the save. I was able to designate targets as normal, but when trying to proceed to the deployment phase, MM did nothing. I was able to save the game again, but reloading the save game just gave me a "waiting on the server" blank screen.

Error log has this : 

`GameReports.get(int) [ERROR] ERROR: GameReports.get() was asked for reports of a round [1] which it does not posses.
megamek.common.GameReports.get(GameReports.java:65)
megamek.common.Game.getReports(Game.java:2702)
megamek.client.Client.handlePacket(Client.java:1357)
megamek.client.Client$1$2.run(Client.java:219)
java.awt.event.InvocationEvent.dispatch(Unknown Source)
java.awt.EventQueue.dispatchEventImpl(Unknown Source)
java.awt.EventQueue.access$500(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.awt.EventQueue$3.run(Unknown Source)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
java.awt.EventQueue.dispatchEvent(Unknown Source)
java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.pumpEvents(Unknown Source)
java.awt.EventDispatchThread.run(Unknown Source)`

[#battletech.zip](https://github.com/MegaMek/megamek/files/274536/battletech.zip)

**Comment by arlith** [comment]
What's happening is when the `Client` receives the COMMAND_SENDING_REPORTS_ALL packet from the server, it tries to update it's `roundReport` cache, however, since the game was saved before the server ever added any reports to its `Game` reference, there are no reports.

I see two solutions.  One would be to update the `Client` code so it doesn't try to cache round/phase reports if none exist.

The second (and the approach I took) was to update `Server.endCurrentPhase()` so that a round report will get added.  I made it so when the LOUNGE, EXCHANGE, STARTING_SCENARIO, and ARTYAUTOHITHEXES phases end, the round report is added. `Game.addReport` uses the current round number to determine what round to add the reports to, and `GameReport` properly handles adding multiple reports for the same round, so it's fine to add multiple reports for "round 0" and adding an empty `Report` list doesn't cause any display issues.  The advantage of this report is that, in the future, if any of these phases *do* have reports, they can be displayed properly.
