### ISSUE TITLE
RFE:  Some weapon types seem to be missing quad turret types

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megamek#2176]
For example, IS LB-X turrets are all missing a quad variant, as are Clan LB-X turrets.
Clan HAG and some Gauss types also seem to be missing quad variants.

Is there an in-game reason for this, or is it an oversight?

If it's an oversight, what are the limitations of sizing and ammo?  I would be willing to work on a PR to add them.

**Comment by NickAragua** [comment]
Feel free, although you would also need to add them to the turret RATs in order for them to actually show up in AtB.

**Comment by mhjacks** [comment]
OK, I've been through the whole filesystem for ge/ and there are north of 100 units to add for both Clans and IS.  I'm up for it, though - my players love big guns and lots of units on the field, so...

I'm inclined to do this in two phases, one to add the units and the second to add them to the RATs.

Is there guidance on how to weight the quad variants vs say the triples for the RATs?  I'm not sure how the RATs are supposed to work, mechanics-wise

**Comment by NickAragua** [comment]
You can start with just the unit definitions. I've got a project in the works to automate turret RAT generation (eta unknown) so it may be a moot point in the future.

The way the RATs work in general is that you basically give it a unit type and a weight, relative to all the other units in the individual RAT file, higher numbers being more likely. When it comes time to generate a unit from the RAT, MegaMek basically assigns each turret a number of slots according to its probability weight, then rolls a number between 1 and the sum of all the weights. Whichever slot it lands on is the turret that gets generated.

There's not really any guidance on relative likelyhoods, other than bigger, nastier turrets should probably be more rare. 

The main limit on what weapons you can put on a structure appears to be CF / 10 tons (not counting ammo, heat sinks, etc). Since you'll never see a structure tougher than 150 CF, that means there's a limit of 15 tons of "heavy" (mech-scale) weapons. Check out page 266 in TacOps. Obviously, this isn't implemented in MegaMek but it's useful as a guideline.
