### ISSUE TITLE
Mech UMUs attacker movement modifier and heat generation

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#22]
Per TacOps, page 295: "Use of UMUs imposes a +3 attacker movement modifier on all attack to-hits made by the UMU-equipped unit, as though the unit were jumping. However, UMUs generate only 1 heat point per turn total, regardless of the number of UMU MPs used."

The attack movement modifier and heat are not being applied at the moment.

**Comment by arlith** [comment]
Fixed in dab42e6.

I noticed an inconsistency if UMUs were used with XXL engines.  XXL engines should generate 2 heat if the unit stands still, but if a unit uses UMUs it should generate 1 heat.  This seems like a strange interaction for a 'mech with an XXL engine and UMUs.  I created a rules clarification: http://bg.battletech.com/forums/index.php?topic=51078.0

I also fixed two other bugs, both in Server.addMovementHeat.  I found that used UMUs would make it so every other unit after it wouldn't generate movement heat (there was a return that should have been a continue), and also damaged radical heat sinks were processed after UMUs, meaning a unit that used UMUs and had a damaged RHS wouldn't properly get heat.
