### ISSUE TITLE
Ecm field in the deployment phase isnt shown correctly

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#223]
After deploying the last elemental BA, a small ecm field centered on the elemental BA appeared, even though it has no ECM.

The SRM carriers do have ECM though, but the ECM field didnt appear when i deployed them.

Reloading the save solves the problem and causes the ECM field to be displayed correctly.

[#battletech.zip](https://github.com/MegaMek/megamek/files/284102/battletech.zip)
![megamek](https://cloud.githubusercontent.com/assets/1191378/15573608/8594694a-238b-11e6-85f1-6bd530d4dae1.jpg)

**Comment by arlith** [comment]
I found an issue when the ECM hexes are updated in `BoardView1`.  The ECM hexes are properly computed, but since the hex image cache isn't changed, the hexes aren't redrawn properly.  I added a mechanism to clear a set of hexes from the cache, and now `BoardView1.updateECM` will clear the hex cache of any hexes that are updated.
