### ISSUE TITLE
41.17 : Backup MP cost calculated incorrectly if the mech is prone

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#224]
If you have a prone mech and click backup, and then try to backup into a hex, you have to pay 3 MP to stand for some reason, whereas if you click getup first, you only pay 2 MP to stand. To replicate, just start a new game with any prone mech using the lobby deployment options and then try using the backup button.

[megameklog.txt](https://github.com/MegaMek/megamek/files/284261/megameklog.txt)

![megamek](https://cloud.githubusercontent.com/assets/1191378/15574611/c1372db0-2391-11e6-8011-d8d913a41d5d.jpg)

**Comment by arlith** [comment]
The issue here is that the A* heuristic doesn't consider the MP cost to stand.  This means that it can underestimate paths costs, so the heuristic isn't admissible and so path optimality isn't guaranteed.  To fix this, I updated `ShortestPathFinder.getElevationDiff(...)`: if the moving entity is prone and the current path does not contain a stand or careful stand step, the path is penalized by 2.

What was happening in this bug is that the path [R Up B] was being picked before [Up R B], essentially because the R step wasn't being penalized for having to stand, while Up step was being penalized for having the wrong facing.

**Comment by Akjosch** [comment]
The heuristic in A* may never *overestimate* a path cost, but it's fine if it underestimates it. In fact, a heuristic which always returns 0 is perfectly fine - it just turns A* into Djikstra's Algorithm.

That said: An overestimating heuristic, even one which returns three to five times the actual distance to travel, can lead to significantly better performance at little cost - only a small percentage of paths in a relatively open terrain situation will not be ideal, but they will still tend to be close to ideal.

**Comment by arlith** [comment]
If I had actually thought about it, I would've realized it.  Ah well, thanks for the correction.
