### ISSUE TITLE
[dev branch] terrain alterations do not respect chosen tileset

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/megamek#2246]
When taking an action to alter terrain, such as reducing woods to rubble or setting woods on fire, the new terrain uses the default tileset instead of the chosen tileset. 

To reproduce: start up a game, making sure the map contains woods. Change the tileset to something other than the default (e.g. desert). Set the woods on fire or reduce them to rubble via clearing attacks. Note that the new hex uses the default (grassland) texture.

This can be fixed by re-setting the tileset to the desired value, but should probably not occur in general.

**Comment by SimonLandmine** [comment]
So, 'changed' terrain should inherit the terrain style from the selected tileset theme, and if no tileset theme is selected, should inherit from the hex's original terrain style. That makes sense.

**Comment by SJuliez** [comment]
Hmmm, I have the feeling that the Server burns down the wood, sends a new hex to the clients and since the board theme change is purely client-side, this new hex doesnt know of that theme change. Im beginning to think that the option to change the terrain theme was one of my misguided ideas. This would be better placed in the lobby (and in the board editor).

**Comment by SimonLandmine** [comment]
I'm not sure whether anyone uses 'theme change' to change visibility for improved accessibility, though.

And I like the fact that the map loads with the original theme (that I have so carefully chosen) [grin] - especially when I've used multiple hex themes on the one map to reinforce terrain appearance - although at least the map picker now renders the map with full art rather than minimap visuals.
(Please don't remove the ability to set theme hex by hex!)

**Comment by SJuliez** [comment]
Yes, Im not speaking of removing anything in the board editor, only of the option "Change Theme" in the View menu and only when in a game. I thought this was a neat thing in the time when everything was desert landscape to be able to change it to grass. But thats no longer necessary. Now one can enjoy desert boards when they are actually created as desert boards. It creates this particular issue and I guess any client-side change in a server-driven game is just not a such good idea. Board changes would be better placed in some board processor tool in the lobby where it would affect the board for everyone. (Board Post-Processor... moonify a board, flood it, grow forests... this gives me ideas ;)

**Comment by SimonLandmine** [comment]
Sorry, yes, doing my "what if"-ness too much. Very good point about client-side-only changes in server-driven systems.

> (Board Post-Processor... moonify a board, flood it, grow forests... this gives me ideas ;)

Ooh ... maybe a chance for light woods to become heavy, for foliage to become light woods, and for clear hexes within x of light woods to become foliage, or for clear hexes in the middle of large clear areas to do the same. Then you could loop through several times, as desired, to watch the woods grow. Similar logic could be employed to shrink woods. Hmmm. (For flooding areas, you (we?) might need to work out how to handle semi-submerged trees, and seabed terrain affecting surface vessels ... or just rule that flooded trees are gone, not just turned to Rough.) I should probably stop having ideas now ...

**Comment by SimonLandmine** [comment]
Quick check - will 'change tileset theme' in the Board Editor now change the theme of all hexes, or just how they are rendered?

**Comment by SJuliez** [comment]
It sets the theme of all hexes. So, it is not just some graphic override. It will save to the boardfile.

**Comment by SimonLandmine** [comment]
Perfect! Thanks, as usual!
