### ISSUE TITLE
RFE: Option to Suppress Fire, Smoke, Out of Fuel, and Smoke Drift Messages

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#226]
Perhaps, there could be an option to suppress these messages. It does take awhile to transmit them. 

700 lines for stuff is burning, smoky, etc. 29K of data. 

And the sad truth is this isn't even the worst I've seen.

[IGiveUHellFire.txt](https://github.com/MegaMek/megamek/files/285313/IGiveUHellFire.txt)

**Comment by arlith** [comment]
29K of data that can compress down to 2.3kB.  I get what you're saying, but I don't know that this is really worth spending time on.  Trust me, there's more time spent on other things than on transmitting the report text (making fire processing work faster was one of the first things I fixed with MM).

**Comment by scJazz2** [comment]
Re-Open... it isn't about the packet size. Do you know how many scrolls it takes to get to the bottom of the Round report. And again 700 events isn't even close to the top. Plus... none of that data is compressed in the GameLog.html.

If you don't want to do it fine. Re-Open and leave it alone.
