### ISSUE TITLE
SWD-2 Swordsman has incorrect entry date

### ISSUE THREAD

**Issue by DaddyHolby** [MegaMek/megamek#23]
MegaMek version: 0.41.13
MekHQ version: 0.3.24-git
MegaMekLab version: 0.1.49-git

I went to load the SWD-2 Swordsman into MegaMekLab and got the following errors (Git won't accept my png nor a converted gif so I have to type it out):

Warning:Invalid unit, it might load incorrectly!
Cockpit is illegal at unit's tech level (IS TW non-box set, 2482): Standard Cockpit (IS advanced)
Gyro is illegal at unit's tech level (IS TW non-box set, 2482): Standard Gyro (IS advanced)

This did not happen with the 0.3.21 version of MekHQ (MegaMek v 0.41.11, MegaMekLab v 0.1.47) as the entry date in that version was set to 2571 not 2482 which is what it's been changed to and seems to be earlier than either the standard cockpit and gyro that it has.  So either the intro dates for the standard gyro and cockpit have to change or the mech's intro date has to change to a minimum of those intro dates.

I have not found a published source for the intro dates.

**Comment by arlith** [comment]
Git has certain file extensions that it accepts.  These extensions are based on filename only, so any attachment you can rename to an accepted type (like screenshot.png.txt would work).  Also, you could host images on a third party host, such as imgur.

As for the issue at hand, this is something we've been struggling with since TL checking for gyros, cockpits and engines was added.  

If you look at the Master Unit List for the SWD-2, it lists the intro date as 2482: http://masterunitlist.info/Unit/Details/7182/swordsman-swd-2.  Basically, MM is using canon dates, but the canon dates cause an issue.  We're looking into it, but for the time being in MM you can use the "allow illegal units" option, and in MML the message can be ignored.

There is a ticket on the SF issue tracker: https://sourceforge.net/p/megamek/bugs/4671/.  I'm going to close this ticket as a duplicate (although you can still post here in the discussion).

**Comment by DaddyHolby** [comment]
Thanks for the quick reply Arlith.  I swear Git says that it supports pngs and gifs so that's what I tried and gave up ratherly quickly.

I hadn't had time to check the MUL for the date nor did I realize that it was IO's tech intro dates not lining up with the unit intro dates.

Thanks again.

**Comment by djmbm** [comment]
Git the protocol supports them for the code repositories, but the GitHub tracker does not.

**Comment by arlith** [comment]
GitHub does say that it supports attaching pngs and gifs and jpgs to issues/pull-requests: https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

I have not tried to attach files yet myself, so I haven't run into issues.
