### ISSUE TITLE
PSR forced when quad stands with all four legs

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#2301]
Version 47.10

I have no clue what caused this, and have not been able to reproduce outside of this game.

In the movement phase of turn 23, the Great Turtle is forced to roll a PSR while standing up when there should have been no need for one (all four legs were intact—page 19, BMM).  Considering its heat, critical hits, and special piloting abilities were putting it at 2/2/3 speed (hip critical, upper leg critical, two sensor hits in head, animal mimicry, and maneuvering ace), running should have been an impossibility anyway. 

Attached is the game file where this occurs. 
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/5324356/autosave.sav.gz)

**Comment by neoancient** [comment]
The PSR is not for standing. It's for using running movement with a damaged hip or gyro (hip in this case). The original movement of 3/4/3 is reduced to 2/2/3 by the hip damage (walk MP / 2, rounded up), and the damaged actuator on another leg reduces walk MP by one more, to 1/1/3. Standing is running movement because it exceeds the walk MP, and in this case has to use the minimum movement rule.
