### ISSUE TITLE
RFE - Screenshot Board Overtime

### ISSUE THREAD

**Issue by buzzzz2138** [MegaMek/megamek#2348]
### Environment
MegaMek and HQ MegaMek
Windows
Java 8 update 261

### Description
Would like the option to have Board->Save As Image auto saved like the game auto save every time the board changes.  Or perhaps at the end of each phase. 

### Files
NA

**Comment by HammerGS** [comment]
Arlith worked on this branch a few years ago. It was almost ready before he retired.
https://github.com/MegaMek/megamek/tree/gameSummaryImages

**Comment by buzzzz2138** [comment]
I did a search for Image and Sheetshot and didn't find that.  

I have experience programming, but not in Java.  Nor in Github.  My experience is in perl and svn.  Any way to see what code they had changed?

**Comment by HammerGS** [comment]
I've asked Arlith if he can add some notes here.

**Comment by arlith** [comment]
This link will give you a diff between the branch and master right now: https://github.com/MegaMek/megamek/compare/gameSummaryImages

It's been a while since I worked on this, but I'll jot down my memory of what needed to be finished.

First, I had intended this to create some type of animation/video so you could "watch" the game progress. This isn't done, I had just tested with an offline tool to combine the images after the fact.

The main remaining issue revolves around file management and configuration.  I was saving the images at board resolution, which could be quite large.  I was concerned about this file size adding up over time over the course of many games.

I also think it needs some type of "game identifier" so that all images go into a directory based on which game you're playing, so if you save and load a game, all of the summary images stay in a directory unique to the particular game.

I also think more configuration could/should be added, especially around how images are saved and which phases they are saved for.

I recall that everything worked if you just loaded up and played the game start-to-finish.  You'd end up with a directory of images at the end of every phase from the board view.

**Comment by SimonLandmine** [comment]
That sounds good - I've done that myself manually to create an animation before. I appreciate the concerns about file size and destination directory - I was handling those myself manually, too.
