### ISSUE TITLE
show sprite in report  failure

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/megamek#2378]
MM 47.11 MHQ version
java 14.0.1

![image](https://user-images.githubusercontent.com/34722287/98063228-876ec300-1e1d-11eb-9a46-58a2cbfa73a5.png)

![image](https://user-images.githubusercontent.com/34722287/98063197-78881080-1e1d-11eb-9bb4-c48f3744b6ff.png)

as can be seen in the images, the show sprite option is set to true but the images are not showing up.  I have tried setting it to false and back to true with no result.

attacked are the log and save file.  let me know if you need any other data
[glitch.zip](https://github.com/MegaMek/megamek/files/5485203/glitch.zip)

**Comment by Windchild292** [comment]
What is your current Java version? If you are not running Java 11, please do upgrade to that and test once more.

**Comment by bczretribution** [comment]
java 14, listed it with my MM version at the top

**Comment by sixlettervariables** [comment]
Double blind?

**Comment by bczretribution** [comment]
i am using double blind now but wasn't at the time.  a friend in the same match with me had them working fine.

**Comment by CreativeHammer** [comment]
So I have been having a similar issue for a while. For me the problem was the fact that i had a java 12 dev kit installed from when I was trying to get a Class file from a future release.
I checked my task manager and megamek was running from ver 12 instead of JDK 11.
So i uninstalled all versions of java and reinstalled the openJDK 11 and it fixed it for me.
Since OP has issues while running ver 14 maybe the issue with the sprites on reports is caused by any version of java newer than 11? Not a programmer so no idea if that makes sense.

**Comment by bczretribution** [comment]
closing as this is out dated and no longer applicable
