### ISSUE TITLE
Hidden Units Testing Notes

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/megamek#238]
I saw in the 41.18 release notes that hidden units needs some testing.  Below are my notes on a few things that do and don't seem to work. The attached savegame offers the opportunity to run the same tests that I did.  337th has a Bloodhound AP and a Beagle AP equipped unit to test detection. Princess has a variety of hidden units to deploy. I set all of the applicable hidden units' stealth systems to active during the deployment phase for my tests. That still needs to be done when using the savegame.

Main rules in TW p259

Deployment:
I can't deploy hidden units into building hexes that have underlying pavement terrain, nor wooded and rough hexes with a road running through them.

Standing Mechs can deploy hidden in planted field hexes and swamp hexes (Not technically a rules violation, but doesn't make much sense...)

Movement:
Mech attempting to enter hex with a hidden mech (violating stacking) doesn't reveal the hidden mech. > This is ok per TW Errata v4.2.2015.6.6, but the game effect is weird. My mech just bounces off the hidden mech's hex and ends its movement with no explanation of why...

Firing:
Clearing a woods hex that contains a standing, hidden mech does not reveal the mech. (This is a grey area according to the rules, which don't give any information about this special case, but it stands to reason that a mech hiding in a forest should be revealed when the forest ceases to exist unless the mech is hidden and prone to start with...)

Firing a point blank shot does not reveal a hidden unit. According to p259 it should, as a unit only remains hidden until it attacks or moves.

Bot:

Princess bot is not able to fire point blank shots, nor activate hidden units. I'm aware that she doesn't have the intelligence to make the most effective use of the hidden units feature, but she might benefit from basic behavior, such as:

attempting a point blank shot whenever given the opportunity
automatically activating a unit after taking any point blank shot

She is able to automatically activate a unit that is revealed prematurely by sensors

Detection:

In Double-Blind play, 'undetected' units are revealed when in LOS of a hidden unit, which could potentially help players to find hidden units, especially in restricted terrain or low-visibility environmental conditions.

BAP-equipped units detect hidden units within LOS even when using 'standard' sensors instead of the BAP.

BAP-equipped units detect hidden battle armor equipped with improved stealth armor - see TacOps p278, only the bloodhound probe should be able to detect hidden infantry

BAP-equipped units detect conventional infantry without stealth armor - see TacOps p278, only the bloodhound probe should be able to detect hidden infantry

BAP-equipped units detect conventional infantry with stealth armor - these should be undetectable when hidden - see TacOps p278 

BAP-equipped units detect units with active void sig system - see TacOps p349, only the bloodhound probe should be able to detect a unit with an active void sig system

BAP-equipped units detect units with active null sig system - see TacOps p336, only the bloodhound probe should be 
[337th-HiddenUnitsTest.sav.gz](https://github.com/MegaMek/megamek/files/297797/337th-HiddenUnitsTest.sav.gz)
able to detect a unit with an active null sig system

**Comment by arlith** [comment]
> Firing a point blank shot does not reveal a hidden unit. According to p259 it should, as a unit only remains hidden until it attacks or moves.

Apparently I misread the rules and missed the sentence in the first paragraph that says:

 >Hidden units remain hidden until they attack or move,
or until an enemy unit moves into their hex, attempts to move
into their hex or ends its movement adjacent to their hex.

Outside of that sentence, nowhere else in the rules does it mention when hidden units are revealed, other than implying that they are revealed when a player activates them, so when I implemented it, activating a unit is the only way it becomes unhidden, I believe.

While the actual rules make sense, I went through some mental gymnastics with the current implementation.  I think that not revealing a hidden unit when it makes a PBS is tactically interesting.  Basically, your opponent knows that hidden unit is there, so it's tactically advantageous to reveal the hidden unit, otherwise it could just be a wasted unit, but keeping it hidden could also be useful (area denial, opponent making a mistake, etc).  

> In Double-Blind play, 'undetected' units are revealed when in LOS of a hidden unit, which could potentially help players to find hidden units, especially in restricted terrain or low-visibility environmental conditions.

This is something I hadn't considered.  I agree with what you say, but the implementation may be a bit tricky.

> Active Probe Detection...

The rules for active probes detecting hidden units is on TW pg 129.  The "sensor selection" is related to "sensor spotting in TO pg 222.  This seems like a potential gray area, but the TW rules about detecting hidden units are pretty plain and make it seem like the currently active sensor suite shouldn't matter.  

Beyond that, for the initial implementation, I basically focused on TW without Princess implementation (beyond enough implementation so that hidden units won't cause Princess to halt the game; the bot will at least decline PBS).  So, your other comments, while valid, just haven't been considered yet.

**Comment by arlith** [comment]
I've fixed all of these issues as part of PR #312.  There are details in the commit messages, but I'll try to give a brief summary.

I believe all of the detection should be according to the rules, including stealth systems and probes.  Hidden units are also revealed when they make a PBS, as well as when an enemy unit ends its turn adjacent to a a hidden unit.

I found that there was some logging code I had added for when a unit tries to move into/through a hex with a hidden unit and there's a stacking violation.  This is much better reported now.

I also found that hidden units are supposed to be able to spot, but weren't allowed  to.  Indirect LRMs just got a bit scarier.

I didn't update Princess.  That's really kind of a separate issue.  Princess has mostly been updated so that the bot doesn't stop the game, but it still doesn't really know what to do with hidden units.

Finally, I tried to fix the visibility indicator thing, but it's a bear.  Basically, the same data that is used to indicate visibility is also used by the "enemy's" client to determine if it should display the unit: if I make it so that the player is unaware that his unit is seen by a hidden unit, then the client of the hidden unit *also* doesn't see the unit.  The fix for this is kind of ugly.
