### ISSUE TITLE
RFE - Searchlights per Tech Manual (Borderline Unofficial Rule)

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#2384]
Night fighting is one of the biggest pains with the TableTop Rules as written. Techmanual pg 237 describes the construction rules as 

_All units except for Combat Vehicles and BattleMechs are presumed to incorporate at least 3 hand-held searchlights
as part of their design (2 Front and 1 Rear) to reflect running lights, headlamps and taillights—though some vehicles may designate these as strobes for emergency and police vehicle units or warning beacons. BattleMechs and Combat Vehicles may instead mount one mounted searchlight at the designer’s option, at no cost in weight, slots, or C-bills. Over and above these “free” lights, additional searchlights may be mounted on all units in accordance with standard core construction rules._

Given the lights are no cost I can't see a reason why every unit wouldn't have them per the above description. This would give every unit at least one, with an option to purchase more.

**Comment by SimonLandmine** [comment]
I presume that units that have actually been built with searchlights at a cost would gain redundancy, so they would have to lose both to enemy fire before becoming 'light-less'?

**Comment by gsparks3** [comment]
I'm given to understand that the right-click option in the MM lobby (Equipment - Add Searchlights) is effectively this rule. It could simply be made active by default - since they have no weight, size, or cost, there's no penalty to having one when you don't need one (other than a few extra lines of text when you get hit in a torso location and it rolls to see if the searchlight is destroyed).

**Comment by HammerGS** [comment]
Yes, but testing it looks like the method isn't working. It also involves the player manually doing this every game. Versus having it happen automatically.

**Comment by SJuliez** [comment]
We seem to have three types of searchlight: 1) Actually mounted ones at 0.5t like in the Inquisitor II, 2) Quirk Lights like in the Warhammer and 3) the somethings that are added by the lobby right-click and are neither added as quirk nor as equipment. I tested it and all seem to work, although nr.3 is on by default while the others are off by default and must be turned on in the movement phase.

It seems to me from TO/StratOps/BMM (but I am guessing) that the authors intended to have the searchlight quirk available to every unit if the players/scenario allows for it (as anything but the quirk requires a redesign of the unit). Actually giving the quirk to every chassis would have made it meaningless and not reflect the specific chassis image anymore, so that was no option. Therefore the cited TechManual rule. 

In a theoretical pursuit scenario that directly follows a fight scenario the players could agree that the involved units do not get a free searchlight (or at least the pursuers don't). This sounds to me like a Game Option "Add the searchlight quirk to every unit for free". If set, the game ensures all units get the quirk if they don't already have it. If not set, it's up to the players to add it. Such a game option could be made easy to reach, e.g. in the Planetary Conditions dialog itself.

Units that already have the quirk kinda seem at a disadvantage but I don't see techs sticking a second searchlight on a unit that already mounts one like the Warhammer. If they did, why not add five free searchlights to every unit...

**Comment by HammerGS** [comment]
I know quirks are intended to be the optional rules so not every unit is supposed to get them. I think that presents the challenge of giving all the units search light quirks, turn off quirks and your search lights are gone.

**Comment by SJuliez** [comment]
True, quirks are optional. I'll look into it.
