### ISSUE TITLE
Using TAG for indirect LRM spotting

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megamek#24]
There does not currently appear to be a way to fire TAG during the Indirect Phase if the overall force does not have Semi-Guided LRMs/Homing Arrow-IV/etc.

However, Total Warfare p.142 allows for units with TAG to spot for indirect LRM fire, removing the penalty for both spotting and shooting.

Would this be difficult to implement?

**Comment by arlith** [comment]
Unfortunately, that's not the way it works.  The wording in TW pg 142 is a little strange, but it's saying that if the TAG is fired, it doesn't count as weapons fire if the unit is a spotter.  It's not saying that TAG effects indirect fire (that only happens if using semi-guided LRMs).

This has been clarified by CGL on at least two occassions:  http://bg.battletech.com/forums/index.php?topic=10569.msg251076#msg251076, http://bg.battletech.com/forums/index.php?topic=15221.msg350506#msg350506.

(As a side not, any unit can spot for LRM indirect fire, you just target a unit and click the "Spot" button during the weapons firing phase).

**Comment by AlphaSled** [comment]
Ugh, woops. Sorry about that.

**Comment by pheonixstorm** [comment]
TAG doesn't help for indirect but a Recon Camera does 

>A unit with a Recon Camera can use it to act as a spotter for LRM Indirect Fire (see p. 111, TW)
>as if it were a TAG (see p. 142, TW), but cannot use it to designate targets for other TAG-guided weapons
