### ISSUE TITLE
[0.41.19 : Error] Dropship Cannot Eject

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#241]
Savegame attached.

Load game, skip Vulture #4's movement. Now during DroST's turn, use all velocity, hit eject, hit yes, receive the message 'This unit has not used all its velocity". 

[DropshipCannotEject.gz](https://github.com/MegaMek/megamek/files/304119/DropshipCannotEject.gz)

**Comment by SirMegaV** [comment]
IIRC, previously I reported that in order to eject, I'll have to use up all
my moves. You fixed that.

**Comment by arlith** [comment]
So, this one is strange.  You did report this bug before, and I did fix it.  It was originally reported as [SF Bug #4617](https://sourceforge.net/p/megamek/bugs/4617/), which I fixed in a5d621.  Then, somehow, in 34136168, this fix was reverted.  This was a mistake on my part.  I've re-added my original fix.
