### ISSUE TITLE
47.14 Weird two-tone effect while using "Darken hexes outside field of view"

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#2413]
### Environment
47.14 (first noticed in MekHQ integrated Megamek, reproduces when loading save in standalone MM)
Windows 10
Java 11.0.8

### Description
My preferred client settings should provide a uniform darkening of hexes outside of the field of view of the selected hex. Instead, an odd "two-tone" effect is sometimes observed, with some hexes partially darkened (relative to the specified level) and others fully darkened. 

In a probably-unrelated issue, the slider for "Opaqueness for outside Field of View overlay" seems to decrease slightly over time, without me telling it to do so. 

Screenshot of relevant client settings:
![image](https://user-images.githubusercontent.com/59574316/99749021-b175e580-2aab-11eb-82a4-a80a12a0847a.png)
(uncertain if other client settings should affect this; can provide them if instructed on how to do so)

Screenshot displaying "two-tone" effect:
![image](https://user-images.githubusercontent.com/59574316/99749061-c3578880-2aab-11eb-8fac-beb5ff86ac48.png)
The more distant regions have the level of darkening I usually expect with the current client settings. 

### Files
[FieldofView.sav.gz](https://github.com/MegaMek/megamek/files/5570855/FieldofView.sav.gz)
Player name: Greyscales

I don't expect the log files to have anything, but am including them anyway. They may include log data from previous scenarios. 
[megameklog.txt](https://github.com/MegaMek/megamek/files/5570857/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/5570858/mekhqlog.txt)

**Comment by sixlettervariables** [comment]
One question:
> "... seems to decrease slightly over time ..."
Visually as in the slider shrinks, or the value decreases?

**Comment by gsparks3** [comment]
Value decreases. I normally set it to 50% when setting up a new version, and you can see that it's a bit lower now.

**Comment by sixlettervariables** [comment]
The value decreases because of our math. Looking into a fix.

**Comment by arlith** [comment]
The two-tone affect is intended.  Actually, the default is that it's shaded vs striped pattern.  What this distinguishes is between "can't see, but in sensor range" vs "can't see and out of sensor range."

This might be clearer if the `UnitDisplay` was showing sensor information but it's not.  The reason is, the sensor information in the `UnitDisplay` is conditioned on double blind being on: you don't have double blind on, but you do have sensors on.  This is a weird option combination (and perhaps shouldn't be allowed) because sensors don't do anything unless double blind is on.

I think line 461 of `GeneralInfoMapSet` can change the `ADVANCED_DOUBLE_BLIND` to `ADVANCED_TACOPS_SENSORS`.  As far as I can tell, there's no reason for it not to be `ADVANCED_TACOPS_SENSORS`. 

I think a tooltip could also help to describe what's supposed to be happening.

**Comment by gsparks3** [comment]
I see! Very interesting. That at least explains the effect - and also why it changes at random, because sensor rolls means the sensor ranges change at random, too. 

In this case, the only remaining issue would be that it's not explained somewhere; the actual display does not need to be changed.
