### ISSUE TITLE
PSR Penalty for Jumping in High G is being calculated wrong

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#243]
I'm currently playing on a 1.1 G world... wanted to double check the PSRs for Hi-G fighting and found this...

TO Errata
Under “Potential Damage From Jumping”, first sentence
“Make a Piloting Skill Roll, adding the appropriate modifiers for low gravity; a standard Piloting Skill Roll is made in high gravity, with no modifiers.”
Change to:
“**Make a standard Piloting Skill Roll, applying a modifier for every full 0.5 gravities above or below 1. For example .2 would apply a +1 modifier, while a 2.6 would apply a +3 modifier.**”

`
Grasshopper GHR-5H #2 (Devil Dogs) must make a piloting skill check (jumped in high gravity).
); needs 4, rolls 3 (Base piloting skill) + 1 (high/low gravity) + 0 (jumped in high gravity) Fumble!: falls.

Crusader CRD-3DW (Devil Dogs) must make a piloting skill check (jumped in high gravity).
Needs 4 [3 (Base piloting skill) + 1 (high/low gravity) + 0 (jumped in high gravity)], rolls 6 : succeeds.

Crusader CRD-3DW #2 (Devil Dogs) must make a piloting skill check (jumped in high gravity).
Needs 5 [4 (Base piloting skill) + 1 (high/low gravity) + 0 (jumped in high gravity)], rolls 11 : succeeds.

Griffin GRF-1S (Devil Dogs) must make a piloting skill check (jumped in high gravity).
Needs 4 [3 (Base piloting skill) + 1 (high/low gravity) + 0 (jumped in high gravity)], rolls 3 : fails.
'

There should be no G penalty at 1.1 Gs.

**Comment by arlith** [comment]
It's more than that.  According to TO, the PSR penalty is *only* applied to the jump PSR.  MM is currently applying it to *every* PSR.  This doesn't appear to be correctly.  I'm not exactly sure where this comes from, but it's always been like that.

**Comment by scJazz2** [comment]
Extra screw up... even if you fail the WRONG PSR it doesn't appear that damage is being done to the legs.

And then there is the old bug from SF and Hi-G Related to Gunnery.

https://sourceforge.net/p/megamek/bugs/4277/

Sorry... no clue how deep the rabbit hole goes.

**Comment by arlith** [comment]
That bug on SF is fixed.

**Comment by arlith** [comment]
That last commit was supposed to have "Fixes" in the commit message to close the ticket, oh well.

Anyways, I broke the fix into several commits.  The first fixes issue with the roll being made but no damage was applied (the roll was always made, even when no damage would be dealt.  The way the rules are read makes it seem like the check is always made, but it's silly to make a roll when failure is 0 damage).  I also noticed that the gravity PSR modifier was being applied to *all* PSRs, but according to the rules it should only effect the jump damage PSRs, so this was fixed in the second commit.  The third commit fixes the fact that the modifier was too aggressive; it was using a ceil instead of floor.

Each commit message also some detail about what was fixed.
