### ISSUE TITLE
Smoke & chaff from artillery appears at the end of weapon phase instead of end of off board attack phase

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#245]
Smoke & chaff from artillery appears at the end of weapon phase instead of end of off board attack phase. Smoke screens & laser inhbiting ammo are unable to defend friendly units on the turn shells land because weapons fire resolves before chaff and smoke are added.

**Comment by arlith** [comment]
There are various `Server.devlier<X>Smoke` methods, that create the smoke cloud for various weapons (missiles, grenades, mortars, artillery).  All of these are basically the some overall code with some modifications.  In call cases, it looks like the methods were setup to update the `Terrain` in the affected `Hex`, but none of them actually do this.  They do create a `SmokeCloud` that gets added to the game, and then in the end phase, `SmokeProcessor` fires and properly adds the smoke.  The fix for this is to also add the smoke when the weapon is delivered.
