### ISSUE TITLE
LAM forced to make piloting roll for entering rubble when at 1 level above terrain

### ISSUE THREAD

**Issue by BowtieBob** [MegaMek/megamek#2530]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
What version of MegaMek does your issue apply to?   HQ's MegaMek 0.47.15
What operating system are you using?  Windows
What java version are you using?  11

### Description
On any round that I move a LAM from ground level to flying above the terrain (airmech mode), I am forced to make a piloting skill check for entering rubble even though I am flying above it.  Subsequent turns do not have this problem as long as I start the turn in the air.
![image](https://user-images.githubusercontent.com/70545594/103106795-1e762100-45fe-11eb-8f1d-889205152965.png)

### Files
Here is a game save file including my custom LAMs and log files.
Username: Nightstalkers
[Lam.sav.zip](https://github.com/MegaMek/megamek/files/5740561/Lam.sav.zip)

**Comment by sixlettervariables** [comment]
Did you actually have to roll the PSRs or were you just nagged about it and they were skipped?

**Comment by neoancient** [comment]
The PSR is not actually being required during movement. The nag only shows when the unit starts the turn on the ground, then lifts off and flies over the rubble. I haven't looked at the code yet, but the likely reason is that it's checking whether the unit is airborne rather than whether the step is airborne. When testing the path the unit position is not changed, but when executing the movement the unit is airborne at the time of checking.

**Comment by BowtieBob** [comment]
Correct, I hadn't noticed that the roll wasn't happening before.
