### ISSUE TITLE
XML-based logging

### ISSUE THREAD

**Issue by SenorPez** [MegaMek/megamek#259]
Add an option to write the game log as XML instead of the HTML-based logging default option. This would make it easier to parse logs for battle reports.

**Comment by MGM175** [comment]
Idea seems to be good, but HTML-based loggins is quite nice in it's actual form - sometimes I need to do some 'copypasta' stuff for forums. In XML - it would be a bit harder without dedicated parser to do the same :(

**Comment by wildj79** [comment]
I would take this a step farther and say there should be an option to write the game log as plain text.

**Comment by arlith** [comment]
I kind of feel like this request is incomplete.  By adding closing tags, the current format would technically be XML (since modern, well-formed HTML is XML).  It's not clear to me whether the request wants the file to be parseable as XML, or wants a more fully featured XML schema to make the parsing easier.

It's probably worth noting that the writing of the gamelog doesn't seem to be a feature that had a lot of design effort put into it.  Having it write output in a more complex XML-schema isn't something that's likely to happen, in my opinion.

**Comment by wildj79** [comment]
I feel that this ticket deserves an update. Though this hasn't been fully implemented, the development team has taken a step in the right direction. Instead of simply redirecting standard output to a file, they have implemented logging functionality through a library called `log4j`. `log4j` is a powerful logging library that allows a wide range of output types. It's only partially implemented, but once all of the logging functionality is being run through the library, it's a simple matter of setting up configuration values to output the desired information into just about any format you can think of.

**Comment by neoancient** [comment]
Closing as outdated.
