### ISSUE TITLE
Mass edit deployment round

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#263]
For large battles it would be helpful if you could select multiple units in the MM lobby and change the deployment round for all of them at once using a right click menu.

**Comment by SirMegaV** [comment]
I think hot loading and rapid fire will benefit greatly from this too.

**Comment by BLOODWOLF333** [comment]
Yes! I second MegaV's addition, I have always wanted a mass check the box for burst fire MG's or that should just be automatically checked when the player turns that rule on since obviously that means we would like to utilize that TO rule.  LRMs though......I dont hotload when its a 15 or 20 since too many crits but, a mass enable would still equal less clicking and more playing on the players part.

**Comment by BLOODWOLF333** [comment]
I see the mass configure window having a new tab for equipment like when normally configuring units.
and check boxes for rapid fire MGs
and then a check box for each LRM launcher type that is in your force (if your force doesnt have any LRM15's or 5's then will only list a box for LRM 10 and a box for LRM20)
and can check to have all LRM10s hotloaded but, maybe not for 20s since they have so many crits and its too much of a risk for example.

**Comment by arlith** [comment]
Looks like I forgot to update this ticket when I added features.
In commit 93ffe107, I made it so that the CustomMechDialog can be shown for multiple units, and right now it display the deploy tab, so all deployment options can be adjusted for multiple units.

Additionally, in 556d4113dca949325c1 I added right-click context menus for configuring rapid fire MGs, hot loaded LRMs, and searchlights.  When multiple relevant units are selected, you can right click and there's an "Equipment" menu with submenus for adjusting these options.
