### ISSUE TITLE
[0.48] Maneuvering Ace SA cannot be turned off

### ISSUE THREAD

**Issue by Tecmes** [MegaMek/megamek#2699]
### Environment
MM 0.48   Java 11     Win 10/64

### Description

* The MAneuvering Ace Special Ability does afford shifting like a quad Mech. This works, but you can't switch off the shifting, that is change movement mode.

**Comment by gsparks3** [comment]
If the auto-movement-calculator is making you shift when you don't want it to, do it tile-by-tile instead, including specifying turns manually with shift+click. E.g. if I want to move into the northeast hex facing northeast, declare the facing chance first then click on the hex, and you'll walk into it instead of making a lateral shift with no facing change (as it would do if you just clicked on the northeast hex).

**Comment by Tecmes** [comment]
My bad sorry I was indeed using the trick @gsparks3 suggests  but somehow I was convinced there was an option for quads to change movement mode.
