### ISSUE TITLE
Issues with Terrain Handling (PSR's wrong)

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#291]
Per this forum post:
http://megamek.info/forums/index.php?topic=2446.msg16556#msg16556

Relevant Text from post:
_Oh, also spotted several bugs with the way the game handles these terrain types.  The don't modify your PSRs.  They apply to hover vehicles, which makes no sense.  Rapids are supposed to give a chance of getting bogged down, but don't.  The MP and PSR modifiers are only supposed to apply when the water depth is >=1.  Currently, depth 0 water with rapids incurs a +1 MP modifier._

I have not tested this.

**Comment by pheonixstorm** [comment]
Rapids p50 TO

> For any water of Depth 1 or greater that contains rapids, apply a +1 MP cost to enter that hex, as well as a +2 modifier to all Piloting Skill Rolls made while in that hex.

Torrent p52

> For any water hex of Depth 1 or deeper that contains torrents, apply a +2 MP cost to enter that hex, as well as a +3 modifier to all Piloting Skill Rolls made while in that hex.

Both go on about water flow and what happens during a failed PSR (swept down river 3 hexes for Torrent. 2 for rapids)

MM doesn't check for depth when applying the MP and PSR modifiers, though the map editor should probably check for legal depth rather than leaving it for MM to deal with during a game.

I found nothing that saying hovers are immune, but seeing as they would be above the water I think this may be a rules oversight rather than a MM issue.

There is nothing in the rules I could see about being bogged down in Rapids or Torrent. Failed PSR checks mean to get displaced several hexes, not get stuck in the one you are in. To stay stationary you must pay x MP each turn (2 and 3 respectively).

**Comment by wildj79** [comment]
Expanded Movement Costs And Planetary Conditions Tables p. 34, Rapids, under the MP Cost per Hex / Terrain Cost column has a footnote
> 24 Units entering this terrain may be stuck; see _Bog Down Rules_, p. 62.

Doesn't seem to apply to Torrents.

**Comment by pheonixstorm** [comment]
That was correctly in errata to point to footnote 23
p6 of the latest (3.5) errata. Still no footnote for torrent though.

**Comment by wildj79** [comment]
Footnote 23, p. 35:

> 23 These terrain modifier do not apply to hover, WIGE or airborne VTOL vehicles; in the case of snow, does not apply to the unit if it mounts the Snowmobile Chassis and
Controls Modification

Makes more sense now.
