### ISSUE TITLE
BV calculation missing for Void Signature system.

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#2952]
From this forum post -- https://bg.battletech.com/forums/tactical-operations/void-signature-system-battle-value/

I know Neoancient has a BV rework in the works but posting to make sure we don't miss something. 

### Environment
What version of MegaMek does your issue apply to?  0.49.2

### Description
Rules on pg 194 of TacOps:AU & E

**Comment by neoancient** [comment]
MM does calculate the void signature BV. There is no benefit for a mech with a target movement modifier > 3, which is the most likely reason the poster did not see anything. Here is the relevant part of the calculation for the Archer ARC-9W:
![Screenshot from 2021-06-18 20-15-55](https://user-images.githubusercontent.com/16927464/122627124-3b525500-d073-11eb-8e11-76e2cd5a32a5.png)


I can't respond to the original post because it's in the rules questions section.
