### ISSUE TITLE
Manei Domini Infantry Files?

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/megamek#298]
Is it possible to code M-D implants into BLK files in order to build things like the Tau squads from TRO 3085?

**Comment by pheonixstorm** [comment]
I don't think so or it probably would have been viable in MML.

I am slowly working on updating the implants as well. There were some changes in IO that need to be made in MM

**Comment by arlith** [comment]
It's tricky, but it would be possible.  The issue is that the MD implants are handled as SPAs, which are part of the crew and that's not generally specified in the BLK file.

What could be done is to add a keyword into the BLK file, and that keyword would indicate to the loader that it should add a trait to the crew.  This isn't impossible, or even really all that difficult.  Mostly it opens up design questions: should we allow this?  Should we allow specifying arbitrary SPAs (or quirks) in the BLK files (or MTF files)?

**Comment by HammerGS** [comment]
I think the MD Implants are a bit of a weird situation as their implants are kinda like equipment. 

I would support the idea of having this.  We still have a chunk of the infantry from 3085 that needed to be added, and most of the infantry from TO to add.

**Comment by HammerGS** [comment]
Ignore this testing something.

**Comment by neoancient** [comment]
I hadn't seen this issue when I worked on this. I had the same reservations expressed by Arlith. I decided that while the unit file for other units describes the machine, the distinction between crew and equipment is not so clear in the case of conventional infantry. The bottom line in my opinion is that these augmentations are a canonical part of the unit and should be included. Note that not all of the cybernetic/prosthetic attributes are implemented, and those that are use the rules from Jihad Hot Spots 3072. Some of the rules were changed in Interstellar Operations.

Support for adding cybernetic/prosthetic augmentations in the unit file for conventional infantry was added in 7402934.
