### ISSUE TITLE
When A Tileset Theme Is Not Found 

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#305]
Currently when a player types in a theme for a board or when snowcapped mountains are used and such a theme does not exist MM will go into the StandardThemes.tileinc and use the first theme listed in place of the request theme that does not exist.

# The Standard MM themes

include "lunar/ThemeLunar.tileinc"    <Is what MM will use for non-existent themes
include "mars/ThemeMars.tileinc"
include "volcano/ThemeVolcano.tileinc"
include "grass/ThemeGrass.tileinc"
include "volcano/ThemeVolcano.tileinc"

Discussed with Arlith that maybe it would be better if MM instead ignored the request for a non-existent theme and just used the blank/no theme for the current tileset.

**Comment by BLOODWOLF333** [comment]
Actually come to find out I was wrong about MM going into the themes and using the first theme listed when one cannot be found.  After messing with the tilesets to get the accumulated snow to work correctly (because I had removed the base * "snow:1" "" "snow/.......gif" images not knowing why they were in there and because I had created a snow theme for MM) it instead uses whatever the first image filepath is listed in the tileset.  Like for largetexture I had to paste base 0 "space:1" "" "largeTextures/BigSpace.jpg" for that tileset to use that BigSpace image on space maps.  And with accumulated snow it starting to use that space image for the snow that appeared on the map.  Where as atmospheric used the lunar images because that is the first theme listed in the StandardThemes.tileinc which is also the very top line of the atomspheric.tileset.

**Comment by arlith** [comment]
The issue, as I see it, is when you have a theme specified for a hex, but the tileset doesn't have a definition for that theme.  In that case, there won't be any good matches, but it'll pick the first shitty match.  Because atmospheric includes StandardThemes.tileinc before it defines the "base" clear hex, whatever theme is defined first gets picked.  I don't feel like this is desired behavior, so what I did was adjust the cod a bit.

The relevant method is `HexTileset.baseMatch`.  Essentially, it defines a similarity measure for matching a given hex to a hex defined in the tileset.  The similarity is based on three terms: elevation, terrain, and theme.  Each of these values are multiplied together.

Previously, the theme value would either be 1 or 0.0001.  If both hexes had the same theme (including no theme) or they had a theme match, the value was 1, otherwise it was 0.0001.  I added an additional term that says if the original has a theme and the match has a null theme, use 0.001, otherwise use 0.0001.  The effect of this is that, if there's a theme match, it scores well, if the hex has a theme but the tileset entry has no theme, it's penalized a small amount, otherwise if there are differing themes it's penalized a large amount.  The effect of this is that the tileset will prefer unthemed bases if there's not a theme match, but if there's a suitably good entry with a mismatched theme it could still pick that one.
