### ISSUE TITLE
Strafing dropship: can only fire one bay which causes control roll for too much heat

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#308]
TW pg 242 for Allowed attacks by aerodyne DS and pg 243 for strafing rules
[DSStrafe.sav.gz.zip](https://github.com/MegaMek/megamek/files/410103/DSStrafe.sav.gz.zip)

During the heat phase it shows 140 heat after a strafe for a Leopard (PPC nose bay, 20 heat).

**Comment by arlith** [comment]
I added code to check to see when heat should be added for strafing attacks.  This code missed some important cases, so I've gone back and updated relevant implementations of `addHeat` to only trigger for the first shot in strafes.

Also had to update some heat computation in `WeaponAttackAction.toHit` which computed if the heat would exceed the heat  threshold.

Note, this was occurring because the bay weapon firing was on.  I think it may have worked without that.

**Comment by pheonixstorm** [comment]
Will try w/o and see what happens. Have another scenario coming up with another leopard.

**Comment by pheonixstorm** [comment]
I did not find an option to use individual weapons while airborne. The option to use individual weapons is for grounded dropships only.

**Comment by arlith** [comment]
I was (poorly) referring to the StratOps Advanced Heat option.

**Comment by pheonixstorm** [comment]
Hmm.. It is showing as checked in the HQ campaign file, was it unchecked in the save?

**Comment by arlith** [comment]
Yes, it was checked.  I was hypothesizing that this bug may only have happened with that option turned on.  But it's also possible it happened with or without the option.  With the fix applied, it shouldn't matter.

**Comment by pheonixstorm** [comment]
So the fix is for the heat off one bay and a strafing DS should now be able to fire more than a single bay?

Of the 3 bays I should have been able to fire (Nose PPC, RW Laser, LW Laser) I could only fire the nose PPC bay.

Will build with the fixed code and check both issue with and w/o that option checked and report the results.

**Comment by arlith** [comment]
As I said before, the option should be irrelevant.  There was an issue with heat calculations when strafing with Dropships.  This is fixed.
