### ISSUE TITLE
Ejected Vehicle Crews Should Count as Crippled

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/megamek#31]
Right now, ejected Mechwarriors are considered crippled and Princess (usually) tries to move them off the board if forced withdrawal is in play.  Ejected vehicle crews appear to be counted as undamaged infantry platoons and are moved as combatant units. I would like to see crews get withdrawn off the board too.

Alternately, perhaps there could be a segment of Princess' code that causes her to always attempt to moved vehicle crews and mechwarriors off her home edge, regardless of what their status is. Often, these unit types are not moved at all if environmental and terrain conditions are in use, especially those that reduce infantry MP to 0.

**Comment by arlith** [comment]
Fixed in 39a5cdb.

MechWarrior (which is the class that handles ejected mechwarriors) overrides Entity.isCrippled and just returns true with a comment indicating that the forced withdrawal rules consider ejected mechwarriors to be crippled (I couldn't find this in the rules, but it makes sense to me).

EjectedCrew did not do this, but I feel that I should, so I added the override.
