### ISSUE TITLE
Dive bomb resolution shows blank after first attack during game

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#314]
As of 0.41.21 dive bombing will work correctly the first time it is used. Any attempt in the next turn(s) will show the correct altitude lose but there is no weapon attack displayed in the phase report. The last time I found this to work was in v0.41.11 I believe this is related to the fix for 

> Bug [#4555]: Aeros strike/dive bomb now lose altitude before attacks resolve

 2a15365d59c607d7c48b3e692441ca0bd223a195

**Comment by pheonixstorm** [comment]
forgot a save.
[divebomb.sav.gz](https://github.com/MegaMek/megamek/files/419791/divebomb.sav.gz)

**Comment by arlith** [comment]
Alright, the problem here is that the altitude is find when the attack is made, then the altitude loss is applied, then the attack is handled.  During the attack handling process, computes another to-hit, which checks the altitude, then (since the ASF started at altitude 3) sees that the attack would crash the ASF, and marks it as illegal, so the attack doesn't get procesed.

**Comment by arlith** [comment]
I added a new state variable to Aero to track how much altitude it has lost that round, and that value is added back in to the checks for bombing.
