### ISSUE TITLE
Pilot dying when CT Ammo explodes

### ISSUE THREAD

**Issue by Bows3r** [MegaMek/megamek#3154]
### Environment
Megamek HQ version 48.0
OS: Windows 10
Java: Version 8 Update 301 (build 1.8.0_301-b09)

### Description
In my custom 'mech, I have 1 ton of Tandem-Charge SRM ammunition in the CT, when my mech experiences an ammunition explosion in the CT from heat, it destroys the mech as expected, then kills the pilot too which is unexpected with the specific text that he "Bakes to death". TacOps expanded heat scale is active, as far as I am aware and have read, those rules should not cause the pilot to instantly die under any circumstance from an ammo bin that explodes in an entirely different component than the component the pilot is located. This custom mech does not have a torso-mounted cockpit, I would expect this behavior from a torso-mounted cockpit.
![heatbug](https://user-images.githubusercontent.com/34803643/133493268-4b5ea2d2-67f5-49ac-af5a-dce4eb330cfe.png)

### Files
[heatbug.sav.gz](https://github.com/MegaMek/megamek/files/7172553/heatbug.sav.gz)

Playername: Bows3r

**Comment by gsparks3** [comment]
Per Total Warfare page 128, the pilot dies if the head or cockpit is destroyed, OR if the center torso is destroyed by an ammo explosion or area-effect weapon. Normally in Megamek the latter is overridden by the pilot ejecting due to the ammo explosion, but here your pilot does not eject, so their death is per the rules as written. I have no explanation for the unusual death notification message, however.

**Comment by Windchild292** [comment]
It is a little easter egg, which probably shouldn't show during an ammo explosion but is still fitting.

Closing based on the above
