### ISSUE TITLE
Princess Ignore List

### ISSUE THREAD

**Issue by buzzzz2138** [MegaMek/megamek#3157]
### Environment
0.48
Win 10
OpenJDK 11

### Description
Give Princess the ability to ignore targets.  Similar to strategic target, add to a list of target that she would ignore.

**Comment by SimonLandmine** [comment]
The intent of this is to be able to configure Princess to e,g, not attack 'neutral' DropShips, or so that Allied Princess units don't destroy 'capture' objectives upon the other side before the player has a chance to immobilise them.

**Comment by gsparks3** [comment]
Probably best to specify that unit is ignored offensively, i.e. the bot will never attack the specified target, but not defensively (bot will still consider incoming damage from the target). Otherwise she might get a little too careless about walking into range of a Demolisher capture target or similar.

**Comment by SimonLandmine** [comment]
Ooh, good thinking!

**Comment by buzzzz2138** [comment]
I would say that would need to be a checkbox.  In my situation the units to be attacked will be near the dropship, but if the dropship isn't ignored for damage, then Princess will stay out of range or make choices that are no ideal.

**Comment by NickAragua** [comment]
This has been implemented with PR #3288; the bot will still consider the unit for the purposes of determining what damage it can do, but will not fire on it.
