### ISSUE TITLE
Movement processing doesn't initialize current location

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#316]
Savegame attached. During Korvin KRV-2 #2's turn, move backward to 2320, then move forward to 2621, then press 'Move' and it will ht SharedUtility.doPSRCheck NPE.
[SharedUtility.doPSRCheckNPELog.txt](https://github.com/MegaMek/megamek/files/424150/SharedUtility.doPSRCheckNPELog.txt)
[SharedUtility.doPSRCheckNPE.sav.gz](https://github.com/MegaMek/megamek/files/424151/SharedUtility.doPSRCheckNPE.sav.gz)

**Comment by arlith** [comment]
This is actually an even bigger issue.  What's happening here is that, there's a `prevHex` variable which stores information about the previous step in movement.  This value is set when processing through the `MoveStep`s in a `MovePath`.  Initially, `prevHex` is set to null, until a step is processed, then `prevhex` is set to `curHex`.  The problem here is that, the bridge is backwards movement for the first step, and this causes a check to fire to see if the `prevHex` had bridge elevation, but it's null, so NPE.

The reason it's a bigger issue is that this means that any check that uses `prevHex` *never* considers the first position.  So, we have skids, sideslips, and backwards movement PSRs.  Really, `prevHex` needs to be inititalized to the `Hex` at `Entity.getPosition()`.  You can see this if you start a movement on pavement, make an immediate turn and then run forward.  This *should* cause a skid PSR, but doesn't.  Side-slipping is the same way.

The fix here is to initialize `prevHex` to the hex at the current position, but then this causes some issues later on, like in `Entity.checkSkid`, since it assumes that `prevHex == null => prevStep == null`, which will no longer be true.

I started on the fix, thinking it would be quick, but since it blew up, I ran out of time.

**Comment by arlith** [comment]
I fixed this in eed0266.  Turns out `Entity.checkSkid` was the only thing that needed to be updated, as side slips don't use `prevStep` nor does `Entity.checkReckless`.
