### ISSUE TITLE
Self Destructing VTOL Causes Unloadable Save

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megamek#320]
In the attached you will find a Save from 41.21. It is unloadable, with an error in what looks to me like reading a VTOL who is set to self destruct but has not yet done so.

It seems probable that this is related to https://github.com/MegaMek/megamek/issues/242
At least insofar as the same area of code is being used.

[SelfDestruct.zip](https://github.com/MegaMek/megamek/files/435252/SelfDestruct.zip)

**Comment by arlith** [comment]
You are loading a 41.21-git saved game using MM release 41.19.  This is not a supported operation.

**Comment by scJazz2** [comment]
It doesn't work in 41.21 either.

**Comment by arlith** [comment]
I can open the saved game just fine in v0.41.21.  The issue in your logfile is that there's a variable serialized in the savedgame that the MM doesn't know about (Entity.selfDestructedThisTurn), since, according to the log, you're using v0.41.19.  When I tried opening the saved game in v0.41.21, it works fine (as I would expect).
