### ISSUE TITLE
Shell scripts in .tar.gz releases should be executable and should have Unix/Linux-style line endings

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megamek#325]
startup.sh in megamek as shipped in the 0.41.22 tarball has Windows-style line-endings (CR/LF) and is not executable, requiring administrator intervention to run it on a Linux system.  Admittedly, this could be handled on the destination system.

If there's a release process, I would be happy to propose a patch to it.

**Comment by MGM175** [comment]
Well, essentially I'm using this to fix the problem:

`chmod -x "startup.sh" && dos2unix "startup.sh"`.
All while being within the catalog with the game.

PS: I didn't used linux for a while, so the syntax can be broken. More or less.

**Comment by mhjacks** [comment]
That technique works, of course.  (I'm doing something similar, but also creating a .desktop file for starting the UI).

I'm wondering how many Linux users of the program there are?  I could see writing something to install .desktop files (which would work for the major Linux desktop UI's).

**Comment by wildj79** [comment]
@mhjacks Honestly, there probably aren't that many of us.  The vast majority of users are most likely running MM on Windows.  Of course, @arlith or one of the other devs could probably confirm that.  Fixing this could also be helpful for those of us who use OS X as our main operating system and use the linux tarball to run MM (I've never had much luck running the native OS X version)

**Comment by arlith** [comment]
Back when we were on SF, we could get information about what OS and country people downloaded from.  Back when I looked at that info, it was largely windows, but the other OSes did get downloaded as well.  The US also held a majority, but there was a lot of other countries as well.

I personally use and develop in Linux.  The reason the scripts aren't better maintained is because I generally run from within Eclipse, other I just use `java -jar MegaMek.jar` to run, rather than using the shell script.  I plan to look into this, I've just been out of town for the last week.

**Comment by MGM175** [comment]
I'm using Linux build as well on Windows :stuck_out_tongue:

**Comment by Dylan-M** [comment]
This is actually an artifact from when the packaging scripts are run on Windows. Also, in order to preserve the execute bit on shell scripts (actually preserve all permissions), the tar-gz must be extracted with the -p flag to the tar command (tar -xvfp megamek.tar.gz). I've made some changes to the packaging scripts that should hopefully preserve the line endings in *nix format as well. Going to close this one as "solved".
