### ISSUE TITLE
Out of control ASF has the "launch" button available.

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#328]
Playing a game with Obvious, my Stuka went out of control and was looking through the buttons because I couldnt figure out why maneuvers wouldnt work (was on a space map) and the launch button was available but, craft was out in space not inside a dropship or on the ground obviously.

Player name: AFFS-FSAC-2REG-2BN-ECO
[launchbug.sav.gz](https://github.com/MegaMek/megamek/files/455756/launchbug.sav.gz)

**Comment by arlith** [comment]
The issue was that, when out of control, ASF would have all buttons enabled, but then a specific subset were enabled.  The launch button was one of them (because you can launch ships when out of control).  The problem one, it was being set to true, instead of being set to whether launching was available.  I just took the normal code to determine if launch should be enabled and applied that.
