### ISSUE TITLE
[0.49.6] Map design - no vehicle movement due to two level difference - 64x68 Diamond River

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/megamek#3353]
The upper right corner of the map 64x68 Diamond River cannot be entered by certain vehicles (although there are roads) because of a height / level difference of 2 at all possible pathways.

**Comment by HammerGS** [comment]
Screen shot of specific hexes, and saves per the text when you open a new issue.

For reference.
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
What version of MegaMek does your issue apply to?  Note whether it is the stand alone MegaMek or HQ's MegaMek.
What operating system are you using?  Windows, Mac, or Linux?
What java version are you using?  If unsure it will state your java version at the top of the megameklog.txt file.
(Delete the above lines)

### Description
Describe the issue and provide screenshots ingame if able.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the saved game if applicable.
(Delete the above lines)

### Files
Provide a saved game of when the issue was found.  If possible try to save the game during the phase before the issue occurs so the 
developers can step through the code and find exactly what it is that is breaking in the code.
Provide the megameklog.txt file for any NPE's or errors that MegaMek might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megameklog.txt file
And provide your playername so that they can load the saved game.
(Delete the above lines)

**Comment by SimonLandmine** [comment]
Map is \unofficial\VictorMorson\Diamond River.board

This isn't a bug as such, but a fault in the map's design. Most vehicles can't climb/descend a 2-level elevation change, and when Victor designed the map, they decided to run roads up 2-level elevation changes.
(They've also got buildings that cross elevation changes which, from memory, breaches BT building rules, although I can't recall the page ref.)
Example shot of map shown below.
I'm not sure if Victor Morson is still around to update the board, or whether it should be left with the design 'features' intact (or whether someone should add some interstitial hexes to smooth the gradients).

![image](https://user-images.githubusercontent.com/26851644/148660328-2d1d21bd-f57d-4180-a93b-ceaf49d34abd.png)

**Comment by HammerGS** [comment]
I haven't seen them around. My vote would be to either fix the map or remove it.

**Comment by SimonLandmine** [comment]
Me and my big mouth ... :D 
Let me know which you'd prefer, and I'll roll out my civil engineers if required.

**Comment by SimonLandmine** [comment]
Some quick fixes. Nothing major, just a couple of intermediate level hexes to ramp out of the pits and up the scarp.

[Diamond River II.zip](https://github.com/MegaMek/megamek/files/7834125/Diamond.River.II.zip)
