### ISSUE TITLE
Infantry missile damage still not being calculated /reported accurately?

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#336]
3.32, just got this report. I can get you a save game, but I'm using custom units in it, will you need the Mtf?

Weapons fire for Manticore Heavy Tank (Standard) #2 (Omega Vengeance)
    SRM 6 at Mechanized Hover Platoon (Laser) (Lyran Commonwealth); needs 6, rolls 10 :  - Direct Blow - 6 missile(s) hit 
hits  MEN
        **Missile weapon against infantry, damage reduced from 12 to 16**
        Infantry platoon caught in the open!!!  Damage doubled.
        Mechanized Hover Platoon (Laser) (Lyran Commonwealth) takes 32 damage to MEN.
             PLATOON KILLED,
*** Mechanized Hover Platoon (Laser) (Lyran Commonwealth) DESTROYED by damage! ***

    Medium Laser at Mechanized Hover Platoon (Laser) (Lyran Commonwealth); needs 6, rolls 7 : hits  MEN
        Direct fire weapon against infantry,  damage reduced from 5 to 2
        Mechanized Hover Platoon (Laser) (Lyran Commonwealth) takes 2 damage to MEN.

**Comment by arlith** [comment]
You don't need any additional data for MM saved games: all of the units are encoded in the saved game.  It's only for the MHQ cpnx files that you need additional data.

**Comment by VampireSeraphin** [comment]
[MissileOverkill.sav.gz](https://github.com/MegaMek/megamek/files/478950/MissileOverkill.sav.gz)

**Comment by arlith** [comment]
After looking at and fixing #354, I think this is actually correct and also the fix for that may make it more clear what's going on here.  Basically, direct blow is increasing the damage potential.  Missile weapons generally do max damage potential / 5, but in this case with your MOS from direct blow, an additional 1d6 is added on to that.  So, your original max potential damage is 2 * 6 = 12.  12 / 5 = 2.4 + 1d6.  If you rolled a 5, you could get 2.4 + 5 = 7.4, take the ceiling for 8.  Then, because it's mechanized, that damage is multiple by 2, leading to 16 damage.  So, it's perfectly possible to see that damage given your roll.
