### ISSUE TITLE
[49.6] & [0.49.7] [Bug] Docked unit display getting larger, no way to resize

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#3372]
MM 49.6 Standalone
Windows 10
Java 11

For some reason it appears that, on reloading a saved game, the docked unit display is now taking up about a third of the screen width, and there seems to be no way to change the width. When undocked, the unit display floats on top of any other window unless minimised, even when MM is not in focus. The MiniMap does not do this.

This could be resolved, as well as adding usability, by making it possible to change the width of the docked unit display.

[autosave_2022-01-14_03-59-51.sav.gz](https://github.com/MegaMek/megamek/files/7872336/autosave_2022-01-14_03-59-51.sav.gz)
 (Player name: Landmine, no custom units)

**Comment by SimonLandmine** [comment]
And here are some screenshots, for reference - as you can see, the docked unit display steadily expanded across the screen.

![20220119-UnitDisplayWidth1](https://user-images.githubusercontent.com/26851644/150208537-f5ba4fd9-263d-4789-ad24-520bef007db6.png)

![20220119-UnitDisplayWidth2](https://user-images.githubusercontent.com/26851644/150208556-ccc97d14-066a-4208-aa9b-cc8a8a8a6b36.png)

![20220119-UnitDisplayWidth3](https://user-images.githubusercontent.com/26851644/150208563-7c1d663e-7b4c-49dc-aab4-04fccf6e9922.png)

![20220119-UnitDisplayWidth4](https://user-images.githubusercontent.com/26851644/150208569-4775392a-0fca-4048-a384-2e496704666c.png)

**Comment by MarcJC** [comment]
As was discussed on the discord there is a workaround for this in 49.6 though it is only a temporary fix.  

Undock the unit display by pressing the D on the top right to undock the pane.  
Hide the unit display by going under view and selecting unit display (CRTL+ D should also work)  

Do this again to make the unit display visible  

Press the A on the top right to attach the pane.  
It should now be the appropriate size for the displayed unit.  

This bug seems to be an issue with various units causing the expansion, and it not shrinking afterwards until these steps are taken.   

In my current game the expansion is caused by selecting a Gunslinger Mech and will stay too large until I am on another unit and take the above steps to allow the pane to resize.

**Comment by MarcJC** [comment]
Last night when I was playing in .6 I think I was able to resize with just undocking and redocking the frame, but it was late and I'm not sure if I just don't remember hiding and unhiding the undocked frame.  

Maybe you don't need two of the steps, not sure

**Comment by SimonLandmine** [comment]
There's been an additional mention on the BT Forum regarding the 'always on top' undocked unit display issue.
[https://bg.battletech.com/forums/megamek-games/coming-soon-to-megamek/msg1815220/#msg1815220](url)

Suggested behaviour is to apply same 'on top' settings as the minimap when undocked, rather than global 'on top'.
