### ISSUE TITLE
Some physical phase options diabled/non functional or confusing to use.

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#352]
In testing sf bug https://sourceforge.net/p/megamek/bugs/3208/ 

During a test game I was not able to use a chainsaw to cut down a wooded hex. I was however able to use it in a physical attack against another mech. The dual saw also acted in this manner.

iNarc pods can be brushed off but are not targetable to do so. Also was unable to brush off the pod from the CT or at least was not able to enable the button to do so. As this falls under the punch attack table CT, R(L)T, and arms should be valid targets for a brush off. 

I looked around in the code but did not notice a section where a saw could cut down woods.

**Comment by arlith** [comment]
This ticket frustrates me.  You've opened a ticket to re-report an issue on SF.  Cutting down forests with chainsaws and dual saws don't work, but they work as physical weapons.  That's why there's a bug for it on SF.

iNARC may have an issue, but then you don't provide a saved game.  It sounds like you must have had a game, because you tested it.

**Comment by pheonixstorm** [comment]
The save game issue is my fault. I had one to attach but apparently forgot to. Will attempt to recreate the save and post one.

**Comment by neoancient** [comment]
Requested data not provided.
