### ISSUE TITLE
AC 2 Treated as Pulse Weapon Against Infantry

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#354]
>    AC/2 at Jump Support Infantry Star Corps Jump Assault Infantry (First Smithson's Chinese Bandits); needs 6, rolls 12 :  - Direct Blow - hits  MEN
        Pulse weapon against infantry, damage reduced from 3 to 3
        Pulse weapon against infantry, damage reduced from 3 to 3
        Infantry platoon caught in the open!!!  Damage doubled.
        Jump Support Infantry Star Corps Jump Assault Infantry (First Smithson's Chinese Bandits) takes 14 damage to MEN.
            7 men alive
>    AC/2 at Jump Support Infantry Star Corps Jump Assault Infantry (First Smithson's Chinese Bandits); needs 6, rolls 10 :  - Direct Blow - hits  MEN
        Ballistic cluster weapon against infantry,  damage reduced from 3 to 2
        Ballistic cluster weapon against infantry,  damage reduced from 3 to 2
        Infantry platoon caught in the open!!!  Damage doubled.
        Jump Support Infantry Star Corps Jump Assault Infantry (First Smithson's Chinese Bandits) takes 10 damage to MEN.
             PLATOON KILLED,
*** Jump Support Infantry Star Corps Jump Assault Infantry (First Smithson's Chinese Bandits) DESTROYED by damage! ***

I got this report from MM recently when I attacked an infantry platoon with AC2s in Rapid Fire mode from a Jagermech, while using increased the IS AC Damage option. I'm not sure why it reported back as a pulse weapon.

I don't have a save game unfortunately. I don't think I had paranoid autosave turned on.

**Comment by pheonixstorm** [comment]
Easy to reproduce. Will try to get a game save up later.

**Comment by VampireSeraphin** [comment]
[AC2infantry.sav.gz](https://github.com/MegaMek/megamek/files/518670/AC2infantry.sav.gz)
[InfantryReports2.sav.gz](https://github.com/MegaMek/megamek/files/518671/InfantryReports2.sav.gz)

**Comment by arlith** [comment]
So, turns out that I think things are working as intended here.  This is because of direct blows (which makes it *not* something that's all that easy to reproduce).  TO pg 81, under the **Direct Blows** section:

>**Conventional Infantry**: For every MoS of 3, treat a direct
blow weapon attack from a non-infantry unit against con-
ventional infantry as the next row down on the Non-Infantry
Weapon Damage Against Infantry Table (see p. 216, TW); in the
case of burst-fi re weapons, apply an additional 1D6. For each
row “above” Cluster (Missile), roll 1D6 and add that number of
troopers eliminated. For example, an LRM 20 direct blow with
a MoS of 6 would fi rst determine its standard damage (20 / 5 =
4) and then would roll 2D6 (1D6 for each 3 MoS “above” Cluster
(Missile)) and apply that die roll result to the 4 to determine
the total number of eliminated troopers.

And that's what is happening in the code: the MOS is getting added into the damageType, which has the effect of making the damage type more effective.  So, really the issue here is one of reporting.  I was unaware of this when I added these reports, and I missed the code that adjusted the damageType (I should've caught that).  I'll adjust the code to report this better.

**Comment by VampireSeraphin** [comment]
Well thats byzantine as hell. You just going to change the report to "direct blow deals bonus damage" ?

**Comment by arlith** [comment]
It's actually super simple to implement in the code, ironically (it was just one line in the method, which is why I missed it).

My initial thoughts is to add an additional message type that will say something like
> Direct Fire Ballistic (treated as Pulse due to MOS) against infantry, damage reduced from 3 to 3

But, I also think there may be another bug...
Seeing a report such as this:

>    AC/2 at Motorized Heavy Infantry Motstand/Mimir Troop (Epsilon Eridani Sarna March Militia); needs 4, rolls 10 :  - Direct Blow - hits  MEN
>        Pulse weapon against infantry, damage reduced from 3 to 3
>        Pulse weapon against infantry, damage reduced from 3 to 3
>        Infantry platoon caught in the open!!!  Damage doubled.
>        Motorized Heavy Infantry Motstand/Mimir Troop (Epsilon Eridani Sarna March Militia) takes 14 damage to MEN.
            6 men alive

I would expect the damage to be 12 (3 * 2 + 3 * 2) instead of 14.  I think that it's *also* applying a +2 damage from direct blow, which is wrong...

**Comment by arlith** [comment]
Alright, think I've worked out the damage from ultra/rapid fire ACs against infantry.
Originally what was happening is that it would compute the damage to infantry for each shot, factoring in direct hit (this is why you'd see the damage reduction report twice), add these up, and then add 1 damage because it was considered a ballistic cluster attack.

Ultra and rapid-fire ACs are treated as cluster weapons, and according to TW pg 215 indicates that cluster weapons should always use their maximum potential damage when determining damage against an infantry unit.

The way  the code was written would give the correct result when direct blow wasn't considered, but I've rewritten it now to compute the maximum potential damage, and then use that to call `Compute.directBlowInfantryDamage`, so now the damage dealt should also be correct during a direct blow.  It also now only reports once.

Here's a screenshot:
![screenshot at 2016-10-24 21-41-31](https://cloud.githubusercontent.com/assets/13815237/19671198/a7d3e2e2-9a32-11e6-9822-6c5c59abdf92.png)
