### ISSUE TITLE
Hull down 'mech 1 level higher than target uses kick table to punch

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#360]
I had a _Wasp_ which went hull down (due to a failed PSR) in a hex 1 level higher than the _Marauder_ in front of it.  During the physical attack phase, the _Wasp_ was able to punch the _Marauder_ using the kick location table.  Based on my knowledge of the rules, that doesn't make sense.

[savegame.sav.gz](https://github.com/MegaMek/megamek/files/521610/savegame.sav.gz)

**Comment by BLOODWOLF333** [comment]
@obvious and I experience this as well two days ago.  I had a warhammer hulldown in a level 1 hex with an enemy stalker adjacent and in a level 0 hex, punched the stalker and it used the kick table.  I forgot to report this and saved the game after seeing the physical report so, might not be helpful.

**Comment by Dylan-M** [comment]
I'm going to guess that someone accidentally reversed the elevations.

**Comment by ObviousTech** [comment]
Megamek appears to implement the rules as written.  When the a hull down unit punches, its attacks are resolved against the Kick Table.  Elevation differences do not appear to be taken into account as written.  

Megamek detects that the punch attack is possible because the elevation of the punch is at its foot level.  
Then following the rules as written, it uses the Kick Table.

Asked about it in BT rules forum: http://bg.battletech.com/forums/index.php?topic=55297.0
There's really 2 options that seem to make the most sense:
-Consider punching while hull down to be equivalent of "Kick" for the purposes of the Different Levels Table.
-You can't punch a unit a level below.  Hull down doesn't matter.

**Comment by arlith** [comment]
Going to mark this as pending until the rules clarification is answered.

**Comment by HammerGS** [comment]
Ruling is in here - 
http://bg.battletech.com/forums/index.php?topic=55297.0

_"If a hull-down unit punches a unit one level lower than it, treat the attack as a kick for the purposes of determining hit location."_

**Comment by pheonixstorm** [comment]
Which would mean use the punch table if I am reading the answer correctly

**Comment by arlith** [comment]
Seems like this came from someone implementing the rules as written.  Punches from hull-down units ignored elevation and always used the kick table.  I changed it so that if the target has a lower elevation, then punch table is used, else kick table.
