### ISSUE TITLE
Building Fires Not Shown On Minimap

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#367]
Woods fires all show up as red little hexes on the minimap but, building fires are not shown (drawing order maybe).

![example](https://cloud.githubusercontent.com/assets/16950832/19418227/5981b5be-9385-11e6-931c-ba20470315c0.png)

Player name: BLOODWOLF
[multibug.sav.gz](https://github.com/MegaMek/megamek/files/531879/multibug.sav.gz)

**Comment by arlith** [comment]
The source of his bug is in `MiniMap.terrainColor`.  This method is used to determine what color to use to draw a hex in the minimap.  Basically the way it works is that `MiniMap.m_terrainColors` is an array that stores a `Color` for each terrain type (defined in `Terrains`).  It starts at the highest terrain type and loops through until it finds a terrain type that exists in the current hex, then it uses that terrain type to determine the color for the hex and breaks.  Basically what this means is that higher valued terrain types (because the loop starts at the end and works down) take precedence over lower valued terrain types.  Because of this, there's a special case for smoke & fire.  Since `Terrains.    public static final int BUILDING` (22) is higher than `Terrains.FIRE` (19), the building color takes precendence.  Any of these terrain types after fire will take precedence over fire, and the fire color won't be drawn.

Probably the simplest way to deal with this would be to make the `FIRE` terrain take precedence over everything.  I think I'm going to leave this open for discussion before actually implementing a fix.

**Comment by BLOODWOLF333** [comment]
I think fire should take precedence over everything and that the minimap should mirror the drawing order of terrain on the board.

**Comment by arlith** [comment]
For now, I made it so smoke & fire takes precedence over everything, fire takes next precedence, and after that it's colored by the highest terrain value.  I think we should probably revisit how this gets colored, but at least for now, fire will always be indicated.
