### ISSUE TITLE
Duplicate Messages When Changing Sensors

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#368]
When changing a mech's sensors from radar to say magscan MM reports the change twice (maybe because there are two sensor critical locations as Ral suggested).

![example](https://cloud.githubusercontent.com/assets/16950832/19418240/ae240734-9385-11e6-839a-0e6cdd141729.png)

Player name: BLOOODWOLF
[multibug.sav.gz](https://github.com/MegaMek/megamek/files/531883/multibug.sav.gz)

**Comment by arlith** [comment]
The issue here was in `ExtraPanel.itemStateChanged`.  A `JComboBox` will issue two `ItemEvent`s when a new selection is made: the first one indicates that the old item is deselected, and the second event indicates that the new item was selected.  Both of these would fire the code to handle a new sensor change, but only one needed to take effect.  I added some code  that makes it so `ExtraPanel.itemStateChanged` only acts on `ItemEvent.SELECTED` events.
