### ISSUE TITLE
41.25 : UI bug on left side of the screen, unit window/move button keeps appearing there

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#380]
I just updated and i noticed that there is now a UI bug where the unit window and move button will sometimes appear on the left side of the screen. Random copies of the UI will also appear there (copies of the chat window, other buttons, etc). This didn't happen in a previous version (not sure which, i haven't updated in a long time).

Clicking a unit in the unit list on the right side of the screen is enough to get the UI bits to appear on the left.

![megamek](https://cloud.githubusercontent.com/assets/1191378/19617141/7d2cfb60-9874-11e6-94fa-3796039b534c.jpg)

[mekhqlog.txt](https://github.com/MegaMek/megamek/files/545617/mekhqlog.txt)

[#battletech.sav.gz](https://github.com/MegaMek/megamek/files/545616/battletech.sav.gz)

**Comment by arlith** [comment]
Does this happen with any other skins besides plain?  I suspect it may only happen with the plain skin.

**Comment by Question2** [comment]
I tested it with the default skin and the problem didnt occur with it.

**Comment by arlith** [comment]
I believe this issue may have been introduced in 5055ff35, or possibly it's been around for longer.  Essentially, the problem is that when there's no background image specified, then nothing gets painted.  This looks like it works, but when something dirties a specific area, it may not get updated properly.  I fixed this in c78135a by adding some code that fills the current dirtied area with a default color.  I chose the `DefaultMetalTheme` secondary 3 color.  This is similar to the color that was used before, but was is slightly darker.
