### ISSUE TITLE
Freeze When Zooming Out With LargeTexture.tileset

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#385]
Found this when tinkering with the largetexture.tileset (the new one), when zooming out one "increment" past the point where the board pretty much fits in it entirety on my window already causes the program to freeze and throw 400kb of NPEs in the log. 
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Width (-1) and height (-1) cannot be <= 0
    at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)

Player Name: BLOODWOLF
[zoombug.zip](https://github.com/MegaMek/megamek/files/549533/zoombug.zip)

**Comment by BLOODWOLF333** [comment]
Does this with the 800x600 space image as well, zooming back in causes the board to redraw and returns playability.

**Comment by arlith** [comment]
The problem here was that the `ImageUtil.getScaledImage` wasn't waiting for the `ImageProducer` for the scaling to finish producing the image until requesting an accelerated image with `ImageUtil.createAcceleratedImage`.  I guess in most cases the scaling was fast enough to finish before the resulting image was used, but in the case of the large texture dataset at the more zoomed out levels the scaling took just long enough to cause an issue.

We have some in `ImageUtil` already to wait until the images are loaded before using them.  Since this exact same code (more or less) is now used in several places, I pulled it out into a static method and used that to wait.  This fixes the issue, but I did notice a brief flash.  This is because the images don't scale in time to re-rendering fast enough.
