### ISSUE TITLE
[0.41.25 : Bug] Auto Elevation Change and Visual Issue

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#386]
Tested with a fresh install.

1. Add Cavalry Attack Helicopter (Standard)
2. Configure Start Height = 1
3. Select Moonless Night
4. Start Game

During deployment, after picking a level 0 hex for deployment, unit shown as elevation 1. 

During round 1, same unit suddenly went to elevation 2. Current Sensor and Max is blank. From graphics, the visual became unlimited (or very long range).

Tried with dawn/dusk and fullmoon night, current sensor and max visual range still blank.

Savegame attached.

[round1.sav.gz](https://github.com/MegaMek/megamek/files/561401/round1.sav.gz)
[deployment.sav.gz](https://github.com/MegaMek/megamek/files/561400/deployment.sav.gz)

Edit: Tested using 0.41.24, visual was working normally. But the elevation change still persist.

**Comment by arlith** [comment]
So, the "visual" issue isn't really a bug,  In your saved game, you don't have double blind on.  Without double blind on, the current sensor and max visual range don't matter, so they can be ignored.  That's why they aren't displaying for you.

As for the elevation, I've pushed a fix for that.  It's still kind of a band-aid for now, until we allow VTOL elevation to be set during deployment.
