### ISSUE TITLE
ASF Visibility

### ISSUE THREAD

**Issue by jayof9s** [MegaMek/megamek#387]
In instances with limited visibility (darkness, rain, etc.) ASF visibility is incorrect. They currently cannot target enemies they flew over during the round if they end up too far away from them.

**Comment by VampireSeraphin** [comment]
Unless they have a searchlight.

I've had this problem as well in night missions. Can't target a non illuminated unit.

**Comment by mkerensky** [comment]
I also run into this a lot. I've previously suggested that Aero units get assigned a sensor suite. They all obviously have one, and given the requirements of space combat it's probably much superior to what most ground units have (though perhaps NOT as good at clutter suppression for things like trees and buildings), but yet aeros got left off the sensor tables in TacOps.

**Comment by jayof9s** [comment]
The problem is it doesn't matter where an ASF ends up. They aren't shooting from their final position, they're shooting from where they moved during the round. So if they fly directly over a target, the target is in LOS regardless of conditions. It doesn't matter that they end up 60 hexes away.

It's currently just not functioning correctly.

**Comment by arlith** [comment]
Yea, it's probably a simple bug to fix.  Basically, when computing visibilities it's using the ASF's current hex, and not the hex it would attack from.  Probably, we just need to add an exception for ASF's in the code that's computing visibility.  I think there a lot of minor bugs like this around air-to-ground attacks, because the ASF isn't attacking from `Entity.getPosition`, but virtually all of the code uses `Entity.getPosition` unless specific exceptions have been considered and added...

**Comment by VampireSeraphin** [comment]
I'd believe that. I find new and interesting problems with fighters almost every time.

**Comment by arlith** [comment]
It's not clear to me how this should work in the rules.  It doesn't seem like the visual spotting rules in TO cover how ASF on ground maps work.  I've reached out to Xotl on this issue.  Until I get a response, I'm going to mark this as pending.

**Comment by pheonixstorm** [comment]
has anyone tested this in reverse? How do ground units act when trying to attack asf during these conditions?

**Comment by VampireSeraphin** [comment]
IIRC, from the last time I played this kind of mission, you need to hit the
fighters with your spot light to attack them.

**Comment by pheonixstorm** [comment]
How do the rules say to handle attacks against ASF in the dark, illuminate to attack or are they visible if their flight path is within visual range.

**Comment by arlith** [comment]
The rules don't say, from what I can see.  That's the problem.  There's nothing that indicates to me how this should be handled.

**Comment by mkerensky** [comment]
I'm playing a current game with ASFs in Dusk/Lt Fog/Lt Rain under 0.41.26.  Ground units seem to be able to attack the ASF's on the map normally, firing at their hex of closest approach.  LOS/Sensor mapping is a bit weird. I had a couple of instances where an ASF well within the 15 hex visibility range, including altitude, was not revealed properly and remained a sensor contact.   ASFs trying to attack each other are unable to at ranges greater than about 16 hexes - (1) on the ASF data sheet - even though they have a max visual range set to 30 hexes. ASFs are also unable to attack ground targets they fly over if they get further away than 30 hexes during their movement, but I think we've already covered that in this thread.
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/613971/autosave.sav.gz)

Start the attached save as 337th if you'd like to try it out.

**Comment by arlith** [comment]
Thanks for the save, it'll probably be helpful when we hear back on the rules.

I'm pretty sure what's happening is that for purposes of visibility, it's being calculated from the end of the flight path for all purposes of visual spotting and sensor detection.  I suspect that explains all of the strange behavior.  I suspect instead of the current Entity position, we need to consider all positions along the flight path.  However, I can't find anything in the rules that explicitly states this to be the case, hence why I've contacted Xotl.

**Comment by Dylan-M** [comment]
@arlith If you haven't heard back from Xotl, can you switch the milestone on this to the next dev?

**Comment by arlith** [comment]
This is the errata that was added to address this:

First, TacOps page 221, add the following section:

Airborne Units:
Against other airborne units, use the visible range table as usual. However, against ground units, the airborne unit is only able to visually spot units along its flight path and must be at or below Altitude 8.

TacOps page 222, replace the "Airborne Units" section:

Replace this paragraph:

Airborne Units:
Sensor ranges for airborne units do not change, though LOS exists to all units on the playing area. If using a High-Altitude Map,
airborne unit must be in the Ground Hex Row to make a sensor detection roll. If using a Low-Altitude Map, an airborne unit cannot be at Altitude 10; it must be at Altitudes 1 –9 to make a sensor detection roll. In both instances, the airborne unit is considered to be in Hex 0909 of the ground mapsheet corresponding to the hex occupied by the unit

With:

Airborne Units:
Sensor ranges are considerably curtailed for airborne units. As with visual spotting, airborne units must be at or below Altitude 8 in order to make a sensor roll. Short range indicates that any unit within 1 hex of the flight path is detected, medium range is any unit 2 hexes away from the flight path and long range is any unit 3 hexes away. Any active probes increase this range to 1-2 for short, 3-4 for medium, and 5-6 for long.
