### ISSUE TITLE
Auto-ejection engage for a mech with CASE

### ISSUE THREAD

**Issue by Dermenore** [MegaMek/megamek#3926]
### Environment
I use the 0.49.10 MegaMek version in Window 10 with Java 11.

### Description
One of my mechs with CASE installed suffered an explosion of ammunition. Despite the CASE contending the explosion, the auto-ejection was engaged. That means that mechs with CASE, who should have still been able to continue the combat after an ammo explosion could be disabled because of the auto-ejection.
![Capture](https://user-images.githubusercontent.com/113073300/194762593-b353886d-3d51-4383-ae47-9b218b3a6406.PNG)
![Capture 2](https://user-images.githubusercontent.com/113073300/194762595-62e74301-24bd-45f5-9f07-771d456d39a7.PNG)

### Files
My player name is "Les Lames Jurées".

[Before.sav.gz](https://github.com/MegaMek
[mekhq.log](https://github.com/MegaMek/megamek/files/9741793/mekhq.log)
[megamek.log](https://github.com/MegaMek/megamek/files/9741794/megamek.log)
/megamek/files/9741792/Before.sav.gz)
[Autosave-1-Les Lames Jurées-30650124.cpnx.gz](https://github.com/MegaMek/megamek/files/9741796/Autosave-1-Les.Lames.Jurees-30650124.cpnx.gz)
[customs.zip](https://github.com/MegaMek/megamek/files/9741797/customs.zip)

**Comment by binaryspica** [comment]
Did you check the 'Disable Automatic ejection?' option of that unit on the lobby? For now it is always turned off whatever the unit has CASE/CASE II or not, so you need to check it manually one by one. I have seen an ASF hit the eject button after only had an ammunition explosion despite of its CASE II, and I found it later that it was always unchecked by default.

**Comment by Dermenore** [comment]
No I didn't check it at that time.

**Comment by binaryspica** [comment]
Then it can be the reason. Will the pilot of the said mech still ejects when you check it and suffer an ammunition hit?

**Comment by gsparks3** [comment]
Okay, think I I have traced down the immediate cause of this; the cause for the underlying change I am less certain about and may need to be looked into.

Megamek has a Game Option, "Conditional Autoejection", that is off by default.

In version 0.48, a Clan mech with ammo (and therefore CASE) loaded into the lobby with this setting inactive will have automatic ejection disabled by default, as shown below.
![image](https://user-images.githubusercontent.com/59574316/198151244-916cf33c-a1e0-4a22-be6e-94de13f39b38.png)
In both 0.48 and 0.49.10, if Conditional Autoejection is active, a Clan mech with ammo will have ammo-explosion ejection disabled, but the other options enabled (and "disable automatic ejection" inactive), as shown below.
![image](https://user-images.githubusercontent.com/59574316/198151401-ebd62953-19c5-47b3-ab50-322582808223.png)
However, _**in version 49.10**_, if Conditional Autoejection is _**inactive**_, automatic ejection will _**not**_ be disabled, as shown below. This is very likely the cause of the issue reported above.
![image](https://user-images.githubusercontent.com/59574316/198151591-85424a60-8fd5-4333-bc49-b953d994095c.png)

I am uncertain why this change occurred, and it should probably be adjusted so that it behaves as it did previously. In the meantime, activating the "Conditional Autoejection" Game Option should function as a workaround.

**Comment by Dermenore** [comment]
> Okay, think I I have traced down the immediate cause of this; the cause for the underlying change I am less certain about and may need to be looked into.
> 
> Megamek has a Game Option, "Conditional Autoejection", that is off by default.
> 
> In version 0.48, a Clan mech with ammo (and therefore CASE) loaded into the lobby with this setting inactive will have automatic ejection disabled by default, as shown below. ![image](https://user-images.githubusercontent.com/59574316/198151244-916cf33c-a1e0-4a22-be6e-94de13f39b38.png) In both 0.48 and 0.49.10, if Conditional Autoejection is active, a Clan mech with ammo will have ammo-explosion ejection disabled, but the other options enabled (and "disable automatic ejection" inactive), as shown below. ![image](https://user-images.githubusercontent.com/59574316/198151401-ebd62953-19c5-47b3-ab50-322582808223.png) However, _**in version 49.10**_, if Conditional Autoejection is _**inactive**_, automatic ejection will _**not**_ be disabled, as shown below. This is very likely the cause of the issue reported above. ![image](https://user-images.githubusercontent.com/59574316/198151591-85424a60-8fd5-4333-bc49-b953d994095c.png)
> 
> I am uncertain why this change occurred, and it should probably be adjusted so that it behaves as it did previously. In the meantime, activating the "Conditional Autoejection" Game Option should function as a workaround.

Thanks for your research. I will use this option. It's appreciable to not have to worry about mechs becoming disabled by a too-quick ejection.
