### ISSUE TITLE
Hidden Units: no breach detection during phase unit activates

### ISSUE THREAD

**Issue by ObviousTech** [MegaMek/megamek#394]
This was detected multiple times in 0.41.22, but it is likely still applicable in the current version as there is no mention of hidden units since that version.

Atmosphere: Trace.  (Probably also happens in vacuum, water.)
A hidden unit activates during the firing phase.  
When the unit takes damage, it should roll for a breach check.  Also, if its internal structure is exposed, that section should be breached.  Neither of these things happen.

It doesn't matter whether due to point blank shooting or if set to activate in a previous phase, same issue.  Attached save contains example of unit activating at the start of the firing phase.  I have a log from a different game of the issue occurring after being spotted while point blanking, if needed.

In later rounds, breaches do properly get detected when the section takes damage.

[UnevenBreaches.sav.gz](https://github.com/MegaMek/megamek/files/573552/UnevenBreaches.sav.gz)

**Comment by arlith** [comment]
Ultimately, the issue here is how `Server.doSetLocationsExposure` is called.  MM tracks the "exposure" for each location of the unit, which is generally `NORMAL`, `WET`, or `VACUUM`.  When damage is taken, it considers the exposure of the location to determine if a breach check recquired.

Right now, exposure is set during movement.  Everytime a unit moves, its exposure is updated.  The problem is, hidden units don't move, so the exposure never gets set.

Ultimate, the issue here is that `Server.doSetLocationExposure` needs to be called on deployment.  This is also important for a rare situation where a unit with damaged armor is deployed into water.  This should cause a breach check and right now it won't until the unit moves.

To fix this, I added a call to `Server.doSetLocationsExposure` at the end of `Server.processDeployment`.
