### ISSUE TITLE
Disallow simultaneous enabling of Lance Movement and Individual Initiative

### ISSUE THREAD

**Issue by ObviousTech** [MegaMek/megamek#4]
Having the "Individual Initiative" and "[unit type] Lance Movement" enabled at the same time leads to a game-corrupting error.

Multiple units move on the first of those units' initiative.  When one of the units that has already moved gets its turn in the initiative order, you get an error saying that the current player has no units to move.

MegaMek should not allow both of these options to be enabled at the same time.  Maybe gray out/disable one or the other when the other one is toggled on.

**Comment by arlith** [comment]
Fixed in e213797.  The two lance movement options will be disabled when individual init is selected, similar to how all of the inf/proto move even/multi options. 

Inadvertently, when I was fixing this I found that the inf/proto move even/multi options would be disabled when individual init is clicked, but if individual init is on when the dialog is created, those options won't be disabled.  I fixed this, otherwise players could potentially turn on conflicting options.
