### ISSUE TITLE
Locust Fires Both Arms from Prone

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#404]
[ArmsGunsFromProne.sav.gz](https://github.com/MegaMek/megamek/files/582270/ArmsGunsFromProne.sav.gz)

In this game I had a locust that was allowed to fire with both arms while prone. I think it might be related to the no/minimal arms quirk I had enabled.

**Comment by arlith** [comment]
Your saved game would be far more useful if it was saved prior to the prone locust taking its shot.

**Comment by arlith** [comment]
Sometimes, additional details are helpful.  This is because you are targeting and adjacent building, and it would appear there's an error in the logic that implements the "targeting ah adjacent building is an automatic hit" rule.

**Comment by arlith** [comment]
Alright, the issue here ultimately comes down to `WeaponAttackAction.toHit`.  There are three pertinent components:

- early on a call to `WeaponAttackAction.toHitIsImpossible` is made, and if the shot is impossible `toHit` returns early
- Down a ways, there is a check for some automatic successes on buildings, which will cause `toHit` to return early
- After the building checks, `Compute.getProneMods` is called to add modifiers for being prone.

This led to a situation where the prone modifiers were never considered in `toHitIsImpossible`, so that `toHit` wouldn't return early before the building checks were made, but the building checks never consider other things that could make the shot impossible, like prone modifiers.

What I did is added a check in `WeaponAttackAction.toHitIsImpossible` to check the prone modifiers, and if they make the shot impossible, it returns that reason.  This now means that shots that are impossible due ot prone modifiers, will cause `toHit` to return immediately.
