### ISSUE TITLE
Sand Still Applies +1 To PSR When On Road

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#410]
In the saved game run the grasshopper forward then turn left down the road and the PSR will be 2 for running and turning on pavement +1 for sand under the road.  Unit begins and ends movement on the road and should be considered "on the road" according to TW pg.32.
Related to #295 

Player Name: AFFS-FSAC-2REG-2BN-ECO
[PSRsandonroad.sav.gz](https://github.com/MegaMek/megamek/files/586995/PSRsandonroad.sav.gz)

**Comment by arlith** [comment]
Clearly this is representing the assholes who can't keep it in their lane when taking a turn and kick up the sand from the shoulder into the road.  Seems like WAD to me.  /s

**Comment by arlith** [comment]
So, the rules aren't 100% clear to me on this, but it seems to make sense that, if you are moving along a road, then the underlying terrain modifiers shouldn't apply.  So, I added a condition that reflects that in `Entity.checkSkid`.  If the previous and current hexes contain pavement, then you are considered to have moved along a road for the purposes of the skid PSR, and terrain modifiers don't apply.  Otherwise, they do apply.
