### ISSUE TITLE
Map Editior allows "Woods:0"

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#411]
I've discovered that the map "Jakes Wide Blue River1" a 35x35 map, is using woods:0 which seems to be an illegal terrain type that is only partly implemented.

It blocks hover vees, but does not cost extra for mechs to cross. 

MM should reject maps with illegal terrain types, or the map editor should not allow them to be saved.

**Comment by arlith** [comment]
A what to compute whether a board is valid has been added, and additionally an application has been added that will validate all of the boards in the release and log the boards that fail validation and why.

The board editor does need a usability enhancements in order to prevent creating invalid combinations, but at least the current board validation helps.  Additionally, we'll be fixing the errors revealed by BoardValidator and fixing those.  I'm going to consider this ticket closed.
