### ISSUE TITLE
Map Editor should use dropdown menus instead of text fields

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#412]
After discovering that MM allows illegal hex types to be built and added I think the map editor should be changed. Presently, when a hex is specified in the hex fields it is done by entering a numerical value. This can be any value, & the editor does not show if there are any limits.

Instead, the editor should use a drop down that only shows legal values for the type of hex entered (except elevation+depth, which can remain unlimited). 

Eg, if the terrain selected is woods, the drop down only shows options 1, 2, & 3 for light, medium, and heavy.

This could possibly include a sub menu for terrain types that use multiple random images like rubble.

**Comment by SJuliez** [comment]
I believe that with the new GUI this issue is now outdated. The buttons restrict values as much as possible (woods, mud etc.). Changing woods to "4" immediately shows the INVALID label. With other terrain options such as fluff there is no correct setting as this depends on the tileset. 

Therefore unless someone stops me I will close this issue.

**Comment by Windchild292** [comment]
I concur
