### ISSUE TITLE
[0.41.26 Bug] Capital Squadrons cause game to hang

### ISSUE THREAD

**Issue by guybtg** [MegaMek/megamek#423]
Tested this out on a 41.23 build that I had, couldn't replicate it there. Grouping ASF into squadrons on a space map causes the armor tab in the unit panel to be a gray box, as well as causing the game to hang after declaring weapons fire.

[asfsquadron.sav.gz](https://github.com/MegaMek/megamek/files/606185/asfsquadron.sav.gz)

**Comment by arlith** [comment]
This issue was introduced in 16d904.  How the sub entities in the squadron was retrieved got changed.  It was then iterating over a `max_size` value set in the `SquadronMapSet`.  If the squadron was full, the `max_size` value was greater than the number of fighters, which caused an exception.  I fixed it so it now iterates over the min of the number of fighters or `max_size`.
