### ISSUE TITLE
New Drop Down Option: Display acitve weather conditions and game effects

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#426]
Please add a new menu similar to "show round report" that displays active weather conditions and their in-game effects. This will be especially pressing as Phoenix finishes up his weather rework.

**Comment by HammerGS** [comment]
I would recommend @pheonixstorm look into this as part of his weather project stuff.

**Comment by pheonixstorm** [comment]
I think I can add that in. Best to have @arlith decide on how best to do this though. I can see it done with the round report or as a separate weather dialog. I had planned on looking into adding the temperature to the round report already as it is not displayed and has a greater impact on the game in extreme cases.

Once I get a little guidance from arlith on how best to implement this I will get it added (I hope, still a bit confudled about how to build extra bits into the round reports)

**Comment by VampireSeraphin** [comment]
I'd prefer to see it as a separate drop down, which you can fill with temperature, visibility, planetary conditions like gravity, and the current weather + the values of the weather modifiers. This would keep the round report from getting more cluttered and make it easier to upgrade later if need be.

**Comment by arlith** [comment]
The round reports are all created in server, having creating new `Report` objects and adding them to the current `Vector<Report>`.  Can't you already see most of the weather conditions from the init report, which you can go back and view with the round report menu?

Regardless, you could potentially do something like the player list, where there's a menu option that pops up a small dialog.  I'm not a big fan of the player this though.  Can't really think of much else.  I feel like a complete report in the init phase is probably sufficient.  Otherwise, there's not much of a great way to communicate info outside of tooltips and the unitDisplay, unless you add a new dialog.

**Comment by kuronekochomusuke** [comment]
implemented in #3969
