### ISSUE TITLE
Improper movement in snow?

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#428]
I'm not sure if this is working as designed, or a bug.

Tanks in heavy/moderate snow weather that have their MP reduced to 0 by snow are not granted 1st move amnesty. I talked with Hammer about this and it might be a bug.

hammer [2:06 PM]  
unit can always move into the hex directly in
front of it, regardless of the terrain cost, provided such movement
is the only MP expenditure the unit makes in that turn
(i.e. the unit cannot make any facing changes in the same turn
it uses the Minimum Movement rule). The controlling player
can only make this kind of move if the unit has at least 1 MP to
spend (meaning it is mobile) and is not prohibited from entering
that terrain (see Level Change, p. 48); all units reduced
to 1 MP either due to heat or damage can still make use of
the minimum movement rule.

[2:07]  
TW pg 49

To me that sounds like the snow should be increasing the MP cost of the hex, but MM appears to deduct the snow penalty directly from the unit, rendering it unable to move, or even turn. I've attached a save game where I had some mobile long toms reduced to 0mps by heavy snow.

The player name is The Infamous Dust, and this save is before I've moved any units. 

[SnowBlocksMovement.sav.gz](https://github.com/MegaMek/megamek/files/615346/SnowBlocksMovement.sav.gz)

**Comment by pheonixstorm** [comment]
Thin snow adds a cost of +1 per hex for wheeled units while deep snow adds a cost of +1 per hex for all units. Temperatures of below -30 affect the units move. A temp of -40 will subtract 1 from the cruising speed of all vehicles. So a Vedette will go from 5/8 to a 4/6.

In the game you provided there is no snow yet. For heavy snowfall it takes 5 turns to build up to thin snow and an additional 10 turns (15 total) for deep snow.

p60 TO says that heavy snowfall includes the effects of -50 temps which would only remove 2 from the vehicle MP. The code as currently written is calculating the heavy snowfall penalty at -3 which is incorrect on two fronts. First, heavy snowfall itself isn't where the penalty is coming from, rather it should be calculated based on the temperature of -50. The other is reductions due to extreme winds such as storm and tornados.

As for the minimum movement rule... that will need to be asked on the rules forum.

**Comment by pheonixstorm** [comment]
@HammerGS this can be closed
