### ISSUE TITLE
Smoke Artillery working improperly

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#430]
[Bug Saves.zip](https://github.com/MegaMek/megamek/files/617962/Bug.Saves.zip)

The smoke long tom rounds landed on target, the round report correctly listed the hexes that should be filled, but the smoke neither displayed properly nor showed up in the tool tip.

One of these saves should be the phase before it lands, though I'm not sure which one.

**Comment by arlith** [comment]
Looks like this is an issue with the fix for #245.  `SmokeClouds`s get added properly, and then code was added to update the terrain types for the `Hex`s involved, however when iterating over the adjacent hexes, there was some copy/pasted code and, while it reports the correct hex, it's actually update the center hex.  In effect, the center hex has heavy smoke added 7 times, instead of once and once for each adjacent hex.
