### ISSUE TITLE
Wrecks cause holes in alternate tileset themes

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#434]
Like this, with the mars theme on large textures.

![image](https://cloud.githubusercontent.com/assets/19868605/21043474/0c15960a-bdc5-11e6-9a68-b3d18030ea33.png)

**Comment by VampireSeraphin** [comment]
Smoke also does it.

![image](https://cloud.githubusercontent.com/assets/19868605/21043746/6e8b3c8a-bdc6-11e6-9644-563776867dce.png)

**Comment by VampireSeraphin** [comment]
Also apparently engine explosions. 

![image](https://cloud.githubusercontent.com/assets/19868605/21044109/437a004c-bdc8-11e6-8931-3bee1cdb49d2.png)

[autosave_2016-12-09_03-46-49.sav.gz](https://github.com/MegaMek/megamek/files/641694/autosave_2016-12-09_03-46-49.sav.gz)

**Comment by BLOODWOLF333** [comment]
......Thats the No Theme base plains terrain showing up.  What the hell?

**Comment by VampireSeraphin** [comment]
*headdesk*

[autosave_2016-12-09_04-40-42.sav.gz](https://github.com/MegaMek/megamek/files/643564/autosave_2016-12-09_04-40-42.sav.gz)

Interestingly, MM does not appear to save which tile set theme you were using, and when you turn it back on in a save game, it reverts the holes caused by the engine explosion.

**Comment by arlith** [comment]
So, when I load up that saved game, everything uses the no theme plains.  Did you by chance use the View > Change Tileset option to change it to mars?  If so, I think I know what's going on.

**Comment by VampireSeraphin** [comment]
yes

**Comment by VampireSeraphin** [comment]
What do you think is causing this to occur?

**Comment by arlith** [comment]
When the Change Tileset feature was added, changes to hexes weren't considered, so when the rough terrain is added, there's a hex change that happens, and the theme isn't being applied properly.  The addition of the rough terrain is something that ends up happening to the  board, and is sent by the server.  The "change theme" is a client-side setting.

**Comment by VampireSeraphin** [comment]
Is that easy to fix?

**Comment by arlith** [comment]
There are three issues here.... 
First is that the rough images for the large texture were using images that didn't have a transparent background, so they would override the base texture.  That was fixed with some updates from BW in e0fd4af133de97ab02e26e8e3ce0a6bd078710da.

Second, if you set the theme in the client, then any updates to the board from the server don't apply the theme.  This was fixed in fe31f75c606ea044887fa9842c85378b662c7020.  When a hex update comes from the server,  the event listener in the BoardView will check to see if there's a theme override set, and if so, it will make sure the updated hex has the proper theme.

Third, there is a bug with how we iterate hexes in a ring for area of effect things like explosions.  This is why you see a "star" pattern in the engine explosion screenshot and not a "circle" pattern.  This is a larger issue with its own ticket: #440.

**Comment by BLOODWOLF333** [comment]
It wasnt my fault! *happy dance*
