### ISSUE TITLE
BA fails PSR jumping into building and suffers damage 0.49.14-SNAPSHOT

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#4529]
![image](https://github.com/MegaMek/megamek/assets/18338059/10430749-5b38-4fba-afbb-78a73c71d172)

Princess jumped IS Standard BA into a building and the squad failed a "PSR" and suffered damage.  I don't think this is the correct way to handle this IIRC.

Save game attached:  
[BA-failed-PSR.sav.gz](https://github.com/MegaMek/megamek/files/11751770/BA-failed-PSR.sav.gz)

**Comment by BLR-IIC** [comment]
Playing through this game more, the battle armor squads are forced to make PSRs just moving through buildings, which I'm pretty sure isn't correct either.  Otherwise what's the point of any infantry in building-to-building settings?

**Comment by gsparks3** [comment]
Per Total Warfare page 168, Infantry should require an AM roll when using jump movement to enter a building hex from outside of that building at a level below the roof. Essentially, you have to aim the jump well enough to jump through a window without hitting the walls. The screenshot shown above appears correct, as the battle armor jumped into a building hex from outside the building. The damage is higher than expected, but that appears to be due to the Battle Armor Critical Hits optional rule being active. 

Megamek currently has an issue where it only requires the AM roll if the jump infantry have insufficient MP to reach the roof of the building (see #3256 and #2935).

Infantry moving through a building using ground MP should not require any rolls. Are you seeing PSRs while using ground MP? If not, this appears to be a duplicate of 3256, and the only actual bug is that it isn't requiring this PSR all the time, instead of only on tall buildings.

**Comment by BLR-IIC** [comment]
It was with jumping MP only, so I stand corrected.  Thanks for checking!
