### ISSUE TITLE
Generated map settings not working correctly?

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#458]
I was trying to create a map filled with elevation changes and roads to test another issue, so i set roads to 100% and elevation to the "high" setitng.

After clicking "okay", I noticed that "map selected" had switchd to "SURPRISE" instead of "GENERATED". It should be on GENERATED as im using the generated map settings. The map preview didnt change everytime i previewed it, which meant that it was using a stock map instead of randomly generating it each time.

When I set it to use the generated map settings instead, It didnt seem to be using the custom settings i had chosen...i set roads to 100%, but it only generated a handful of road hexes instead of roads in every hex. See the lower part of the screenshot.

![megamek](https://cloud.githubusercontent.com/assets/1191378/21580576/1efa87ba-d055-11e6-8d52-6404a2ed938f.jpg)

[megameklog.txt](https://github.com/MegaMek/megamek/files/679943/megameklog.txt)

**Comment by mkerensky** [comment]
I use generated maps for nearly all of my games, and it seems to work just fine. 
Changing the generated settings does reset the map selection to 'surprise', but when you reset it to generated, it will keep your custom settings.
Use the map size options on the select map screen, rather than the generated map settings screen, for best results.
I think you're also looking for the wrong results on your road. Setting the road option to 100% means you have a 100% chance of getting 'a road' on the map, not that every hex will contain a road. If you want more of a road grid, use that option under the cities and towns portion of the Civilization tab. The more city blocks you pick, the more roads you get.

**Comment by BLOODWOLF333** [comment]
Yeah anytime you change something in generated map settings it will reset to surprise and you then have to re-click that << button to change it back to generated map, its been like that forever and is not wrong.

**Comment by neoancient** [comment]
In my opinion, changing the generated map settings should not reset the map to surprise.

**Comment by arlith** [comment]
I don't witness this changing to surprise behavior.  When I change a setting in "Generated Map" settings, if I had selected "[GENERATED]" beforehand, it stays, even if I change the size of the board.  Are there particular settings that are affecting this?

**Comment by arlith** [comment]
Interesting... apparently if I load an XML file and then click okay, it does change.

**Comment by arlith** [comment]
So, I'm going to take this ticket to represent the problem of the map changing when you load map settings.  The other issue seems to 1) a misunderstanding of the map generation options and perhaps 2) wanting some new options for map  generation.  This is more of a feature request, which I don't see happening.

I found the cause of the map switching.  It's because, when the XML file is loaded, it generates a new `MapSettings` instance, and doesn't save the currently selected boards, instead reverting to the default.  Caching and restoring the selected boards will fix this.
