### ISSUE TITLE
Incorrect titles for ASF pilots and BA troopers in the end-of-battle text

### ISSUE THREAD

**Issue by crazys1** [MegaMek/megamek#464]
Version 0.42.0

After completing a battle that included aerospace fighters and battle armor, in the end-of-battle results, you see text similar to the following example:

> Survivors are:
> Simurgh SMG-9TF Prime (Nine-Tailed Foxes)
> Driver : Lieutenant So-hee Yoon [3/4]
> Kills : 4
> 
> ...
> 
> Black Wolf Battle Armor [Plasma] (Wolf Empire (Reinforcements))
> Gunnery Skill : Mafileokaveka [1]
> Kills : 0

The Simurgh is an ASF, and the pilot is titled as "Driver." I'm pretty sure that should be "Pilot" as it is with 'Mechs.

For the BA, the trooper's name is titled as "Gunnery Skill," which clearly is wrong. I think it should be "Trooper" or something similar.

**Comment by arlith** [comment]
The problem with BA is that they were using `Crew.getDesc(true)`  Which returns `<crewname> [gunnery]`.  Basically, it's the exactly same output as for the "Driver" entry above, just omitting the piloting (or anti-mek, for infantry) skill.  This looks somewhat strange for BA.  Instead, I added a new report that's just `Gunner: <gunnery skill>`, so that the crew name is omitted.

For ASF, I switched ASF/Conv Fighters to "Pilot" and added a new `Crew : ` message for other larger ships, like Dropships, Jumpships, small craft, et al.
