### ISSUE TITLE
terrain changed during game

### ISSUE THREAD

**Issue by seem8** [MegaMek/megamek#466]
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/692016/autosave.sav.gz)
On the map Lunar Raid terrain was changed after blowing up some Fuel Tanks.
http://wstaw.org/m/2017/01/07/mm1error1.jpg
http://wstaw.org/m/2017/01/07/mm1error2.jpg
New buildings and fluff elements was replaced by older ones. Roads was replaced and on roads and under city walls was grass, instead of moon terrain.

**Comment by BLOODWOLF333** [comment]
Related to #440

**Comment by arlith** [comment]
This bug was introduced in fe31f7 with the fix for #434.  The problem was that BoardView's `selectedTheme` was initialized to `""` and not null, and when a hex update is received by the BV, it was always setting the theme on the incoming hex, generally to nothing.  This isn't quite right so I first initialized `selectedTheme` to null (which is handled properly already), and also added a check for `("No Theme")` which also shouldn't change the incoming hexes' theme.
