### ISSUE TITLE
Printing and Exporting Issue Fix

### ISSUE THREAD

**Issue by John2003cpht** [MegaMek/megamek#4701]
I am using Linux Mint 21.2 and MekHQ version 49.14 and Java 17.0.1. I could not get MegaMekLab to print or export to pdf no matter what I did. It also would not genarate any log files. The way I was was running the programs was opening my gui file manager and made the jar files exeacutable the megameklab.jar, megamek.jar, and mekhq.jar. At that point I just double clicked and ran them and because they ran I thought all was good but I was wrong. I had to make 6 more files exeacutable and run your starter files from the terminal and then things worked. I ended up writing 3 batch programs that are run by launchers and it works great now.

**Comment by John2003cpht** [comment]
The six other things I had to make exeacutable were the files mhq-startup, mhq-startup.bat, mml-startup, mml-startup.bat, mm-startup, and mm-startup.bat

**Comment by neoancient** [comment]
The *.bat files are for Windows and do not need to be made executable. The *-startup are shell scripts and are the way that the programs should be started. They are not executable because the packaging is currently being done on a Windows machine that does not interact with the executable bit, and the end user must do this.
