### ISSUE TITLE
Vehicle damage threshold not working correctly

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#473]
Weapons fire for Hunchback HBK-4H (Independent (Periphery))
    AC/10 at Peregrine Attack VTOL (FCE) #2 (Comguards); needs 7, rolls 12 : hits  (using Right Side table) RS
        Peregrine Attack VTOL (FCE) #2 (Comguards) takes 10 damage to RS.
            Armor destroyed.
             2 Internal Structure remaining.
            Critical hit on RS. Roll is 8; damage threshold not exceeded, no effect.

The VTOLs have 9 side armor and the game has the vehicle damage threshold divisor set to 10, yet megamek thinks that the damage threshold has not been exceeded, when it has.

[comguards.sav.gz](https://github.com/MegaMek/megamek/files/702191/comguards.sav.gz)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/702193/mekhqlog.txt)

**Comment by Dylan-M** [comment]
This is a strange issue, it shouldn't even be checking threshold at this point because it hit internal structure. Threshold takes effect to determine if you get a crit even if you didn't penetrate the armor. I suspect this is just a bad message, because thresholds definitely work.

**Comment by neoancient** [comment]
The code in `Server` that checks threshold excludes VTOLs. Starting with line 21871 (at the time of writing):
`                if ((te instanceof Tank)
                        && game.getOptions()
                                .booleanOption(OptionsConstants.ADVCOMBAT_VEHICLES_THRESHOLD)
                        && !((te instanceof VTOL) || (te instanceof GunEmplacement))) {`

Since this is an unofficial option, there is no right or wrong way to do it but I see no reason why VTOLs would be treated differently and if there is some reason to do so we should change the text of the option to indicate ground vehicles specifically.

**Comment by Dylan-M** [comment]
This is most certainly intentional, due to the more fragile nature of VTOLs. It shouldn't affect WiGE either, but I forgot to account for that when I wrote this originally.

**Comment by arlith** [comment]
The problem here is with the report.  In `Server.criticalTank` around line 25528 there is a check to see if report 6006 (the "didn't exceed threshold" report) should be added to the critical report.  This check doesn't include the "not VTOL or GunEmplacement" portion, but they aren't above the threshold, so the "didn't exceed threshold" report gets added.
