### ISSUE TITLE
[0.49.14] 'Planetary Conditions' overlay cannot be hidden in Map Editor

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#4737]
MM 0.49.14 (standalone and bundle)
Windows 10
Java 11

In the map editor, CTRL-P does not hide the new planetary conditions shortcut overlay (Which also appears to only render a single line, as obviously planetary conditions are not linked to the map.) That pop-up should probably be permanently hidden on the Map Editor render.

![image](https://github.com/MegaMek/megamek/assets/26851644/f491f55d-574e-4799-9eca-e1cce04f0ee1)

**Comment by Sleet01** [comment]
@SimonLandmine Sorry, I got sidetracked on another issue.

I believe this is likely related to the <ctrl>+<k> issue that was seen previously, so applying the same restrictions to this overlay may be sufficient to fix the problem.  I'll see what I can find out.

**Comment by Sleet01** [comment]
For future reference, the "Planetary Conditions - press... CTRL + P to toggle this overlay" line is only visible in the map editor if the map is zoomed in and the window is shrunken to bring the right edge of the window frame just to the edge of the map.  Otherwise it is hidden behind the white filler space around the map.

This is not to trivialize the bug, but as a guide for reproducing similar issues in the future.

**Comment by Sleet01** [comment]
As suspected, the state of the Planetary Conditions configuration setting in the main game influences whether it displays in the Map Editor, just as with the Keyboard Shortcuts overlay issue previously reported on 49.13.

**Comment by SimonLandmine** [comment]
Makes sense.

**Comment by Sleet01** [comment]
I've got a little bit of a hacky fix.

The problem is that we first instantiate the CommonMenuBar, _then_ we create the PlanetaryConditionsOverlay, which initially defaults its visibility to whatever the GUIP preferences object has set, _not_ what the CommonMenuBar has set (because the two objects don't see each other at all).  The Overlay then becomes a listener for menu bar events such as toggling View->Show Planetary Conditions Overlay (which is disabled in BoardEditor) and so can never change its state after init.

So first we're turning off the option, then we're loading the overlay, then we're setting it to visible or invisible based on what's saved in the MM options and not allowing the player to change it.

The hack is to not instantiate the overlay at all if we're in a BoardView with no players; this avoids a bunch of changes to the objects and appears to work.
