### ISSUE TITLE
[0.42.0] Next Valid Target Not Working for Ground to Air Attack.sav

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#475]
Next valid target not working if you are on the ground and have visibility and sensor to air targets.

[NextValidTargetNotWorkingForGroundToAirAttack.sav.gz](https://github.com/MegaMek/megamek/files/705780/NextValidTargetNotWorkingForGroundToAirAttack.sav.gz)

**Comment by SirMegaV** [comment]
Tested with air to air targeting on ground map and it's working.

**Comment by SirMegaV** [comment]
Weird... it's working now on the next turn...

**Comment by arlith** [comment]
Which targets do you think are valid? The "valid" check requires that the to-hit is `<= 12`.  It would appear that your intended "valid" target is the `Intrepid Assault Craft (2331) #12`, which requires a to-hit of 13.  That's why it's not working.

I can see how it may be confusing that it doesn't target a unit that's "valid" because of LoS but not because of to-hit, however in situations of lots of units it can also be useful to not target units with valid to-hits, because you could use it as a way to filter what targets you can shoot at, and more often than not you don't want to shoot at impossible TNs.

I'm going to close this ticket for now, but if you want to argue that the `<= 12` check should be removed, I'm willing to listen.
