### ISSUE TITLE
NullPointerException at firing phase start

### ISSUE THREAD

**Issue by KaiserFalk** [MegaMek/megamek#4790]
### Environment
MekHQ 0.49.14
Windows 10
Java 17.0.8

### Description
NullPointerException when starting firing phase - seems to be artillery related?

### Files
[megamek.log](https://github.com/MegaMek/mekhq/files/12517800/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/12517801/mekhq.log)

[Czechoslovak Foreign Legion30270919.cpnx.gz](https://github.com/MegaMek/mekhq/files/12517807/Czechoslovak.Foreign.Legion30270919.cpnx.gz)

Savegame: advance turn to firing phase to get NullPointerException. I had a Thumper artillery vehicle off screen, but I fled it to avoid sniper turret counterfire
[autosave.sav.gz](https://github.com/MegaMek/mekhq/files/12517810/autosave.sav.gz)

Custom mechs: Dervish and Archer are in this battle
[Czechoslovak Foreign Legion.zip](https://github.com/MegaMek/mekhq/files/12517859/Czechoslovak.Foreign.Legion.zip)

**Comment by Sleet01** [comment]
I've touched that stuff recently, I'll take a look.

**Comment by Sleet01** [comment]
This is a pretty niche case, and we were not handling it correctly.
The order of operations seems to be:

1. Sniper turret fires on target during Indirect phase.
2. target flees during movement phase.
3. target is _removed from the game_, that is, it no longer is registered as an entity.  But the created AttackAction remembers its ID.
...
4. Fired indirect attack "lands" and attempts to get the location of the target... which no longer has any record in the game.  And because it was a counter-battery shot at an off-board target, we never recorded the original target's coordinates.
5. NPE occurs when trying to call `target.getPosition()` because `target` is null.

My proposal is to just not worry about where the round goes in this situation, and move on.  Unless it's possible for an off-board artillery round to scatter back onto the visible map (I'm relatively sure it is not) there's no reason to try to do anything more in this edge case.
