### ISSUE TITLE
Major Bug with Init Compensation... it Compensates even when You win init... DOAH!

### ISSUE THREAD

**Issue by Mekslayer** [MegaMek/megamek#480]
it Compensates even when You win init... DOAH!

**Comment by Mekslayer** [comment]
It is in 0.42.0 Stable No LESS!!

**Comment by Dylan-M** [comment]
1. I don't think you understand how it's actually supposed to be working, but yes, you're compensated on the turn you win, because it's based on _prior_ turns. It would only be a bug if it did it on the turn _after_ you win.

2. This is not an acceptable bug report, and you know it:
https://github.com/MegaMek/megamek/wiki/Making-a-Bug-Report

**Comment by Mekslayer** [comment]
I am not a SW person.. so here is our gamelog to prove what Happened.
[megameklog.txt](https://github.com/MegaMek/megamek/files/751316/megameklog.txt)

[gamelog.txt](https://github.com/MegaMek/megamek/files/751322/gamelog.txt)

**Comment by HammerGS** [comment]
A note on the log, there are thousands of lines of errors relating to unit files.  Extensions wrong, invalid and illegal equipment combinations.  Most seem to be in a "AJ_Mechs" folder.  I'd suggest removing that folder.
