### ISSUE TITLE
Flight path data readability improvement

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#4812]
There are a couple of numbers in the flight path data which I have an extremely hard time making out:

![Flight path numbers](https://github.com/MegaMek/megamek/assets/70451747/59ffe838-52a6-4b74-a557-f4de34a3438e)

Specifically, the red numbers (current hexes moved/mandatory hexes moved?) overlaid on the large cyan numbers.  It would be easier to read these if they were below (preferred), above, or just somewhere else.

**Comment by JonhyBurner** [comment]
I agree with moving the numbers, but other hexes can have numbers, words and other indicators as well, so a place should be chosen as not to interfere much with those either. Since they have different operators around them, putting them above to the left of the others would be my choice.

**Comment by BLR-IIC** [comment]
Could the path number color be changed too?  I find that shade of red hard to read and would like to change it.

**Comment by HoneySkull** [comment]
#5301 was designed to address this concern in a way that eliminates the need to squeeze the flight path numbers on the hexes.  Instead of trying to display busy numbers on the current path, Flight Path Indicators only show the elevation and thrust on the moved hexes, and project a series of indicators along the flying vehicles current trajectory showing both how far the craft must travel and when along that path it can turn for free or for thrust cost.

![image](https://github.com/MegaMek/megamek/assets/83041327/bd36f398-808e-4280-8fda-b8be6a9a057c)

It adjusts as you navigate your flight path and also can help visualize and help line up attack runs because you can instantly see the row of hexes the craft will fly over.

**Comment by SuperStucco** [comment]
@HoneySkull - was keeping an eye on that, it can close this request.
