### ISSUE TITLE
Low-altitude match hangs before final round report

### ISSUE THREAD

**Issue by nutritiousemployee** [MegaMek/megamek#4846]
Environment
Version: 49.15
OS: Windows
Java: 17.0.1

Description
This issue was generated while playing a MekHQ scenario, but it can reproduced by just loading the provided save file in MegaMek.
Logging it as a MegaMek issue for that reason.

In a low altitude map with one allied and one enemy bot, while the player has no units remaining, the game hangs before the final round report after the allied bot killed the last remaining unit of the enemy's bot.
The round report screen remains empty, and the "Done" button is greyed out.

To reproduce, load the attached save in MegaMek, replace the ghosts with bots and wait a few seconds for the issue to happen automatically.

Files
[save.zip](https://github.com/MegaMek/megamek/files/13063112/save.zip)

**Comment by kuronekochomusuke** [comment]
to work around this issue until next release, you can hide the unit tooltip in the report log in game options.   this issue happens when it tries to display an pilot image in the report log, unit tooltip for a killed unit.

![image](https://github.com/MegaMek/megamek/assets/116095479/be8a64fd-054a-4a61-9cd0-19194efab669)
