### ISSUE TITLE
[49.15] Hang on use of RAC/5 when insufficient ammo is available

### ISSUE THREAD

**Issue by casualjoker** [MegaMek/megamek#4861]
### Environment
MegaMek 49.15
Windows 10
Java 11

### Description
I don't have a screenshot, but I do have the log and save game file. a Highlander attempted to fire more rounds than available for a RAC/5 and the game locked up and froze and also possibly kicked the offending player from the game.

### Files
[megamek.log](https://github.com/MegaMek/megamek/files/13197301/megamek.log)
[save.sav.gz](https://github.com/MegaMek/megamek/files/13197302/save.sav.gz)
Player name: "Brookfield Asset Management"
Name of player this issue effected: "Jeff-Sabar my name is short just like my. . . .Temper"
this was a multiplayer co-op game

**Comment by kuronekochomusuke** [comment]
here is a nightly save setup right before the issue happens.  just need to fire the 2 rac5 .  the game then hangs and there is not any errors in the log.

[rac5.sav.gz](https://github.com/MegaMek/megamek/files/13210365/rac5.sav.gz)

**Comment by Sleet01** [comment]
It looks like the initial log doesn't contain much of interest; we'd probably need the disconnected player's `megamek.log` to see what their client reported from the server.

I'll see if I can dig up some info from the save game, though; thanks for providing that.

**Comment by Sleet01** [comment]
I'm tentatively calling this an unhandled exception in Precognition, which runs in its own thread.  From what I can tell:

1. `qwerty` declares their attacks, trying to use 12 RAC/5 rounds with only 3 (or is it 6?) remaining total.  This attack declaration is sent to the server, which also hosts Princess.
2. an exception occurs while Precognition is handling `qwerty`'s declared attacks; probably due to running out of ammo but possibly something else.  This is due to Precognition ingesting all the events that its host receives, but handling them separately (I believe to speed up Princess' handling of each phase).
3. Precognition catches the exception within its `run()` method but does nothing with it.
4. Precognition goes back to waiting for more events, causing a LiveLock situation:
- Player's client is waiting for feedback from the server.
- Server is waiting for Princess to declare attacks.
- Princess is waiting for more Events to arrive at the server.

This all makes the issue quite difficult to debug, as the (presumed) exception is swallowed.  I believe the server and client will probably handle the issue of over-allocated RAC rounds correctly, they just never get to that point.

**Comment by Sleet01** [comment]
Looks like I'm incorrect about the location of the exception; it may be in the player's client _after_ sending the attack actions.

**Comment by Sleet01** [comment]
Yep, the Princess disconnect was a red herring: we were just straight-up ignoring the possibility of having to handle a RAC shot with zero remaining ammo at one point in the code.  In fact, I quote:

```
// there will be some ammo somewhere, otherwise shot will not have
// been fired
```
(this is directly below the point where we don't properly handle the case where 0 rounds remain, which is what has been happening)

Working on a general fix.  I think I want to clean up the RAC and UAC handlers at the same time, as they duplicate a lot of functionality... and UAC handler, as currently written, could absolutely hit this issue.
