### ISSUE TITLE
Fumble setting incorrect

### ISSUE THREAD

**Issue by epic76** [MegaMek/megamek#4866]
### Environment
  MekHQ megamek .49.15
 Windows
  Java 11
)

### Description
.  When checking for fumble roll, is not just a 2 rolled that is generating a fumble
 TO pg 77 
but this happened on turn 1

Griffin GRF-1N #2 (Loknar's Pirate Legion) must make a piloting skill check (used more MPs than at 1G possible).
); needs 6, rolls 6 (Base piloting skill) + 0 (used more MPs than at 1G possible) Fumble!: falls.
        Griffin GRF-1N #2 (Loknar's Pirate Legion) takes 1 damage to Internal Structure of RL.
             12 Internal Structure remaining.
            Critical hit on RL. Roll is 11; 2 locations.
            CRITICAL HIT on Hip.
            CRITICAL HIT on Upper Leg.

        Griffin GRF-1N #2 (Loknar's Pirate Legion) takes 1 damage to Internal Structure of LL.
             12 Internal Structure remaining.
            Critical hit on LL. Roll is 8; no effect.

Situation is, low gravity .77.  They did jump 6 but should have fumbled only on a 2, report say it rolled a 6.  

### Files

[megamek.log](https://github.com/MegaMek/megamek/files/13231232/megamek.log)
[autosave_2023-11-01_12-31-37.sav.gz](https://github.com/MegaMek/megamek/files/13231218/autosave_2023-11-01_12-31-37.sav.gz)
[autosave_2023-11-01_12-31-41.sav.gz](https://github.com/MegaMek/megamek/files/13231220/autosave_2023-11-01_12-31-41.sav.gz)
attached save before and after issue happened 
Player name Chimera
other player name Loknar Pirate Legion

**Comment by epic76** [comment]
minor correction: other player name was Loknar's Pirate Legion

**Comment by ObviousTech** [comment]
for this specific PSR check, it's doing 
```
SharedUtility.checkNag(rollTarget, nagReport,
                                    psrList);
```

but for most similar checks in the same file (megamek/src/megamek/client/ui/SharedUtility.java), the call is 
`checkNag(rollTarget, nagReport, psrList);`

(However, there are a few other instances of SharedUtility.checkNag() calls, notably in the section where it checks for fall damage from leaping off a cliff.)

**Comment by gsparks3** [comment]
I will note that I recently experienced this same issue in 0.48 several times in a single game. In all cases, the "fumbled" PSRs were for moving too quickly in low gravity.

**Comment by ObviousTech** [comment]
Turning on the dice log shows something interesting.  See the final round of this test game.  The rolls match up with the piloting checks [10, 8, 7], then there is a 2.  This 2 corresponds with the fumble.  But the unit is displayed as needs 5, rolled 5, fumble.

So most likely, the fumble is correct, but the wrong result is displayed.  Additionally, these fumbles only seem to be occurring when the displayed check == the TN, so maybe the log is getting the TN's value instead of the roll's value when there is a fumble?

[forcedfumble.zip](https://github.com/MegaMek/megamek/files/13233448/forcedfumble.zip)
