### ISSUE TITLE
Megamek Has Thunder ammo shenigans

### ISSUE THREAD

**Issue by miku2020** [MegaMek/megamek#4908]
### Environment
Windows 49.15 MekHQ

### Description
first 2 pictures shows ammo following options turned off: tacops minefields / bmm minefield support
last picture has following option turned on: tacops minefields / bmm minefield support

![Battletech_bug3](https://github.com/MegaMek/megamek/assets/2915330/13409332-1159-41a3-b6a0-851473c7f4dc)
![Battletech_Bug1](https://github.com/MegaMek/megamek/assets/2915330/d0c33299-6054-4d23-99f3-7a26bb497310)
![Battletech_bug2](https://github.com/MegaMek/megamek/assets/2915330/e57811ce-bdcd-4ec7-b74e-faf3e4ed8259)

**Comment by neoancient** [comment]
Since the actual issue is not stated, I'm left to guess and I assume it's that the LRM ammo choices include thunder munitions whether or not the advanced mines option is in use. I've tested in the current repository and v0.49.15 and verified that the list does in fact filter out thunder munitions when advanced mines is switched off.
