### ISSUE TITLE
java.lang.IllegalArgumentException: Attacker or target not valid at megamek.common.actions.ThrashAttackAction.toHit

### ISSUE THREAD

**Issue by Sebmono** [MegaMek/megamek#4949]
### Environment
0.49.15
Windows 10
Java Vendor: Eclipse Adoptium
Java Version: 11.0.13

### Description
![image](https://github.com/MegaMek/mekhq/assets/7840034/8ac86c6c-ece7-4e48-8cc1-9d8f8865831b)
I get the above error after clicking the 'Done' button at the end of the Round 15 Firing Phase. 

Exact reproduction steps with the below campaign and MegaMek save file:
1. Load the below campaign save file.
2. Click Load Saved Game from the Briefing Room for the TankBase - Hostile - Prevent Evac scenario.
3. Select OK, load the BA_01.sav file below.
4. Game > Edit Bots > Replace all with Princess > OK
5. Have Booster fire autorifle at pilot north of her.
6. Have Voltage fire autorifle at crew north of him.
7. Have Jester fire all weapons at Cataphract closest to him.
8. Have Calamity fire all weapons at Cataphract closest to her (same one as Jester).
9. Select Done.
10. After Fire Phase resolution log is produced, click done.
11. Error.

### Files
Provide the .cpnx campaign file that this issue occurs in.
[Poznan Heavy Lancers02.cpnx.gz](https://github.com/MegaMek/mekhq/files/13636685/Poznan.Heavy.Lancers02.cpnx.gz)

Also here is the MegaMek in-mission save file it occurs in.
[BA_01.sav.gz](https://github.com/MegaMek/mekhq/files/13636780/BA_01.sav.gz)

Provide any custom units that you are using in this campaign so that it will load on the developers machine.
[Black Knight BL-7-KNT Hussar.zip](https://github.com/MegaMek/mekhq/files/13636708/Black.Knight.BL-7-KNT.Hussar.zip)

Provide any other files that you have customized in this campaign like the factions.xml for example.
I'm using the customized "Heavy" scenarios from Discord here: https://discord.com/channels/458705327911731231/1125131384835555491/1125151393515327498
[scenariotemplates.zip](https://github.com/MegaMek/mekhq/files/13636750/scenariotemplates.zip)

And provide the megamek.log and mekhq.log files for any NPEs or errors that MekHQ might be reporting.
[mekhq.log](https://github.com/MegaMek/mekhq/files/13636773/mekhq.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/13636774/megamek.log)

**Comment by HoneySkull** [comment]
Thought about that too, but there should be no condition where there input parameter are null - so this check indicates some kind of a problem that would be masked if it treated it as impossible.  If it's changed to return impossible instead of throwing an illegal argument error, then I would still recommend posting an error to the error log.

**Comment by HoneySkull** [comment]
ThrashAttack - is different that all the other attack actions when checking for physical attacks, the class gets newed up instead of the toHit function being static like all the others.   ThrashAttack looks up the target and entity from the 'game' interface and not the entity and target passed into the constructor.  I'm suspect the game object is out of sync with the target and entity the object is constructed with.   All the other 'toHit' methods on the Attack Actions are static and pass in and use the Entity ID and target.
