### ISSUE TITLE
[0.42.0 Bug] Map Editor Theme Broken

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#499]
1. Open MM map editor.
2. Set theme to 'grass', preview will show grass hex
3. Apply 'grass' hex onto the map, 'grass' hex will not appear.
4. Same with 'snow', 'mars', 'lunar' etc.

**Comment by arlith** [comment]
This bug was introduced in fe31f75c, which was fixing an issue reported in #434, where board update events were changing the UI-selected theme.  I added code that compares the theme on the incoming hex, and could adjust it to the UI selected theme.  This causes a problem with the board editor, which actually doesn't care about this code.  I added to check to only fire the code in fe31f75c if the user isn't in the board editor.
