### ISSUE TITLE
Feature request: active unit window hotkey/button

### ISSUE THREAD

**Issue by ThomasMarik** [MegaMek/megamek#504]
This is a bit of a pet peeve of mine and is mostly relevant in the weapon phases. Could we get a hotkey or a button that will automatically bring the active mechs status window up?  I find it irritating that if I look around at the various targets information window I then have to hunt my mech down again to select the weapons I want to fire. It's not a game breaking thing. Just something I keep wishing I had.

**Comment by arlith** [comment]
Do you have a suggestion for what key to use?  I had thought about Ctrl-Spacebar, but that seems like it would be good for selecting and centering on the active unit.  Tab may be another option.  It may be possible to switch between the currently selected and currently viewed unit, but maybe not.  I'm not even certain it'd be easy to swap back to the currently "selected" unit vs the currently "viewed" unit.

**Comment by ThomasMarik** [comment]
CTRL+C maybe for current mech.  Maybe instead of a hotkey have the weapon screen for the currently active mech pop up when you select a target.   Another possibility is to add an option to select the active mech in the right click menu regardless of what you are right clicking on.

**Comment by arlith** [comment]
Ctrl+C is already bound to "Next Valid Target".  I don't really want to add yet another mech display, as it just adds yet more open windows.  You can't have an "active 'mech" and "select mech" both at the same time, as you *need* the mech display in order to fire weapons on the active mech.  I think your initial suggestion is best: have a key that can quickly switch you back to your currently "select" mech (which is a unit you own and can control) vs your currently "viewed" unit (which can be any unit on the board).

**Comment by pheonixstorm** [comment]
Can the hotkeys be changed in the client settings? Never really looked. If not would changing the code to allow it be difficult?

**Comment by arlith** [comment]
Yes, hotkeys can be changed.  Yes, the code to allow hotkeys to be changed is complex.
