### ISSUE TITLE
Report.addNewline failed, array index out of bounds

### ISSUE THREAD

**Issue by seem8** [MegaMek/megamek#510]
I have a MegaMek on my little VPS and players had a strange error:
http://pastebin.com/aFjvX4ee

It starts on the line 207 with "Report.addNewline failed, array index out of bounds" and repeated . Server hanged for awhile, but managed to "unloop" itself after a few minutes. I wasn't playing with them. Does anyone have idea of what could happened?

thanks

**Comment by arlith** [comment]
Did this cause issues with the game, other than the hang?  Whenever something happens in the game, MM uses a `Report` to generate the text for the reports between phases.  These reports can be public or hidden, for double-blind games.  If the reports are hidden, they must have a subject ID that identifies who the report belongs to, so it can be properly filtered.  This error means that there was a report that wasn't public, and didn't have a subject ID.

The vast majority of the reports belong to reports for geysers.  I'll push a fix for it.  Two out of those many errors related to a report for repairing a jammed tank weapon.

The array index out of bounds message is just a warning message.  It happens when `Report.addNewLine` is called with a report vector that's empty.  It doesn't cause any harm, it's just a logged message.

**Comment by seem8** [comment]
Oh, I missed your reply. Thank you very much, I'll upload that on our server and check it out.
