### ISSUE TITLE
[0.49.19] Dual Thunderbolt 20's on Orochi Only Fired One Launcher

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#5189]
### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:118) - Starting MegaMek v0.49.19-SNAPSHOT
	Build Date: 2024-02-19T01:07:54.080017200
	Today: 2024-02-21
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 8 GB

### Description
When firing both Thunderbolt 20's, the Orochi in this save file sometimes only fires one of them. The + appears next to the weapon indicating it was fired and it appears to deduct the ammunition correctly, but no weapon is actually fired and it does not generate heat for the one that did not fire.

It's possible this has something to do with the ammo bin size 3, as this occurred during the second turn of firing, so the second launcher would have switched to the next full bin for its ammunition

Save file made during the firing phase where the issue occurred, and I am also including the autosaves from the turn phases prior. Gamelog.html included as it shows the Orochi as only firing one TB20 launcher.

Megamek.log does not appear to show anything at all regarding the launcher firing.

### Files
![image](https://github.com/MegaMek/megamek/assets/101755917/81c26207-25d6-4cc5-a459-0d0434d6eda1)

[Orochi TB20 Bug.zip](https://github.com/MegaMek/megamek/files/14363265/Orochi.TB20.Bug.zip)

**Comment by Sleet01** [comment]
Fun fact: the ammo loading is working correctly.  The new ammo bin even gets linked to the correct weapon!  But then the to-hit calculation for one of the weapons says it's impossible because the weapon is "out of ammo".   It looks something like this:

TBolt 1 declares attack action.  Ammo bin A is at 1 shot left.
TBolt 2 declares attack action.  Ammo bin A is at 1 shot left.
GameEngine handles attack action 1.  Ammo bin A drawn down to 0 shots left.
TBolt 1 attack action handled, attack roll made, damage allocated, and action concluded.
GameEngine handles attack action 2.  Ammo bin A is bingo, TBolt 2 linked to Ammo bin B, which is drawn down to 2 shots left.
Tbolt 2 attack action handled, attack roll ruled IMPOSSIBLE due to out of ammo (?!) and attack silently fails.
End result: 2 ammo used, 1 attack made, 1 weapon's heat generated.

I'll see if I can suss out the root cause; it's probably to due with how ammo is passed around to toHit calcs now.

**Comment by PhoenixHeart512** [comment]
Issue just occurred again but on a unit that has NEVER had this problem before and has been used in my campaign since 49.15 or so. I believe this issue is new to 49.18 or .19.

![image](https://github.com/MegaMek/megamek/assets/101755917/9004c7f1-bfb7-4dd8-8ca2-ea6f56087d31)
