### ISSUE TITLE
[49.18 Nightly] - Infantry Firing issue

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#5224]
This was discussed in discord.  Very quick bug report.  Infantry (at least tested with Horse Cavalry AR and Laser versions) no longer fire their weapons.  They will spot and do leg and swarm attacks, but not shoot their guns.

Sort of related:  4 of them were spotting one unit.  Seems like there should be a "has been spotted" flag so multiple units dont waste their spot on a single target.  
Screens showing them not firing, MHQ Save, Customs,

EDIT:  Just to remind myself, I also need to post a UI and Turret not firing issue later.

![image](https://github.com/MegaMek/megamek/assets/23645569/a746e6bb-dc74-4907-b80a-53db21cc92f3)
![image](https://github.com/MegaMek/megamek/assets/23645569/5deaccac-7639-4a64-8458-d0ecc11d4e86)

[Crazed Profanity30690614INFBUG.cpnx.gz](https://github.com/MegaMek/megamek/files/14516620/Crazed.Profanity30690614INFBUG.cpnx.gz)
[Mine.zip](https://github.com/MegaMek/megamek/files/14516634/Mine.zip)

**Comment by Sleet01** [comment]
Ugh.  This was me: the new ammo-selecting code was working correctly for infantry in the _movement_ planning phase, where it guesses at possible attacks; it was also working correctly for ammo-fed weapons in the _attack_ phase, which I tested heavily.  But all infantry will skip actual _infantry_ weapons during the attack phase because they don't think they have any ammo for the weapons.

Fix PR up soon.
