### ISSUE TITLE
Princess colour issues with multiple bots

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#525]
With multiple Princess bots (e.g. to implement multiple Behaviours within the same team), although it appears that you can change the default colour for each Princess, it doesn't seem to update in the back end - the new colour is displayed on the left of the screen, but any 'mechs added retain the original default colour for that Princess.

To replicate:
01 Start a new game as Player1 - default colour blue.
02 Create Princess1 - default colour red.
03 Create Princess2 - default colour green.
04 Change Princess2 default colour from green to red.
05 Add a mech to Player1 - it is coloured blue.
06 Add a mech to Princess1 - it is coloured red.
07 Add a mech to Princess2 - it is coloured green.

If you change the Princess2 colour after selecting the mechs, it is not applied to those mechs either - they remain green.

(As a secondary issue, when you attempt to "set individual camo" on Princess2's mech, the only solid colour option is the original default green - no other 'no camo' options are available.)

(This is on current stable.)

**Comment by neoancient** [comment]
Colors are not intended as camo, but as a way to identify players. While a unit can have a different camo pattern than other units belonging to the player, the color index is set for the player and no two players can have the same color. One change that I made was to make sure the color assigned to a player is displayed in the camo dialog button rather than the one that was selected, if that one is already used by another player.
