### ISSUE TITLE
Linux release 0.43.1 seems to be missing files

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megamek#526]
0.43.1 is smaller than previous releases:

-rw-r--r-- 1 root root  83111637 Feb 13 19:18 megamek-0.42.1.tar.gz
-rw-r--r-- 1 root root  74454150 Mar 31 22:15 megamek-0.43.1.tar.gz

Megmeklog.txt has lots of errors about missing files when drawing boards:

Received null image from ImageUtil.loadImageFromFile!  File: data/images/hexes/grass/grass_plains_0.gif
Trying to load image for a non-existant file! Path: data/images/hexes/transparent/rough_0.png
Received null image from ImageUtil.loadImageFromFile!  File: data/images/hexes/transparent/rough_0.png
Trying to load image for a non-existant file! Path: data/images/hexes/transparent/rough_1.png
Received null image from ImageUtil.loadImageFromFile!  File: data/images/hexes/transparent/rough_1.png
Trying to load image for a non-existant file! Path: data/images/hexes/transparent/rough_2.png
Received null image from ImageUtil.loadImageFromFile!  File: data/images/hexes/transparent/rough_2.png
Trying to load image for a non-existant file! Path: data/images/hexes/grass/grass_plains_0.gif
Received null image from ImageUtil.loadImageFromFile!  File: data/images/hexes/grass/grass_plains_0.gif
Trying to load image for a non-existant file! Path: data/images/hexes/transparent/rough_0.png

...and these files seem not to be packaged in the release.

**Comment by arlith** [comment]
Comparing the file sizes between the latest stable release and the latest dev release will have significant differences because of the image atlases.

The images requested do exist, they just exist within an image atlas.  For instance, `data/images/hexes/grass/grass_plains_0.gif` is now in `data/images/hexes/grass/grass_atlas.png`.  If you look in `data/images` there's an `imgFileAtlasMap.xml` file that does list the old image path and it's atlas look-up.

The problem here is basically the same thing as in #507, except now it's in the value instead of the key.  I should've noticed this when fixing #507.

**Comment by mhjacks** [comment]
Confirmed.  I sub'ed the slashes the other way, and everything works as expected.

**Comment by arlith** [comment]
The problem here is that, when the `File` instance is deserialized, it has a windows path.  This cases `File.equals` to fail on the in-memory version with UNIX-style slashes. I guess I had assumed that the file would internally store the path some other way.  I may have to ultimately use `Path` instead, as suggested by Ralgith.

**Comment by Dylan-M** [comment]
It only has a Windows path if it's built with Windows I thought... but yeah, you may have to use `Path` to handle this.

**Comment by arlith** [comment]
Yea, so I looked at the implementation of OpenJDK `File`.  It only has a `String` state variable that gets serialized, but it has this line: `private static final FileSystem fs = DefaultFileSystem.getFileSystem();`.  It then uses `fs.compareTo` for equality.  So, basically, it's going to be system-dependent as to how path strings in `File` are compared.  This is kind of shitty, at least for this purpose.

**Comment by arlith** [comment]
So, the previous fix worked for a Windows when packaged in Linux, because I think the Windows FS can resolve a UNIX path, but not the other way around.

**Comment by Dylan-M** [comment]
Which is probably why `Path` has the capabilities that it has. Sadly.

**Comment by arlith** [comment]
I'm not sure `Path` will work directly either.  It's a lot less transparent than `File` in serialization, but it does serialize information about the file system.  In a quick test, I couldn't just serialize `Path` instances.

**Comment by arlith** [comment]
Alright, I think I've fixed this with b7c6cf43486f052fe24b9dd656191cb51d79e477 (merging in the imageAtlasFix branch).

Essentially, I went with what Ralgith suggested in #507.  I've created a new wrapper class, `ImageAtlasMap` which wraps a `Map<String,String>`, however you can only insert `Path` objects, which then internally get changed into UNIX-style path strings.  This ensures that we are always using UNIX-style paths, which work in both Windows and Linux (and Mac OSX).

I had Hammer generate the atlas map XML in windows and diffed it with my copy generated in Linux and they diffed the same.  Hammer tested the fix in Windows, and I tested in Linux and it worked.
