### ISSUE TITLE
[49.19-SNAPSHOT #1439] NPE When Targeting Unit Atop Building

### ISSUE THREAD

**Issue by IllianiCBT** [MegaMek/megamek#5275]
### Environment
Origin Project: MekHQ
Java Vendor: Eclipse Adoptium
Java Version: 11.0.22
Platform: Mac OS X 13.6.4 (x86_64)

### Description
NPE encountered when targeting adjacent wasp with wasp piloted by callsign 'Hero'. Save file has 'Hero' as the active unit, so just attempt to target the adjacent enemy wasp and you'll hit the NPE. Other units appear to be unaffected by this issue.

This issue persists into the melee phase.

The issue is also present when attempting to DFA during the movement phase.

Once the enemy Wasp left the top of the building I was able to target them without issue. My current theory is that there is weird interaction going on with the pop-up that lets you pick whether to attack the Wasp or the Building. Especially as 'Hero' was the only unit affected and had the Blood Stalker SPA active on the hostile Wasp.

### Files
[IllianiCBT_#5275.zip](https://github.com/MegaMek/megamek/files/14727177/IllianiCBT_.5275.zip)

**Comment by HoneySkull** [comment]
This is what's supposed to happen when you target a mech on top of a building.  You get a pop-up with a dialog to choose the target. 

![image](https://github.com/MegaMek/megamek/assets/83041327/eef743df-75a7-40d0-b416-3bc1024414b7)

The null pointer in this case is caused by the target having Blood Stalker SPA with a declared target and has selected a hex with multiple targets... The to-hit logic when creating the dialog is trying to compare the target ID of the building to see if it's the Blood Stalker target, but the blood stalker target is null during this check.

The question is:  Does the attacker with a declared blood stalker target still get the +2 penalty if targeting a building?  Or only when targeting another unit?

**Comment by HammerGS** [comment]
Blood Stalker is limited to units only.

**Comment by HoneySkull** [comment]
The issue here isn't that you can or cannot stalk a building, but if you are stalking another mech; do you get the penalty if you then try targeting the building.  I believe the answer is yet based on the verbiage "any attacks directed at targets other than the one the Blood Stalker has designated". 

So the dialog above would be correct as the choosing the building would get the +2 modifier because the attacker has declared another mech as the designated target.

**Comment by HammerGS** [comment]
> So the dialog above would be correct as the choosing the building would get the +2 modifier because the attacker has declared another mech as the designated target.

That is my understanding.
