### ISSUE TITLE
49.19 Nightly - NPE During first round

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#5364]
Set up a bot v bot game.  Was going to test autosave on newest nightly.  Right at the start - I think during round 1 move, game Gives me a NPE.

Dismissed NPE, kicked bots, replaced bots, and the game never restarted.  Had to close.

EDIT:  Doesnt look like the new autosave feature is in this version yet anyway.

![image](https://github.com/MegaMek/megamek/assets/23645569/0842b3cf-9a90-419e-9e20-33b96952f025)

[megamek.log](https://github.com/MegaMek/megamek/files/14974125/megamek.log)

[Customs41424.zip](https://github.com/MegaMek/megamek/files/14974144/Customs41424.zip)

23:53:16,943 ERROR [megamek.MegaMek] {Packet Pump}
megamek.MegaMek.lambda$main$0(MegaMek.java:63) - Uncaught Exception Detected
java.lang.NullPointerException: Cannot invoke "megamek.common.options.IOption.intValue()" because the return value of "megamek.common.options.AbstractOptions.getOption(String)" is null
	at megamek.common.options.AbstractOptions.intOption(AbstractOptions.java:189)
	at megamek.common.service.AutosaveService.performRollingAutosave(AutosaveService.java:48)
	at megamek.server.GameManager.prepareForPhase(GameManager.java:1899)
	at megamek.server.GameManager.changePhase(GameManager.java:1602)
	at megamek.server.GameManager.endCurrentPhase(GameManager.java:2350)
	at megamek.server.GameManager.changeToNextTurn(GameManager.java:2740)
	at megamek.server.GameManager.endCurrentTurn(GameManager.java:1587)
	at megamek.server.GameManager.receiveDeployment(GameManager.java:12844)
	at megamek.server.GameManager.handlePacket(GameManager.java:762)
	at megamek.server.Server.handle(Server.java:1277)
	at megamek.server.Server$PacketPump.run(Server.java:113)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Thom293** [comment]
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/14974169/autosave.sav.gz)
forgot autosave

**Comment by Thom293** [comment]
Ok - as discussed in discord, old save from yesterday removes the autosave option.  New save built tonight the autosave option is present.  Here is new save if it helps.  
[deadeye2.sav.gz](https://github.com/MegaMek/megamek/files/14974337/deadeye2.sav.gz)

**Comment by Sleet01** [comment]
I'm going to close this "won't-fix" for now:
- It only affects save game files for Nightlies or local builds where the source build A does not have the option in question, but build A' (the next Nightly) _does_ have the option, and tries to check its value after loading the save game.
- The cleanest fix requires overriding `readResolve()` for AbstractOption, and probably for all its subclasses as well, which is new territory for me.
- Fixing this will actually going to be a huge hassle to implement because it will require adding a copy constructor to each concrete implementation of AbstractOption (which can't be instantiated 'cuz it's Abstract).
- Introduces a ton of uncertainty in the various areas where Options are used.

We will need to revisit this if we ever allow users to load save games from prior releases, though.

**Comment by Sleet01** [comment]
I'm going to close this "won't-fix" for now:
- It only affects save game files for Nightlies or local builds where the source build A does not have the option in question, but build A' (the next Nightly) _does_ have the option, and tries to check its value after loading the save game.
- The cleanest fix requires overriding `readResolve()` for AbstractOption, and probably for all its subclasses as well, which is new territory for me.
- Fixing this will actually going to be a huge hassle to implement because it will require adding a copy constructor to each concrete implementation of AbstractOption (which can't be instantiated 'cuz it's Abstract).
- Introduces a ton of uncertainty in the various areas where Options are used.

We will need to revisit this if we ever allow users to load save games from prior releases, though.

**Comment by Sleet01** [comment]
I'm going to close this "won't-fix" for now:
- It only affects save game files for Nightlies or local builds where the source build A does not have the option in question, but build A' (the next Nightly) _does_ have the option, and tries to check its value after loading the save game.
- The cleanest fix requires overriding `readResolve()` for AbstractOption, and probably for all its subclasses as well, which is new territory for me.
- Fixing this will actually going to be a huge hassle to implement because it will require adding a copy constructor to each concrete implementation of AbstractOption (which can't be instantiated 'cuz it's Abstract).
- Introduces a ton of uncertainty in the various areas where Options are used.

We will need to revisit this if we ever allow users to load save games from prior releases, though.
