### ISSUE TITLE
RFE:  Tweak of Princess Ammo Conservation

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#5408]
Discussed this in QA channel and sleet asked that I post this.

FIRST:  The new ammo code is fantastic and a great addition.  She is much more dangerous now.  Thank you very much.

Issue: The ammo conservation is making it so princess will not shoot on high TN even when she has lots of ammo.  One of her redeeming qualities used to be that she would always shoot on 12s and get a TAC on you.  With many ammo based weapons, there is no reason not to shoot on 12s.  

Example shown in screenshot below:  This is from 4.23.24 nightly.  Both sides have MML or MRM.  They are clearly in range because they are shooting ISERML and SNPPCs.  This is round 4.  They were in missile range on round 3.  They dont start shooting Missiles until round 6, missing out on at least 3 rounds of potential damage.  So, its kicking in at the wrong time I think.  Some weapons, like AC2 or LRM5 or almost all MML/ATM should always shoot on 12s because they have massive ammo reserves (or in the case of MML/ATM dedicated long and short ammo).

I say the below with the following assumption as its foundation:  Rarely does any unit in Princess control survive more than 10 rounds while in shooting range. Also, she should obviously never shoot on 13s.   

Possible Solutions:
I dont know how exactly it is currently coded, so cant speak to specifics, but I think some general options are:

1.  Turn it off completely.  Its our dear Princess.  She is the embodiment of "The brightest candles burn half as long."  The future is not her concern.  She should not shoot on 13s, but otherwise she should shoot.  Simpliest solution and should be fine for 93.6% of use cases. (I guess in some extremely large battles with very odd terrain that prevents closing to medium range would be an exception, but I would consider that so rare as it can probably be ignored).  "One Shot" weapons like and RLs, Rocket Pods, ASF missiles, etc might need a special class with a carve out: "oneShotWeapons will only shoot on a TN of 9 or lower"
2. Have it kick in on a per weapon basis:  Make a list of all weapons and select a TN on which they should fire.  Somehow should account for ammo reserves.  Seems tedious and unecessary.
3. Have it kick in based on "game rounds of ammo left."  e.g. When you have 3 shots left you dont shoot on 12s, When you have 2 shots left you dont shoot on 11s, When you have 1 shot left you dont shoot on 10s.  If aggression settings are somehow factored in, then could use that as a modifier.  If aggression = 1-3 add 2 rounds to the "caresAboutTN" number. Aggression 4-7, default, 8-10 subtract 2 from the number.  i.e. very low aggression would start conservation with 5 rounds left, and high aggression would only care with 1 round left.  This seems a workable solution too.  Some stuff, like Arty, that always has very high TNs, or that has very low ammo counts, Like a Nuke or Rocket Launcher, should be excluded or have a special carve out exception.

Again - I dont know how its currently coded, so the details may need tweaking, but I think some version of 1 or 3 above would be fine. Since I am a simple man and cant code,  Id comment out the conservation code and start with and test version 1.   But that may be an overly brutish solution.

Thank you.

![image](https://github.com/MegaMek/megamek/assets/23645569/d2f82f8b-35d0-4f0b-b08b-2b798d9ab53d)

**Comment by Sleet01** [comment]
@Thom293 
I updated this code while working on the Princess ammo selection stuff because the existing code definitely wasn't working; however, I had to guess at the desired behavior because, again, it wasn't working.

For future reference, and because I hate going to look stuff up over and over, here is the current ammo conservation threshold calc:

```java
                // Desired behavior:
                // At min aggro (0 of 10), require ~50% chance to hit with > 3 shots left
                // At normal aggro (5 of 10), require at least 10% to-hit chance with > 3 shots left
                // At max aggro (10 of 10) require just over 0% chance to hit until at 1 round left.
                toHitThreshold =
                        Math.max(0.0,
                                (0.8/((aggroFactor) + 2) + 1.0 / ((ammoCount*ammoCount)+1)));
```
This `toHitThreshold` is consumed by Princess when deciding whether a shot is worth taking, both when planning movement and assigning attacks.

Some data points:

1. For Aggression 0 (slider all the way down):
1.1 If remaining ammo (of all types) for a given weapon is 7 rounds (chosen for ease of calculation): `toHitThreshold` = (0.4 + 1/50) = 0.42 or 42%; will fire on a TN of 7 or less, but not an 8.
1.2 If remaining ammo is 3, `toHitThreshold` = (0.4 + 1/10) = 0.50 = 50.0%, will fire on a TN of 6 or less.
1.3 If remaining ammo is 1, `toHitThreshold` = (0.4 + 1/2) = 0.90 = 90.0%, will fire on a TN of 4 or less.
2. For Aggression 5 (slider at default middle position):
2.1 If remaining ammo is 7, `toHitThreshold` = (0.114 + 1/50) = 0.134 = 13.4%, will fire on a TN of 10 or less.
2.2 If remaining ammo is 3, `toHitThreshold` = (0.114 + 1/10) = 0.214 = 21.4%, will fire on a TN of 9 or less.
2.3 If remaining ammo is 1, `toHitThreshold` = (0.114 + 1/2) = 0.614 = 61.4%, will fire on a TN of 6 or less.
3. For Aggression 10 (slider at default middle position):
3.1 If remaining ammo is 7, `toHitThreshold` = (0.066 + 1/50) = 0.086 = 8.6%, will fire on a TN of 11 or less.
3.2 If remaining ammo is 3, `toHitThreshold` = (0.066 + 1/10) = 0.166 = 16.6%, will fire on a TN of 10 or less.
3.3 If remaining ammo is 1, `toHitThreshold` = (0.066 + 1/2) = 0.566 = 56.6%, will fire on a TN of 7 or less.

_(Note that ammo above 7 rounds per weapon will return essentially the same value as 7)_

As you can see, the default Aggression setting is fairly conservative, and even the highest Aggression setting won't fire on 12s with the current code.  This definitely needs tweaking.  However, I am fairly pleased with the curve this generates,  as it incentivizes closing for better TNs when ammo runs low, so my proposal is this:
1. Adjust the curve upward so that Aggression 10 will fire at 12s even with 3 rounds remaining for a given weapon.
    Aggression 5 (default) will fire at 12s with 7+ ammo remaining.
    Aggression 0 (minimum) will never fire at 12s, only 11s or better.
 2. Clamp the output of this function to 12 or less, so Princess won't start shooting at 13s.
 3. Add unit tests to confirm the desired thresholds are generated for each Aggression setting and amount of ammo.
 
 This can easily be accomplished without changing any other code besides this function.

**Comment by Sleet01** [comment]
The proposed new function would be:

```
toHitThreshold =
                        Math.max(0.01,
                                (0.6/((8*aggroFactor) + 4) + 4.0 / (4 * (ammoCount*ammoCount) * (aggroFactor + 2) + (4 / (z + 1))));
```
Which gives the following results:
(for remaining ammo of 7, 3, 1 rounds respectively)
1. Aggression 0, shoot at TN 10, 9, 7
2. Aggression 5, shoot at TN 12, 11, 10
3. Aggression 10, shoot at TN 12, 12, 10
with a clamp to max allowed TN of 12 (previously a 13 might have slipped through)

**Comment by Thom293** [comment]
Thank you for explaining.  That looks like a good plan.  Whatever requires the least work for you is good with me.  

Generally, I think the 7 threshold is unnecesary.  Needing 7 ammo for something implies she has a long term plan, which she does not.  But it might be too much of a pain to remove.  

Some low ammo items like AC20 (5 ammo per ton) are in immediate conservation mode at 7, and if they are in long range of something (<9 hexes) the they are for certain being shot by other things and will likely die soon.  Kicking in at 3 I understand but 7 seems too high of a threshold.  But if its too much of a pain to change then its not worth spending the time on.  

Question - what does this do with One Shot weapons like OS Srms or ASF missiles or Rocket Pods or Rocket Launchers?  Ive seen sometimes in missions where a RL turret wont fire at all.  Although I have not tested this recently.  

Regardless whatever you decide is fine with me.  I just just think it should be relaxed a bit.
