### ISSUE TITLE
View > Round Report Does Not Allow Copy & Paste of Text

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#548]
Was testing a dropship landing on this map, game kind of hanged for a while once I finally landed and it had to do all of its calculations for terrain damage but not the point of this.  Next round I clicked View>Round Report to copy ctrl+c and paste ctrl+v the landing damage and it would not copy the text into the clipboard.  Ended turn to get to the current round's round report and then could finally copy and paste text from the end round report.  Windows 7 HQ 0.42.1

[RoundReportTest.sav.gz](https://github.com/MegaMek/megamek/files/998882/RoundReportTest.sav.gz)

**Comment by arlith** [comment]
The issue here is the keyhandler.  The round report dialog doesn't disable hot keys like other dialogs do.  This is a little trickier than other dialogs, because the round report isn't modal: you can open it and keep it open and keep playing.  I think what has to happen is we need to setup focus listeners on the round report dialog and when the dialog gets focus, it disables hotkeys, and when focus is lost it re-enables them.

**Comment by arlith** [comment]
Nevermind, the dialog is modal, so it's a lot easier.
