### ISSUE TITLE
[0.43.2-git: Bug] Hover Craft Can Enter Heavy Woods On Pavement

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#551]
Hover craft can enter heavy woods on pavement. Savegame attached. Move Sand Devil 3 to hex 1914.
[HoverCraftCanEnterHeavyWoodsOnPavement.sav.gz](https://github.com/MegaMek/megamek/files/1003077/HoverCraftCanEnterHeavyWoodsOnPavement.sav.gz)

**Comment by VampireSeraphin** [comment]
Is the pavement in question a road?

**Comment by SirMegaV** [comment]
Visually speaking it was a heavy wood on top of pavement.

**Comment by BLOODWOLF333** [comment]
TacOps
Unless specifically noted otherwise under Base Terrain Types (see p. 30),
no two base terrain types can be found in the same hex.

Woods and pavement are base terrain.  Yes Megamek allows people to break the rules when building maps but, there isnt code to prevent that from happening.  So this is more of an error on whoever built this map.

**Comment by SirMegaV** [comment]
My bad for using a bad map.

**Comment by arlith** [comment]
Presumably, heavy woods on pavement could represent some-type of park.  Since this doesn't really fit into the rules of the game, I'm just going to leave it as is.
