### ISSUE TITLE
Side-Slipping Aero allowed to use backspace to move too early

### ISSUE THREAD

**Issue by TigerShark** [MegaMek/megamek#557]
When using the Side-Slip Aero maneuver, the player is able to use the Backspace button to turn before the maneuver is completed.

Example 1: Correct flight path
![image](https://user-images.githubusercontent.com/951444/27006081-a0f54b84-4de0-11e7-9282-417bafdc4848.png)

Example 2: Incorrect flight path
![image](https://user-images.githubusercontent.com/951444/27006076-7fd6d01c-4de0-11e7-8716-5ddd16ab286b.png)

**Comment by arlith** [comment]
Huh, I thought I realized this years ago and fixed it.  Or maybe I realized this years ago and swept it under the rug... heh.

**Comment by TigerShark** [comment]
I think it was one of those "post-stable" things that never happened after the stable.

**Comment by arlith** [comment]
The fix for this ends up being somewhat straight-forward, I think.  Basically, `MoveStep` should have a maneuver ID state added to it, so we can know what steps belong to a single maneuver.  Then, when you hit remove the last step from a `MovePath`, an additional check should be added to see if the removed `MoveStep` has a maneuver ID, and if so remove all of the consecutive steps in that maneuver.
