### ISSUE TITLE
[0.49.20] ASF in space can fire beyond weapon range

### ISSUE THREAD

**Issue by SJuliez** [MegaMek/megamek#5596]
ASF in space can fire SRM4 at a target at range 7. The weapon display shows "out of range" but the fire button allows firing. The shot misses automatically (correctly) but still happens. Incidentally, the firing arcs show ground ranges beyond the allowed aero range on a weapon such as the SRM4

**Comment by Sleet01** [comment]
I don't think we've ever disallowed firing weapons at out-of-range targets.  It would really slow down the process of heating up TSM 'mechs, for one thing.

When you say "firing arcs show ground ranges", do you mean the firing arc display on the Ground Map?  That may be intended, since Aero weapons get Low Alt ranges on the Ground Map (nominal range x 16).

**Comment by SJuliez** [comment]
Ah I wasnt aware of the first. For the second, no in space; for the SRM4 it shows an S range up to 6 hexes and then an L range and an E range area up to the ground ranges which feels like it shouldnt be.

**Comment by gsparks3** [comment]
Yeah, those extra bands shouldn't be there; previously range bands in space would only display the S/M/L/E bands as appropriate.

**Comment by Sleet01** [comment]
Pretty sure we had an RFE or issue to make Aerospace units display out to Extreme range by default; it should only brighten the range[s] for the current weapon, but should display the full range IIRC.

Let me see if I can find that PR or issue...

**Comment by Sleet01** [comment]
Okay, I made the change that forced Aerospace units to always allow displaying ranges out to E (range band 5) based on a rules check with the Aerospace Discord server, back around 02/18.
But I'm not sure what's causing out-of-range bands to display no matter what - that definitely should not be happening.

**Comment by Sleet01** [comment]
Problem appears to be a combo of:
1. we are now only using the currently-loaded ammo for drawing range bands (rather than the currently-selected ammo in the Weapon Panel)
2. we used to short-circuit drawing the range bands when they exceeded the max range of the selected weapon or weapon+ammo combo, but we no longer do so.

I assume I broke this just because of all the stuff I've touched, but it'd take more time to be sure and I'd rather get this working.
