### ISSUE TITLE
Rasalhague Dominion Force Generator Issues

### ISSUE THREAD

**Issue by repligator** [MegaMek/megamek#5647]
### Environment
Linux
Java 17

### Description
When using the Force Generator, and selecting Rasalhague Dominion, only one Unit Type is available; combined. Only one formation is available; Random. Only one Equipment Rating is available; Random. Hitting generate will always generate a cluster.

Log entries include

`13:58:51,230 WARN  [megamek.client.ui.swing.ForceGeneratorOptionsView] {AWT-EventQueue-0}
megamek.client.ui.swing.ForceGeneratorOptionsView.refreshUnitTypes(ForceGeneratorOptionsView.java:635) - No unit type node found.

13:58:51,231 WARN  [megamek.client.ui.swing.ForceGeneratorOptionsView] {AWT-EventQueue-0}
megamek.client.ui.swing.ForceGeneratorOptionsView.refreshRatings(ForceGeneratorOptionsView.java:754) - No rating found.`

### Files
[megamek.log](https://github.com/user-attachments/files/16041728/megamek.log)

**Comment by HammerGS** [comment]
The underlying issue is the faction data isn't defined. If you open any of the Clan files in teh data\forcegenerator\faction_rules folder you'll see the difference. There isn't an editor to create these files and have to be hand made assuming we have canon data on the formations. 

As of the development of this (2018) we did have that. So this will have to get addressed at some point but won't be a quick of easy fix. 

<img width="637" alt="image" src="https://github.com/MegaMek/megamek/assets/13752452/a4f9f085-8d77-4658-b957-3097f07954a4">

**Comment by repligator** [comment]
I've sent in a PR. Even though CGB is technically 50-ish years out of date, most of it is still accurate, and I'd argue that occasionally anachronistic force names are the lesser evil compared to not being able to generate forces at all.
