### ISSUE TITLE
Diacratics and/or name changes causing issues with Force/RAT Generator

### ISSUE THREAD

**Issue by repligator** [MegaMek/megamek#5648]
### Environment
49.20
Java 17
Linux

### Description
Select year 3100, faction Ghost Bear Dominion, unit type Battle Armor, check Marine, hit generate. Clan Medium Battle Armor (Naval) 'B**a**r' (Sqd5) and/or Clan Medium Battle Armor (Naval) 'B**ä**r' (Sqd5) will not appear. The log will show various errors relating to not being able to find one or both of the aforementioned squads. I've tried changing various ä's to a's and a's to ä's, without any luck.

### Files
[megamek.log](https://github.com/user-attachments/files/16041857/megamek.log)

**Comment by HammerGS** [comment]
Going to leave this open for a bit.

**Comment by repligator** [comment]
Same results as before.
[megamek.log](https://github.com/user-attachments/files/16044413/megamek.log)

**Comment by HammerGS** [comment]
The underlying issue is the faction data isn't defined. If you open any of the Clan files in teh data\forcegenerator\faction_rules folder you'll see the difference. There isn't an editor to create these files and have to be hand made assuming we have canon data on the formations. 

As of the development of this (2018) we did have that. So this will have to get addressed at some point but won't be a quick of easy fix. 

<img width="637" alt="image" src="https://github.com/MegaMek/megamek/assets/13752452/a4f9f085-8d77-4658-b957-3097f07954a4">

**Comment by repligator** [comment]
@HammerGS Was this meant for #5647 ?

**Comment by HammerGS** [comment]
It was.

**Comment by HammerGS** [comment]
Ok, two part issue the Diacratic was part of the problem. But the bigger issue was a complete lack of data for the unit. The roles underneath in the RAT Generator will only filter if that unit has that role. Currently most units don't have a role so you're better to avoid selecting them. 

Fixed in the nightlies.
