### ISSUE TITLE
Princess-controlled Aerospace fighters cannot ground-attack or bomb when equipped with bombing ordnance. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/megamek#5755]
### Environment
01:31:37,842 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:142) - Starting MegaMek v0.50.0-SNAPSHOT
    Build Date: 2024-07-18T01:16:04.265828280
    Today: 2024-07-20
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MegaMek: 4 GB
    MM Code Revision: Unknown
    MML Code Revision: Unknown
    MHQ Code Revision: Unknown

### Description
Princess-controlled Aerospace fighters are not able to perform ground-attacks or bombing attacks when equipped with any ordnance delivered using bombing actions. This includes: HE, Inferno, Thunder and Cluster bombs, as well as Small and Large Fuel-Air-Bombs. She will commit to ground-attacks using TAG, rocket-pods, or without bombs fine, but the presence of any bomb prevents regular behaviour. She just flies around and looks pretty instead <3

[gameoptions in use when observed.zip](https://github.com/user-attachments/files/16317767/gameoptions.in.use.when.observed.zip)

**Comment by repligator** [comment]
Would you mind running this test map? I suspect the lack of attacks may be caused by some ongoing air-to-ground detection/spotting issues. The C3 turrets will ensure that Princess can spot your units.
[princess_bomb_test.sav.gz](https://github.com/user-attachments/files/16318057/princess_bomb_test.sav.gz)

**Comment by Tzahr** [comment]
"Error: unable to load game file. "
I seem to be having a general issue loading _any_ savegame actually. 
Might need to investigate that seperately.

**Comment by repligator** [comment]
It might just be because I just synced my fork with master a few minutes ago. It's just the map AeroBase 2 with 3 C3 turrets and 3 bombers (with bombs) for princess, and 3 big mechs for the player so Princess has something to target.

Interestingly, although Princess will perform air-to-ground attacks while carrying bombs, I can't seem to get her to actually drop the bombs. It might just be a matter of damage calculation showing bombs as the inferior option though.

**Comment by Tzahr** [comment]
I attempted to duplicate these conditions: no ground attacks of any kind. 
All fighters were carrying bombs. 

![image](https://github.com/user-attachments/assets/b2811686-eee2-49d3-98d2-c29216df23ae)

**Comment by Sleet01** [comment]
Looks like this is related to the 0.49.20 non-firing issue; dive-bombing attacks are getting the "no ammo" result and giving up, but apparently only _after_ guiding the unit to the path that makes the dive-bombing attack viable.

**Comment by Sleet01** [comment]
We need to pass in at least one real mounted bomb to act as the ammo for determining to-hit chances.
All this because we were using bombs as both ammo _and_ weapons previously :_:

**Comment by Sleet01** [comment]
The Riever's not an especially good testbed, though; it's doing 84 damage on 5+ TN vs non-moving targets, which bombs are going to have a hard time beating.

Lemme try the same scenario with something toothless but bomb-capable, like a Jump Bomber...

**Comment by Tzahr** [comment]
Ran a simple test with Jump Bombers. 
Bomb-equiped Jump Bombers did not bomb. 
Rocket-equiped Jump Bombers _did_ ground attack.
