### ISSUE TITLE
Bandit (C) Invalid units

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megamek#596]
This problem exists with both 0.42.2 and 0.43.3 versions of MegaMek.
The Bandit (C) series of vehicles, as they come with the program, are mostly invalid. While the Prime and C are fine, the A, B, D, E, F and H have two points of armor unallocated (one point missing on left and right side).
Furthermore, variants B, E and H are 0.5T overweight because they have 9.5T of armor rather than the 9T they should have.
Finally, variant G is using two more slot than it has access to.

Several of the variants are marked as "advanced" without discernable reason.

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/megamek/commit/df36ca4c586a4143d1fe649d827b90aad7458a38

The 'G' Variant won't fix it looks like it has been designed by CGL wrong.  I suspect the original intent was to have the array themselves hold 0 crit slots but they are listed as 1 slot.

![image](https://user-images.githubusercontent.com/13752452/29998920-221d0508-8ff4-11e7-8e39-968162990f70.png)

**Comment by Xeno426** [comment]
Searching through the CGL forums, it seems they are aware of the Bandit (C) G issue.
http://bg.battletech.com/forums/index.php?topic=5933.0
I have been so far unable to find any info on what the final errata decision was.

**Comment by HammerGS** [comment]
Our policy is to leave the units per the RS until CGL releases official errata. At this time the unit will remain invalid.
