### ISSUE TITLE
12/13 logistic/0.50.02 - can no longer reassign bot behavior or reactivate or kick bots once game has started

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/megamek#6277]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

The pane is missing the option to set the bot behavior, and the kick/replace functionality is broken, it does nothing
![image](https://github.com/user-attachments/assets/92add7d5-2035-4ae7-b536-93baea1e3245)

### Steps to Reproduce

load into any game with megamek and attempt to adjust bot behavior, kick, replace bots

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/13 Logistics Overhaul '0.50.02-SNAPSHOT'

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by OrbMonky** [comment]
This appears to be resolved in 12/16 Logistics Artifact - 0.50.02 Snapshot, I see the options in that version.

**Comment by OrbMonky** [comment]
Well, I take that back. On loading a save, it does not have the options.
![image](https://github.com/user-attachments/assets/fd7b7a8d-a0d2-4ef0-a405-339995dfb9a2)

**Comment by psikomonkie** [comment]
@OrbMonky - Hey! Took me a bit to figure out what the actual issue was. I was unable to find any issue with adding bots. When loading a saved game either from MegaMek or loading a save via MekHQ I was able to use Edit Bots to add bots. However, as the game is in progress, Princess is added as a Remote Bot - it can't be edited once added. This is how it worked in 49.19. To edit the bot, you should just kick the bot and when adding the bot you can change the settings - but like you pointed out, kicking the bot isn't possible. 

To fix this, I've fixed kicking bots/players.
