### ISSUE TITLE
Rapid Fire ACs With ASF

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#654]
![image](https://user-images.githubusercontent.com/16950832/30509322-9fae96e2-9a73-11e7-996d-079956a11714.png)
Changed my two AC/2s to rapid fire and shot at the Stingray and I guess the mode did not change.  I know rapid fire works for mechs currently, this is just a low atmosphere ASF test battle to see if you can land a dropshop on LA maps (you can't but still draws the big 7-hex DS image once the DS reaches alt 0, confusing).

Player name: BLOODWOLF
[RapidACs.zip](https://github.com/MegaMek/megamek/files/1308093/RapidACs.zip)

**Comment by neoancient** [comment]
Because aerospace units cannot use indirect fire and ultra/rotary acs always fire at the maximum rate, aero units ignore mode switches. The question here is whether the rule in TW that aeros always use the maxiimum firing rate also applies to standard ACs if the optional rapid-fire rule from TO is in use. If so, the mode needs to be set the same time that it's set for ultras and rotaries.

**Comment by pheonixstorm** [comment]
Closest possible answer might be if it is stated how burst fire rules for MGs are handled for aero.

**Comment by HammerGS** [comment]
http://bg.battletech.com/forums/index.php?topic=56440.0

Based on that ruling I'd say no.

**Comment by HammerGS** [comment]
Closed at Original Posters request.
