### ISSUE TITLE
Build failure due to TinyXML still listed in classpath

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#67]
Updated my fork to the latest code to continue working and eclipse gave me 2 warnings about tinyXML and its source package. It is still listed in classpath.

Would this also affect MML or HQ?

**Comment by nderwin** [comment]
Can you attach the error messages?  All traces of it should be removed from the master branch at this point.  It could also be something peculiar to Eclipse.

Note also that since the MML and HQ repos contain a MegaMek.jar file, it would need to be replaced with a newer build for those projects to function from their respective master branches.  I'm not sure what process the main devs use to update that, so it was not included in any of my pull requests.

**Comment by Dylan-M** [comment]
There is a .classpath file that references all the classpath info for Eclipse. I'll take care of updating it. As for updating the jar files in the other projects, I don't normally do it except during a release. I will however make an exception today so that the projects are still buildable.
