### ISSUE TITLE
Arrow IV infernos calculate cover incorrectly?

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#696]
![megamek](https://user-images.githubusercontent.com/1191378/31454377-fcb39544-af00-11e7-8ca8-800018dbabd0.jpg)

I fired Arrow IV infernos at the hex with the stormcrow, but for some reason the adjacent Fire Falcon D was getting cover from the Arrow IVs...even though it was right next to the target hex.

`Weapons fire for Mobile Long Tom Artillery LT-MOB-27 #2 (#battletech)
    Arrow IV at Hex: 2345 (Artillery); needs 1, rolls 12 : hits the intended hex 2345.
        Inferno fire (Arrow IV) started in hex 2345.
            Ryoken (Stormcrow) C (Clan Jade Falcon) hit by Inferno IV:                Target gains 10 more heat during heat phase.

        Inferno fire (Arrow IV) started in hex 2344.
        Inferno fire (Arrow IV) started in hex 2444.
        Inferno fire (Arrow IV) started in hex 2445.
        Inferno fire (Arrow IV) started in hex 2346.
        Inferno fire (Arrow IV) started in hex 2245.
            Fire Falcon D (Clan Jade Falcon) hit by Inferno IV:                Target gains 0 more heat during heat phase.

                5 missiles hit the cover.`

Im also not sure why it says 5 missiles hit the cover when it was one Arrow IV Inferno.

[#battletech.sav.gz](https://github.com/MegaMek/megamek/files/1376511/battletech.sav.gz)

[mekhqlog.txt](https://github.com/MegaMek/megamek/files/1376514/mekhqlog.txt)

**Comment by neoancient** [comment]
Per the rules in TacOps, the effect of an Arrow IV inferno round is equivalent to being hit by five inferno missiles, which is how it is implemented in MM. Based on the round report and the save file there appears to have been a building just north of the Fire Falcon at the time of the attack (since reduced to rubble) which is where the partial cover comes from. By treating the artillery inferno attack as an SRM5 inferno attack against every unit in the target hex and the surrounding hexes it was applying the partial cover rules. I added a flag to indicate an area effect attack which ignores partial cover.
