### ISSUE TITLE
Movement for units over water or sumerged in water is using subsurface terrain

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/megamek#721]
Movement for units over water or sumerged in water (submarine) are using subsurface Terrain movement penalties, which should not be the case for VTOL, Surface ships or submarines. I suspect Connections to the following already reported issues:

https://github.com/MegaMek/megamek/issues/521
https://github.com/MegaMek/megamek/issues/674

Some screenshots are attached.

![hover over water](https://user-images.githubusercontent.com/28268113/32065301-aca21e04-ba7c-11e7-9416-2eb7eef09f0b.png)
![sea skimmer over water](https://user-images.githubusercontent.com/28268113/32065302-acc1478e-ba7c-11e7-87af-fc29f77253e8.png)
![surface ship on water](https://user-images.githubusercontent.com/28268113/32065303-acdd3d04-ba7c-11e7-99d9-91649f5f01c0.png)
![vtol over water](https://user-images.githubusercontent.com/28268113/32065304-ad00427c-ba7c-11e7-8f61-33081fd4c852.png)

**Comment by wildj79** [comment]
The problem I see here, is that you have water hexes at different levels next to each other.  Depth and level's are two different concepts, and based on your screen shots, everything is working as it should. Though, I would question why you have water hexes next to each other that are at different levels.

The only real error I see here is in the last attached image, which shows a VTOL being slowed because it is traveling over water.

**Comment by HammerGS** [comment]
As an extension of this I'd be curious to see the board file.

**Comment by mwberlindeu** [comment]
The board is the 50x50 urbanruins map included in the megamek package.

[urbanruins.zip](https://github.com/MegaMek/megamek/files/1419382/urbanruins.zip)

**Comment by mwberlindeu** [comment]
> The problem I see here, is that you have water hexes at different levels next to each other. Depth and level's are two different concepts, and based on your screen shots, everything is working as it should.

I think rather not. If I look at the map. I see the intention to model a seafloor not a cascading waterfall. Assuming the first Surface water vessels should have no maneuvering encumberance.

**Comment by wildj79** [comment]
I can see what the intention is, but the map is executed incorrectly. Again, levels and depth are two different things. The problem here, is that the map is setup more like a waterfall, with water hexes at different levels, instead of having all of the water hexes at the same level, but with different depths.

**Comment by BLOODWOLF333** [comment]
Not all of our boards are done correctly, this one needs to be re-done because the depth of water can be used to simulate a sloping sea floor for example.  This is just done funky.  None of the boards are really "official" so some of them can have human error.

**Comment by neoancient** [comment]
The level of a hex determines where the water's surface is. The depth of the water determines how far below the surface the sea floor is. To implement a sloping sea floor, the level of each hex should be the same and only the depth should change.
