### ISSUE TITLE
Oblique Attacker can't indirect fire without a spotter

### ISSUE THREAD

**Issue by blah2355** [MegaMek/megamek#737]
According to CamOps and the tooltip, Oblique attacker should allow indirect fire without a spotter or LOS. In my testing, I set up two mechs with LRM launchers (with Friendly Fire on) and placed them where they had no LOS on each other. Both pilots had Oblique attacker but could not target each other with indirect fire. However, with a spotter, they were able to target each other with the -1 to hit bonus.

**Comment by ObviousTech** [comment]
This is not mentioned in the description in CO, but in the AToW rules for Oblique Attacker, the firing unit needs to pass a sensors check in order to do this.  

My guess is they need to be within sensor range in megamek or this is just not implemented yet.

This commit looks relevant:  https://github.com/MegaMek/megamek/commit/41a88aa3b8a5336e51ae99bc53e826c013df32b1  Seems like it is already implemented.

**Comment by blah2355** [comment]
I actually did do a test with TacOps sensors enabled as well but was still not able to indirectly fire.

**Comment by VampireSeraphin** [comment]
Sensor rolls can fail. Did you have double blind enabled and were you able to confirm that you passed the sensor check? Most sensors will not give you a successful result through terrain that blocks normal LOS. Generally you would need a unit with BAP and lrms.
