### ISSUE TITLE
[0.43.2-git : Bug] Better Princess Deployment

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#752]
There are times (quite frequently) when Princess deployed somewhere they can't move at all. Example:

1. In between buildings or in the middle of a ring shaped building
2. A wheeled vehicle in an opening in the middle of a forest
3. Inside building
4. Etc Etc

Image attached for 1, 3 and 4 (please note that the space hex is actually light jungle.

![image](https://user-images.githubusercontent.com/17064665/32761259-5fa80ab8-c92d-11e7-84b0-56a18a462b95.png)

![image](https://user-images.githubusercontent.com/17064665/32761276-78310b48-c92d-11e7-9ab8-ca2458909a59.png)

![image](https://user-images.githubusercontent.com/17064665/32761288-8c1864a8-c92d-11e7-8442-d35af253d9f4.png)

Possible to let princess to check maybe 3 movable hexes before deployment?

**Comment by NickAragua** [comment]
I've got a few ideas about this, but they won't make it into this release.

**Comment by dericpage** [comment]
I amended the deployment code a while back to check for viable paths to the board center when testing a hex for potential deployment.  Obviously, there's problems with this if the deployment area is set to center or any (those should probably check for a valid path to the home edge).

Regardless, if you want to discuss ideas or just get a better idea of what the heck I was thinking with my code changes, feel free to ping me.

**Comment by NickAragua** [comment]
Well, I was wrong. This should be at least partially addressed as of PR #771. There's still some more work to be done in the area, but it should cover the vast majority of situations involving units deploying in a cul-de-sac.

**Comment by NickAragua** [comment]
Fixed a number of bugs with the previous PR. As before, the expected behavior is that Princess will no longer deploy units in completely inaccessible cul-de-sacs, or in building interiors (however, outer building hexes or one-hex buildings are still fair game).

Unfortunately, she still may not be able to find her way out of particularly hairy enclosures where there's technically a path to the outside but it leads through a rat maze. That is a different issue altogether.
