### ISSUE TITLE
Grippling a 'mech involved in a Grapple may cause hang (save attached)

### ISSUE THREAD

**Issue by VictorMorson** [MegaMek/megamek#81]
[GrappleBug-SubmitLater.sav.gz](https://github.com/MegaMek/megamek/files/173284/GrappleBug-SubmitLater.sav.gz)

NOTE:  The attached save was played on a map with custom tilesets; the map may not be visible without these files.
-

During a match, an Archer was grappling a Jagermech, and in the process, destroyed it's arms (while losing one of it's own arms).  The grapple continued until a second unit fired into the melee to attack the Jagermech, hitting it's gyro repeatedly and knocking it down.

On the Jagermech's turn, the game hung and refused to progress past this point.  I believe the primary cause was being knocked during during a grapple but there were numerous factors at work (as mentioned above).   

Additional Issue:  The Archer took no penalty to maintain the grapple after losing an arm.  I am unsure if it is related.

**Comment by arlith** [comment]
Alright, I think I know what's going on here, and it's tricky... 

The JagerMech is KOed, and is the only unit on that side.  Since DB is on, and the JagerMech is the only unit, that player doesn't spot any other enemy units, including the unit that is grappling him.  So, his client doesn't know about the Archer (eId 11), and when the counter grapple turn fires, the client can't target the archer, because it doesn't know about it.  Since it doesn't know about the archer, the target is "null" and end sup causing an NPE at some point.  I feel like, unconcious/immobile targets shouldn't be allowed a counter grapple turn, but I need to read some rules.

**Comment by arlith** [comment]
Fixed in b0986c2.

According to TW, units that are immobile cannot "move, fire or take any other action."  So, units that are immobile should not be able to make a counter-grapple attack.  Based on this, I add a condition to the code in Server, that will only add the `CounterGrappleTurn` if the defender is able to make a counter grapple.

This will prevent the issue you are encountering, although it won't fix the save.  If you'd like to continue this scenario, have GMake leave the game and skip his turn, it'll have the exact same effect as declining the counter grapple attack, or what would happen after the fix (the Archer automatically succeeds).

**Comment by VictorMorson** [comment]
Thanks for the input everyone!  We ended up continuing the scenario by reloading into the movement phase and just ejecting the Jagermech flat out after intentionally breaking the grapple.  But thanks to both the fix and the explanation, I'm very glad we don't have to blacklist grappling from our normal games (which was the major concern, we have a player built around being good at grappling).

Awesome folks.
