### ISSUE TITLE
Dropship Deployment Overlapping

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#82]
MegaMek version 0.41.15

Related to sourceforge #4388 Dropship Stacking Issue during Deployment  and #4219 Issues with stacking violations and MovePaths, both closed. 

Princess is still having stacking issue when deploying grounded dropship. Savegame attached after deployment.

[OverlappingDropshipDeployment.sav.gz](https://github.com/MegaMek/megamek/files/173294/OverlappingDropshipDeployment.sav.gz)

**Comment by arlith** [comment]
Fixed in c0e6621.

Ultimately, the problem came down to `BotClient.getCoordsAround` which is now renamed to `BotClient.getFirstValidCoords`.  The way it works is, in `Princess.calculateDeployment` a list of possible deployment coords is created.  This list is ranked and returned, and then `BotClient.getFirstValidCoords` will then find the first coords in that list that doesn't violate stacking.

However, because Compute.stackingViolation didn't have an applicable function signature, stacking violation computation was done "by hand", and was woefully incomplete.  In this case, it didn't have any logic whatsoever for landed Dropships. (Actually, I should mention, the underlying issue is that, for deployment, the Server doesn't validate the deployment packet; it trusts the client.  This is a potential issue that should be fixed.)

What I did to fix this is create a new function signature for `Coords.stackingViolation` that allows the caller to pass in a position, instead of using the passed `Entity`'s position.  Now, `BotClient.getFirstValidCoords` uses the same stacking violation logic as everywhere else.
