### ISSUE TITLE
VTOL Special Attacks rule changes [TacOps]

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/megamek#883]
Few items:

- Tactical Operations Errata v3.6, p.23 changes the VTOL movement penalty for carrying bombs to "each bomb carried reduces the VTOL’s Cruising MP by 1". (MegaMek seems to still be using the old rule of 1 MP loss for every 5 bombs.)

- Tactical Operations Errata v3.6, p.23 changes the name of this optional rule from "VTOL Special Attacks" to "VTOL Bombing" (I guess due to removing strafing entirely) - the rule name in MegaMek could be changed accordingly (or given some transitional name, e.g. "VTOL Bombing (formerly VTOL Special Attacks)"

- **Bug?** MegaMek currently applies an attacker movement TH modifier to VTOL dive bombing. However, I don't see this mentioned anywhere in either TacOps or TW - only that VTOL dive bombing follows the same rules as AS dive bombing, and I don't believe AS units get an attacker movement TH modifier.

**Comment by neoancient** [comment]
While VTOL strafing has been removed from the official rules, it is available as an unofficial option in MM if the VTOL special attacks option is selected.

The fact that aerospace units do not get a TH modifier for attacker movement when bombing is not because it's a bombing attack but because they never apply a TH modifier to any attack, while VTOLs do.

**Comment by RexPearce** [comment]
To clarify, the first bullet wasn't about VTOL strafing, rather about a rule name change.

That is, MegaMek currently refers to a rule that no longer exists: "VTOL Special Attacks". It no longer exists because it's been renamed to "VTOL Bombing" in the errata.

Anyway, its a minor thing either way.
