### ISSUE TITLE
Kraken (Bane) 3 costs over 5 billion c-bills

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megamek#949]
### Environment
0.43.9 RC3
Windows 7
Java build 1.8.0_161-b12

### Description
The Bane 3 has a C-bill cost in excess of 5 billion, as seen in the image. Further, trying to recreate the mech (setting armor, mass, speed, HS, etc) works without issue until any ammo is added to the design (even from the one-shot SRM). In fact, a single LRM-15 launcher with ammo on a 100T Clan chassis with 19T armor and 3/5 movement (and only 10 DHS) sees the cost shoot through the roof.
![bane3](https://user-images.githubusercontent.com/3220418/37836608-e8a6691e-2e80-11e8-9cb8-c90a6fb7852f.JPG)
This may be better placed in the MML GitHub, but it appears to affect regular MM just as much as the Lab. I'll leave it to mod discretion as to where it is best placed.

**Comment by Xeno426** [comment]
So, further testing seems to suggest it's deeper than this. This appears to apply to *any* mech that is set as Clan (including Mixed Clan) that is given just a single Clan LRM of *any* size and a single tonne of ammo. A 25T Clan mech with absolutely nothing else with a single cLRM-5 and one tonne of ammo costs over three billion C-bills.

**Comment by Playergh** [comment]
Also something that might be worth noting is that when I placed the Kraken 3 in my list in Megamek (version 0.43.9-RC3, windows 8.1) the price capped at 214.783.647 c-bills instead of listing the full 5 billion. I also did not encounter this issue when working with my 0.43.4 meklab, where not only the kraken but all other clan mechs had their correct price until in-game. The Kraken 3 is also the only unit I've seen so far with this incorrect price, and dumping ammo in the lobby doesn't seem to change it
