### ISSUE TITLE
Feature Request: Using "xz" instead of "gzip" in Linux version packing

### ISSUE THREAD

**Issue by MGM175** [MegaMek/megamek#968]
Can be possible, to replace gzip with xz in (at least) stable 0.44 for Linux?

Here is the reason why:

`mgm175@mgm175q4os:~$ du -h megamek-v0.43.10-RC4.tar.gz
93M     megamek-v0.43.10-RC4.tar.gz
mgm175@mgm175q4os:~$ du -h megamek-v0.43.10-RC4.tar.xz
88M     megamek-v0.43.10-RC4.tar.xz`

Yes, 5 MB less, but it could be useful in the future, especially that each build is bigger and bigger.

**Comment by Dylan-M** [comment]
Personally I would have gone with bz2. However, the reason neither of those options was done is because gzip is almost guaranteed to be on any Linux or UNIX, thus making the package instantly extractable on pretty much everything. Yes, you could make the argument that bz2 and xz (and while we're at it, just about every other archive format) is much more prolific now and I would agree. However, gzip is almost always installed by default, and often other formats are not. This makes it difficult for those with a lower knowledge level. I personally feel that we shouldn't raise the barrier to entry any higher than it already is.

**Comment by jayof9s** [comment]
Closing out for reasoning above.
